### PR TITLE
Prevent read on TSDB once closeAllTSDB function has been called

### LINKED ISSUE #3350: Ingester trying to open a TSDB block index reader while shutting down
**Describe the bug**
Today I experienced the following log while an ingester was shutting down after getting the `/shutdown` endpoint called:

```
Issue: `level=warn ts=2020-10-14T08:35:20.077984655Z caller=grpc_logging.go:55 method=/cortex.Ingester/QueryStream duration=11.567608ms err="open querier for block 01EMJ919X41XRBW40XW40DDVZA: open index reader: block is closing" msg="gRPC\n"`
```

**Expected behavior**
We should add a circuit breaker to make sure no read occurs on TSDBs once `Ingester.closeAllTSDB()` has been called.

**Storage Engine**
- [x] Blocks
- [ ] Chunks

### PR DESCRIPTION
**Pull request by ilangofman**
**What this PR does**:
Added another variable in the `TSDBState` that prevents any read occurring on the TSDB once the ingester has called the `closeAllTSDB` function. 

**Which issue(s) this PR fixes**:
Fixes #3350

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ingester/ingester_v2.go [hunk 1]
```diff
@@ -677,6 +681,12 @@ func (i *Ingester) updateLoop(ctx context.Context) error {
 			i.ingestionRate.Tick()
 		case <-rateUpdateTicker.C:
 			i.userStatesMtx.RLock()
+
+			if i.TSDBState.closed {
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:685]: This cannot possibly happen. `updateLoop` is called while Ingester is in `Running` state. Only when this function returns, ingester goes to `Stopping` state and will call `closeAllTSDB`.

File: pkg/ingester/ingester_v2.go [hunk 2]
```diff
@@ -1483,6 +1497,10 @@ func (i *Ingester) v2QueryStreamChunks(ctx context.Context, db *userTSDB, from,
 func (i *Ingester) getTSDB(userID string) *userTSDB {
 	i.userStatesMtx.RLock()
 	defer i.userStatesMtx.RUnlock()
+	if i.TSDBState.closed {
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1500]: I don't think we should check the flag here. We should instead check for closing state in query functions (v2LabelNames, v2LabelValues, ...). Behaviour of query methods will be more explicit that way.

File: pkg/ingester/ingester_v2.go [hunk 3]
```diff
@@ -415,6 +416,9 @@ type TSDBState struct {
 	appenderAddDuration    prometheus.Histogram
 	appenderCommitDuration prometheus.Histogram
 	idleTsdbChecks         *prometheus.CounterVec
+
+	closed bool // protected by userStatesMtx
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:420]: I am wondering if we should use an extra boolean flag, or rely on Stopping state of ingester. Extra boolean flag allows us to reply to query functions while compaction and shipping loops are still running, but in practice I'm not sure if it makes enough difference compared to just using ingester's state.

Therefore I would suggest we remove this flag. We can already check for ingester's state (`i.State() == services.Stopping`) and reject queries in that case. Ingester only calls `closeAllTSDB` after it enters `Stopping` state (and after its subservices have finished).

File: pkg/ingester/ingester_v2.go [hunk 4]
```diff
@@ -1236,6 +1246,10 @@ func (i *Ingester) v2AllUserStats(ctx context.Context, req *client.UserStatsRequ
 	i.userStatesMtx.RLock()
 	defer i.userStatesMtx.RUnlock()
 
+	if i.TSDBState.closed {
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1249]: If we return error here, distributor will also report error to user. Would it be better to return empty response?

File: pkg/ingester/ingester_v2.go [hunk 5]
```diff
@@ -1493,6 +1511,11 @@ func (i *Ingester) getTSDBUsers() []string {
...
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1514]: Please remove this check. No code using this method should run when ingester is Stopping.

File: pkg/ingester/ingester_v2.go [hunk 6]
```diff
@@ -1510,10 +1533,10 @@ func (i *Ingester) getOrCreateTSDB(userID string, force bool) (*userTSDB, error)
 	i.userStatesMtx.Lock()
 	defer i.userStatesMtx.Unlock()
 
-	// Check again for DB in the event it was created in-between locks
+	// Check again for DB in the event it was created or closed in-between locks
 	var ok bool
 	db, ok = i.TSDBState.dbs[userID]
-	if ok {
+	if ok && !i.TSDBState.closed {
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1539]: Please revert this change. No code using this method should run when ingester is stopping (after adding state-checks to query methods).

File: pkg/ingester/ingester_v2.go [hunk 7]
```diff
@@ -1534,6 +1557,11 @@ func (i *Ingester) getOrCreateTSDB(userID string, force bool) (*userTSDB, error)
 		}
 	}
 
+	// If all the TSDB's are in the process of closing, then should not proceed to creating a new TSDB
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1560]: Please remove this change. Same comment from above applies.

**Review by pstibrany — COMMENTED** [review]
Thank you for working on this. I think we should just use ingester's state to reject queries. In practice difference between entering Stopping and calling closeAllTSDB is tiny.

File: pkg/ingester/ingester_v2.go (hunk 1 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: That makes sense, thanks for catching that mistake.

File: pkg/ingester/ingester_v2.go (hunk 2 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: I've removed the check from this function and added to the query functions.

File: pkg/ingester/ingester_v2.go (hunk 3 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: I agree, I don't think it is necessary to have the extra boolean. I've removed the `closed bool` and added the check as per your suggestion.

File: pkg/ingester/ingester_v2.go (hunk 4 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: That's a really good point. I've changed it so that if the ingester is stopping, then the queries will log a message and return an empty response.

File: pkg/ingester/ingester_v2.go (hunk 5 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Good catch, I've removed it.

File: pkg/ingester/ingester_v2.go (hunk 6 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Good catch, I've removed it.

File: pkg/ingester/ingester_v2.go (hunk 7 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Good catch, I've removed it.

**Review by bboreham — COMMENTED** [review]
Would it be less repetitive to do the check in `i.getTSDB()` ?

**Comment by pstibrany** [comment]
> Would it be less repetitive to do the check in `i.getTSDB()` ?

I advocated against that. I think having it on read path is more explicit than returning `nil` from `getTSDB`.

File: pkg/ingester/ingester_v2.go [hunk 8]
```diff
@@ -1787,6 +1827,13 @@ func (i *Ingester) getMemorySeriesMetric() float64 {
 	defer i.userStatesMtx.RUnlock()
 
 	count := uint64(0)
+
+	// If the TSDB is in the processes of closing, then return 0
```
[the remark this answers is not in the document]
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Makes sense. I've removed it.

**Comment by bboreham** [comment]
> having it on read path is more explicit 

Sorry, I missed that discussion. Did you talk about returning an error?

**Comment by ilangofman** [comment]
> Sorry, I missed that discussion. Did you talk about returning an error?

I can change it to return an error from `getTSDB`. Would that be more preferable?

**Comment by pstibrany** [comment]
> > Sorry, I missed that discussion. Did you talk about returning an error?
> 
> I can change it to return an error from `getTSDB`. Would that be more preferable?

My opinion is that simple "getter" should simply return element from map, and not check for internal state of the ingester. This state only affects read-path, where it should be checked.

**Comment by bboreham** [comment]
> This state only affects read-path

Not sure I get this part. We wouldn't want to reopen a TSDB for write, would we?

**Comment by pstibrany** [comment]
> Not sure I get this part. We wouldn't want to reopen a TSDB for write, would we?

Right, we wouldn't. What I was trying to say is to add checks to read methods for this state – because that is where it will be more explicit, instead of getter.

On write path, we could either use `getOrCreateTSDB` or preferably add check for ingester state at the beginning of `v2Push`. Later in that method we also check for `stopped` flag, but we don't actually call `i.stopIncomingRequests()` in blocks code.

File: CHANGELOG.md [hunk 9]
```diff
@@ -2,6 +2,7 @@
 
 ## master / unreleased
 
+* [BUGFIX] Ingester: Prevent any reads on TSDBs once `Ingester.closeAllTSDB()` has been called. #3350
```
Comment (pracucci) [inline CHANGELOG.md:5]: Few things please:
- Could you rebase `master` and, after rebasing, move the change log entry under "master / unreleased"?
- Please specify the PR number #4304 instead of the issue number #3350
- We're used to sort CHANGELOG entries by type: CHANGE, FEATURE, ENHANCEMENT, BUGFIX

File: pkg/ingester/ingester_v2.go [hunk 10]
```diff
@@ -992,6 +992,11 @@ func (i *Ingester) v2Query(ctx context.Context, req *client.QueryRequest) (*clie
 
 	i.metrics.queries.Inc()
 
+	if i.State() == services.Stopping {
```
Comment (pracucci) [inline pkg/ingester/ingester_v2.go:995]: I'm not sure this is actually a real change. `v2Query()` is called by `Ingester.Query()` which already does this check calling `i.checkRunningOrStopping()`.

_Same comment applies to other functions._

Comment (pstibrany) [reply pkg/ingester/ingester_v2.go:995]: Change is that while `i.checkRunningOrStopping()` is used to allow querying in `Stopping` state, here we disable it.

Comment (pracucci) [reply pkg/ingester/ingester_v2.go:995]: Oh sorry. Well, then we should change the check in `Ingester.Query()`, no?

Comment (pstibrany) [reply pkg/ingester/ingester_v2.go:995]: That's an option too. Chunks code currently allows querying during Stopping, this change would break it. In chunks with transfers enabled, Stopping can take long time, so it makes sense there.

File: pkg/ingester/ingester_v2.go [hunk 11]
```diff
@@ -992,6 +992,11 @@ func (i *Ingester) v2Query(ctx context.Context, req *client.QueryRequest) (*clie
...
+		level.Warn(i.logger).Log("Cannot retrieve TSDB, as the Ingester is in the process of stopping and closing all TSBD")
```
Comment (pracucci) [inline pkg/ingester/ingester_v2.go:996]: Logs must be in the form `("msg", "<put the message here>")`. Also `TSDB` is mispelled.

```suggestion
		level.Warn(i.logger).Log("msg", "Cannot retrieve TSDB, as the Ingester is in the process of stopping and closing all TSDB")
```

_This comment applies to all other places too._

Comment (pracucci) [reply pkg/ingester/ingester_v2.go:996]: Also, is this a warning? Doesn't like something actionable. It's by design, so I'm wondering if we should log it at all (or a debug at most). @pstibrany ?

File: pkg/ingester/ingester_v2.go (hunk 10 above)
Comment (pracucci) [reply pkg/ingester/ingester_v2.go:995]: Ok, let's keep it as is.

However, if we keep logging it, then maybe an utility similar to `checkRunningOrStopping()` may be a nice to have to avoid repeating the same log over and over.

File: CHANGELOG.md (hunk 9 above)
Comment (ilangofman) [reply CHANGELOG.md]: Thanks for letting me know. Should be updated now.

File: pkg/ingester/ingester_v2.go (hunk 11 above)
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: I changed it to a debug level, but if it isn't required, I can remove the log message completely.

Comment (pstibrany) [reply pkg/ingester/ingester_v2.go]: I don't think this log message is too helpful. Cortex already logs message when it starts its shutdown procedure.

Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: That makes sense. I've removed the log message.

File: pkg/ingester/ingester_v2.go [hunk 12]
```diff
@@ -2245,3 +2282,11 @@ func (i *Ingester) getInstanceLimits() *InstanceLimits {
 
 	return l
 }
+
+func (i *Ingester) checkIfAllTSDBClosing() bool {
```
[the remark this answers is not in the document]
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Thank you for the suggestion. If it is using block store, it will check if the state is running. Otherwise it will check if it is running or stopping. If the ingester is stopping, it will return an error before it even gets to the v2 functions. 

If I misunderstood what you had in mind, please let me know and I will try to update it again.

[the remark this answers is not in the document]
Comment (bboreham) [reply pkg/ingester/ingester_v2.go]: I think Peter was suggesting the code look like:

```Go
func (i *Ingester) Query(ctx context.Context, req *client.QueryRequest) (*client.QueryResponse, error) {
	if i.cfg.BlocksStorageEnabled {
		return i.v2Query(ctx, req)
	}

	if err := i.checkRunningOrStopping(); err != nil {
		return nil, err
	}
...
```

```Go
func (i *Ingester) v2Query(ctx context.Context, req *client.QueryRequest) (*client.QueryResponse, error) {
	if err := i.checkRunning(); err != nil {
		return nil, err
	}
...
```

[the remark this answers is not in the document]
Comment (ilangofman) [reply pkg/ingester/ingester_v2.go]: Oh I see now. I have updated it. Thanks for the help!

File: pkg/ingester/ingester.go [hunk 13]
```diff
@@ -480,8 +480,22 @@ func (i *Ingester) checkRunningOrStopping() error {
...
+	}
+	return status.Error(codes.Unavailable, s.String())
+}
+
 // Push implements client.IngesterServer
 func (i *Ingester) Push(ctx context.Context, req *cortexpb.WriteRequest) (*cortexpb.WriteResponse, error) {
+	if i.cfg.BlocksStorageEnabled {
+		return i.v2Push(ctx, req)
+	}
+
```
Comment (bboreham) [inline pkg/ingester/ingester.go:498]: For `Push` it's ok to `CheckRunning()` in both cases, that will avoid duplicating the other checks.
There is a comment to say something else will catch it, but it doesn't matter.  We don't want to accept writes while stopping.

**Review by bboreham — COMMENTED** [review]
Looking good now, but I think we can get away without the duplication in `Push()`.

File: pkg/ingester/ingester.go (hunk 13 above)
Comment (ilangofman) [reply pkg/ingester/ingester.go]: Makes sense. I've updated it so it calls `checkRunning()` in both cases.

**Review by bboreham — APPROVED** [review]
Great! 🎉

**Review by treid314 — APPROVED** [review]
Looks great! Thank you!

**Review by pstibrany — APPROVED** [review]
LGTM, thank you!
