### PR TITLE
Templates in use are being removed by alertmanager cleanup logic

### LINKED ISSUE #4888: Templates in use are being removed by alertmanager cleanup logic
**Describe the bug**
With the implementation of Cortex with a sidecar, templates continuously get removed every 15seconds. Through a discussion on [slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1664472167491769?thread_ts=1664388746.634659&cid=CCYDASBLP), the issue is that the `local` storage implementation doesn't fill in the `Templates` slice. So the cleanup logic marks all the templates as stale. 

**To Reproduce**
1. Deploy Helm Chart https://github.com/cortexproject/cortex-helm-chart
2. Follow the instructions [here](https://github.com/cortexproject/cortex-helm-chart/blob/a9df59bbb852ef8d19a69351ef006cf40d5ac764/docs/guides/configure_rules_via_sidecar.markdown) to set up the sidecar configuration for alertmanager.
3. Add some templates into configmaps that the sidecar is watching. It will mount those configmaps onto the filesystem and then within 15 seconds they will be deleted. 

**Expected behavior**
The cleanup logic should not delete templates in use.

**Environment:**
 - Infrastructure: Kubernetes(AKS)
 - Deployment tool: Cortex Helm Chart https://github.com/cortexproject/cortex-helm-chart

**Additional Context**
Our Configuration:
```
alertmanager:
  external_url: /api/prom/alertmanager
  enable_api: true
  data_dir: /data/
  storage:
    type : local
    local:
      path: /data
```

### PR DESCRIPTION
**Pull request by alanprot**
**What this PR does**:
Populating the templates when using alertmanager local store.

**Which issue(s) this PR fixes**:
Fixes #4888

**Checklist**
- [X] Tests updated
- [NA] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/alertmanager/alertstore/local/store.go [hunk 1]
```diff
@@ -148,9 +149,40 @@ func (f *Store) reloadConfigs() (map[string]alertspb.AlertConfigDesc, error) {
 		// The file name must correspond to the user tenant ID
 		user := strings.TrimSuffix(info.Name(), ext)
 
+		// Load template files
+		userTemplateDir := filepath.Join(f.cfg.Path, user, templatesDir)
+		var templates []*alertspb.TemplateDesc
+
+		if _, e := os.Stat(userTemplateDir); e == nil {
```
Comment (alvinlin123) [inline pkg/alertmanager/alertstore/local/store.go:156]: We should probably check for `e` is not `os.ErrNotExist` then return error. I think `os.Stat(userTemplateDir)`may return other errors like "no permission" etc. which we should propagate up.  There is also [`os.IsExist()` helper function](https://pkg.go.dev/os#IsExist).

File: pkg/alertmanager/alertstore/local/store.go [hunk 2]
```diff
@@ -148,9 +149,40 @@ func (f *Store) reloadConfigs() (map[string]alertspb.AlertConfigDesc, error) {
...
+			err = filepath.Walk(filepath.Join(f.cfg.Path, user, templatesDir), func(path string, info os.FileInfo, err error) error {
```
Comment (alvinlin123) [inline pkg/alertmanager/alertstore/local/store.go:157]: we can replace `filepath.Join(f.cfg.Path, user, templatesDir)` with just `userTtemplateDir` variable right?

**Review by alvinlin123 — APPROVED** [review]
Thanks for fixing the issue @alanprot !
