### PR TITLE
Fix queriers shuffle-sharding blast radius containment

### LINKED ISSUE #3571: Shuffle-sharding of queriers may not work as intended
Shuffle sharding is intended to protect the system in a case, where user is sending queries to the system that can crash the querier.

However, if this happens and querier crashes, from query-frontend (or query-scheduler) point of view, querier is simply disconnected, and query-frontend will recompute the shard for user and simply use different queriers. If user sends more crashing queries at this moment, he can eventually crash all the queriers.

In practice, crashed queriers should restart quickly, which will make them part of users shard again, but the potential problem still exists.

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
As described in the #3571, when shuffle-sharding is enabled in the query-frontend/scheduler and a querier crashes, tenants are immediately resharded across the remaining queriers. This practically invalidates the assumption that shuffle-sharding can be used to contain the blast radius in case of a "poisoned query" on the read path: if a tenant repeatedly send a poisoned query over and over it has the ability to crash all queriers, and not just its shard.

In this PR I propose a solution to mitigate it, introducing a delay ("forget delay") between when a querier disconnects because of a crash and when a tenant's shard changes because of that.

To do it, a query-frontend/scheduler needs to know when a querier disconnects because of crash. I've introduced a "graceful shutdown notification" from the querier to query-frontend/scheduler: when a querier disconnects from the query-frontend/scheduler without sending such notification it means the querier crashed / abruptly terminated.

_I've done some manual testing and looks working as expected._

**Which issue(s) this PR fixes**:
Fixes #3571

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/scheduler/queue/user_queues.go [hunk 1]
```diff
@@ -3,10 +3,28 @@ package queue
...
 	"math/rand"
 	"sort"
+	"time"
 
 	"github.com/cortexproject/cortex/pkg/util"
 )
 
+const (
+	// How frequently to check for disconnected queriers that should be forgotten.
+	forgetCheckPeriod = 5 * time.Second
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:13]: Nit: Let's move this to queue.go, where it is used.

File: pkg/scheduler/queue/user_queues.go [hunk 2]
```diff
@@ -19,8 +37,13 @@ type queues struct {
 
 	maxUserQueueSize int
 
-	// Number of connections per querier.
-	querierConnections map[string]int
+	// How long to wait before removing a querier which has got disconnected
+	// but hasn't notified a graceful shutdown.
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:41]:
```suggestion
	// but hasn't notified about a graceful shutdown.
```

File: pkg/scheduler/queue/user_queues.go [hunk 3]
```diff
@@ -152,41 +176,103 @@ func (q *queues) getNextQueueForQuerier(lastUserIndex int, querier string) (chan
...
 
-func (q *queues) addQuerierConnection(querier string) {
-	conns := q.querierConnections[querier]
+func (q *queues) addQuerierConnection(querierID string) {
+	info := q.queriers[querierID]
+	if info != nil {
+		info.connections++
 
-	q.querierConnections[querier] = conns + 1
+		// Reset in case the querier re-connected while was in the forget waiting period.
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:184]:
```
		// Reset in case the querier re-connected while it was in the forget waiting period.
```

File: pkg/scheduler/queue/user_queues.go [hunk 4]
```diff
@@ -152,41 +176,103 @@ func (q *queues) getNextQueueForQuerier(lastUserIndex int, querier string) (chan
...
+	if info.connections > 0 {
+		return
+	}
 
-		ix := sort.SearchStrings(q.sortedQueriers, querier)
-		if ix >= len(q.sortedQueriers) || q.sortedQueriers[ix] != querier {
-			panic("incorrect state of sorted queriers")
-		}
+	// There no more active connections. If the forget timeout is configured then
+	// we can remove it only if a graceful shutdown has been notified.
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:212]:
```suggestion
	// we can remove it only if querier has announced a graceful shutdown.
```

File: pkg/scheduler/queue/user_queues.go [hunk 5]
```diff
@@ -152,41 +176,103 @@ func (q *queues) getNextQueueForQuerier(lastUserIndex int, querier string) (chan
...
+	if ix >= len(q.sortedQueriers) || q.sortedQueriers[ix] != querierID {
+		panic("incorrect state of sorted queriers")
 	}
+
+	q.sortedQueriers = append(q.sortedQueriers[:ix], q.sortedQueriers[ix+1:]...)
+
+	q.recomputeUserQueriers()
+}
+
+// notifyQuerierShutdown records a querier has notified a graceful shutdown.
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:237]:
```
// notifyQuerierShutdown records that a querier has sent nofication about a graceful shutdown.

File: pkg/scheduler/queue/user_queues.go [hunk 6]
```diff
@@ -19,8 +37,13 @@ type queues struct {
 
 	maxUserQueueSize int
 
-	// Number of connections per querier.
-	querierConnections map[string]int
+	// How long to wait before removing a querier which has got disconnected
+	// but hasn't notified a graceful shutdown.
+	forgetTimeout time.Duration
```
Comment (pstibrany) [inline pkg/scheduler/queue/user_queues.go:42]: Nit: I'd suggest to move `forgetTimeout` to `user_queues.go`, and pass only threshold to `forgetDisconnectQueriers`. `removeQuerierConnection` is also using this field, but only to know whether to keep disconnected querier or not. We could pass that information as a bool to `removeQuerierConnection`. This would simplify `queues` a bit, and allow for easier testing of `forgetDisconnectQueriers`. I would also suggest passing `time.Now()` as parameter to `removeQuerierConnection`, to avoid having dependency on current time in `queues`. WDYT?

File: pkg/scheduler/scheduler.go [hunk 7]
```diff
@@ -76,13 +80,14 @@ type connectedFrontend struct {
...
-
-	GRPCClientConfig grpcclient.Config `yaml:"grpc_client_config" doc:"description=This configures the gRPC client used to report errors back to the query-frontend."`
+	MaxOutstandingPerTenant int               `yaml:"max_outstanding_requests_per_tenant"`
+	QuerierForgetTimeout    time.Duration     `yaml:"querier_forget_timeout"`
+	GRPCClientConfig        grpcclient.Config `yaml:"grpc_client_config" doc:"description=This configures the gRPC client used to report errors back to the query-frontend."`
 }
 
 func (cfg *Config) RegisterFlags(f *flag.FlagSet) {
 	f.IntVar(&cfg.MaxOutstandingPerTenant, "query-scheduler.max-outstanding-requests-per-tenant", 100, "Maximum number of outstanding requests per tenant per query-scheduler. In-flight requests above this limit will fail with HTTP response status code 429.")
+	f.DurationVar(&cfg.QuerierForgetTimeout, "query-scheduler.querier-forget-timeout", 0, "When configured, if a querier disconnects without notifying a graceful shutdown, the query-scheduler keeps the querier in the tenant's shard until the forget timeout expires. This feature is useful to reduce the blast radius when shuffle-sharding is enabled.")
```
Comment (pstibrany) [inline pkg/scheduler/scheduler.go:90]:
```suggestion
	f.DurationVar(&cfg.QuerierForgetTimeout, "query-scheduler.querier-forget-timeout", 0, "If a querier disconnects without sending notification about graceful shutdown, the query-scheduler will keep the querier in the tenant's shard until the forget timeout expires. This feature is useful to reduce the blast radius when shuffle-sharding is enabled.")
```

File: pkg/querier/worker/frontend_processor.go [hunk 8]
```diff
@@ -42,6 +42,17 @@ type frontendProcessor struct {
 	log log.Logger
 }
 
+// notifyShutdown implements processor.
+func (fp *frontendProcessor) notifyShutdown(ctx context.Context, conn *grpc.ClientConn, address string) {
+	client := frontendv1pb.NewFrontendClient(conn)
+
+	req := &frontendv1pb.NotifyClientShutdownRequest{ClientID: fp.querierID}
+	if _, err := client.NotifyClientShutdown(ctx, req); err != nil {
+		// Since we're shutting down there's nothing we can do unless logging it.
```
Comment (pstibrany) [inline pkg/querier/worker/frontend_processor.go:51]:
```suggestion
		// Since we're shutting down there's nothing we can do except logging it.
```

**Review by pstibrany — COMMENTED** [review]
Good job, looking forward to see the tests. My comments are mostly some grammar suggestions... if you find these annoying, let me know and I will stop. (Some may also be wrong, so... :))

File: docs/configuration/config-file-reference.md [hunk 9]
```diff
@@ -589,6 +589,13 @@ query_scheduler:
   # CLI flag: -query-scheduler.max-outstanding-requests-per-tenant
   [max_outstanding_requests_per_tenant: <int> | default = 100]
 
+  # If a querier disconnects without sending notification about graceful
+  # shutdown, the query-scheduler will keep the querier in the tenant's shard
+  # until the forget timeout expires. This feature is useful to reduce the blast
+  # radius when shuffle-sharding is enabled.
+  # CLI flag: -query-scheduler.querier-forget-timeout
+  [querier_forget_timeout: <duration> | default = 0s]
```
Comment (ranton256) [inline docs/configuration/config-file-reference.md:597]: Do you think querier_forget_delay or querier_forget_wait would be a more straightforward name for this querier_forget_timeout seems to imply it's trying to do something until it gives up, as opposed to adding a delay to something it could do immediately.

**Review by ranton256 — COMMENTED** [review]
This makes sense to me functionally. I had a question about alternative naming of the configuration value being added, but otherwise LGTM.

File: docs/configuration/config-file-reference.md (hunk 9 above)
Comment (pracucci) [reply docs/configuration/config-file-reference.md]: Sure. I've renamed it to `querier_forget_delay`.

**Review by ranton256 — APPROVED** [review]
Thanks for doing this and the changes.

File: CHANGELOG.md [hunk 10]
```diff
@@ -91,6 +91,7 @@
   * `cortex_bucket_store_chunk_pool_returned_bytes_total`
 * [ENHANCEMENT] Alertmanager: load alertmanager configurations from object storage concurrently, and only load necessary configurations, speeding configuration synchronization process and executing fewer "GET object" operations to the storage when sharding is enabled. #3898
 * [ENHANCEMENT] Blocks storage: Ingester can now stream entire chunks instead of individual samples to the querier. At the moment this feature must be explicitly enabled either by using `-ingester.stream-chunks-when-using-blocks` flag or `ingester_stream_chunks_when_using_blocks` (boolean) field in runtime config file, but these configuration options are temporary and will be removed when feature is stable. #3889
+* [ENHANCEMENT] Query-frontend/scheduler: added querier forget delay (`-query-frontend.querier-forget-delay` and `-query-scheduler.querier-forget-delay`) to mitigate the blast radius in the event queriers crash because of a repeatedly sent "query of death" when shuffle-sharding is enabled. #3901
```
Comment (pstibrany) [inline CHANGELOG.md:94]: Cortex release 1.8.0 is now in progress. Could you please rebase master and move the CHANGELOG entry under the master / unreleased section?

File: pkg/scheduler/scheduler.go [hunk 11]
```diff
@@ -76,13 +80,14 @@ type connectedFrontend struct {
...
-
-	GRPCClientConfig grpcclient.Config `yaml:"grpc_client_config" doc:"description=This configures the gRPC client used to report errors back to the query-frontend."`
+	MaxOutstandingPerTenant int               `yaml:"max_outstanding_requests_per_tenant"`
+	QuerierForgetDelay      time.Duration     `yaml:"querier_forget_delay"`
+	GRPCClientConfig        grpcclient.Config `yaml:"grpc_client_config" doc:"description=This configures the gRPC client used to report errors back to the query-frontend."`
 }
 
 func (cfg *Config) RegisterFlags(f *flag.FlagSet) {
 	f.IntVar(&cfg.MaxOutstandingPerTenant, "query-scheduler.max-outstanding-requests-per-tenant", 100, "Maximum number of outstanding requests per tenant per query-scheduler. In-flight requests above this limit will fail with HTTP response status code 429.")
+	f.DurationVar(&cfg.QuerierForgetDelay, "query-scheduler.querier-forget-delay", 0, "If a querier disconnects without sending notification about graceful shutdown, the query-scheduler will keep the querier in the tenant's shard until the forget delay is passed. This feature is useful to reduce the blast radius when shuffle-sharding is enabled.")
```
Comment (pstibrany) [inline pkg/scheduler/scheduler.go:90]:
```suggestion
	f.DurationVar(&cfg.QuerierForgetDelay, "query-scheduler.querier-forget-delay", 0, "If a querier disconnects without sending notification about graceful shutdown, the query-scheduler will keep the querier in the tenant's shard until the forget delay has passed. This feature is useful to reduce the blast radius when shuffle-sharding is enabled.")
```

**Review by pstibrany — APPROVED** [review]
LGTM, great work.
