### PR TITLE
Fix chunks flushing bugs

### LINKED ISSUE #2743: Panic while flushing chunks
This panic happened while calling `/flush` endpoint on ingester in internal cluster. Ingester was running `grafana/cortex-cortex:r92-a0674c0c2` (https://github.com/grafana/cortex/commits/a0674c0c2f528f8aa5297768604e17ca7ebb047f)

```
level=info ts=2020-06-18T08:23:49.848675718Z caller=flush.go:42 msg="starting to flush all the chunks"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x279a9b7]

goroutine 1288 [running]:
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushChunks(0xc0006e8800, 0x3ee0260, 0xc002814d20, 0xc000e0c6b0, 0x3, 0x87ff6a90a1aa9836, 0xc0191ae160, 0xb, 0xb, 0xc1c44a5180, ...)
	/go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:344 +0x637
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushUserSeries(0xc0006e8800, 0x20, 0xc000e0c6b0, 0x3, 0x87ff6a90a1aa9836, 0x1, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:291 +0x843
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).flushLoop(0xc0006e8800, 0x20)
	/go/src/github.com/cortexproject/cortex/pkg/ingester/flush.go:205 +0x10a
created by github.com/cortexproject/cortex/pkg/ingester.(*Ingester).startFlushLoops
	/go/src/github.com/cortexproject/cortex/pkg/ingester/ingester.go:256 +0x68
```

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: There were few bugs in chunks flushing code that this PR tries to fix:
- https://github.com/cortexproject/cortex/issues/2743
- Samples added during immediate flush were discarded
- If removal of old chunks happens during flush, incorrect chunks are marked as flushed (this can now happen since this PR keeps immediate-flushed chunks in memory)

In addition to that, this PR also:
-  introduces new metric `cortex_ingester_flush_series_in_progress` (needed to fix integration test)
- updates log messages related to flushing chunks (Fixes https://github.com/cortexproject/cortex/issues/2744)

**Which issue(s) this PR fixes**:
Fixes #2743 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

(Notify @gouthamve @bboreham as chunk experts)

### CODE REVIEW

**Comment by bboreham** [comment]
I wonder if it would be possible to fix #2287 at the same time?
Maybe if we move the point that the metric is computed to after we know what happened to the chunk, we can get away without adding a new metric?

File: pkg/ingester/flush.go [hunk 1]
```diff
@@ -238,8 +247,11 @@ func (i *Ingester) flushUserSeries(flushQueueIndex int, userID string, fp model.
 		return nil
 	}
 
-	// shouldFlushSeries() has told us we have at least one chunk
-	chunks := series.chunkDescs
+	// shouldFlushSeries() has told us we have at least one chunk.
+	// Make a copy of chunks descriptors slice, to avoid possible issues related to removing (and niling) elements from chunkDesc.
+	// This can happen if first chunk is already flushed -- removeFlushedChunks may set such chunk to nil.
+	// Since elements in the slice are pointers, we can still safely update chunk descriptors after the copy.
+	chunks := append([]*desc(nil), series.chunkDescs...)
```
Comment (pracucci) [inline pkg/ingester/flush.go:254]: A `make([]*desc, 0, len(series.chunkDescs)` + `copy()`  may me more efficient?

File: pkg/ingester/flush.go [hunk 2]
```diff
@@ -275,6 +287,11 @@ func (i *Ingester) flushUserSeries(flushQueueIndex int, userID string, fp model.
 
 	userState.fpLocker.Unlock(fp)
 
+	// No need to flush these chunks again.
+	for len(chunks) > 0 && chunks[0].flushed {
```
Comment (pracucci) [inline pkg/ingester/flush.go:291]: Question: is it always guaranteed that chunks are flushed in order? May end up in a situation where X is not flushed but X+1 is?

Comment (bboreham) [reply pkg/ingester/flush.go:291]: Not in the current code; `Put()` is always implemented by iterated calls to `PutOne()`, and any error considers the whole set to have failed.
But there's nothing guaranteeing this.  Possibly we should remove `Put()` to avoid confusion.

File: CHANGELOG.md [hunk 3]
```diff
@@ -57,6 +57,7 @@
 * [CHANGE] Removed `-store.fullsize-chunks` option which was undocumented and unused (it broke ingester hand-overs). #2656
 * [CHANGE] Query with no metric name that has previously resulted in HTTP status code 500 now returns status code 422 instead. #2571
 * [CHANGE] Experimental Delete Series: Change target flag for purger from `data-purger` to `purger`. #2777
+* [CHANGE] Ingester: Chunks flushed via /flush stay in memory until retention period is reached. This affects `cortex_ingester_memory_chunks` metric. #2778
```
[the remark this answers is not in the document]
Comment (pstibrany) [reply CHANGELOG.md:60]: I can do that, but there are already changes merged on master, that are not in 1.2-rc0, so cleanup needs to happen when merging release branch to master. (Personally I think we should do the first merge as soon as 1.2-rc0 is tagged, to avoid this problem growing. It is a pain to clean up.)

File: pkg/ingester/flush.go (hunk 1 above)
Comment (pstibrany) [reply pkg/ingester/flush.go:254]: I don't think sightly complicating code to be more efficient here will get us much... there is typically only one or two chunks in the slice. And I assume (without checking) that compiler is smart enough to optimize for this case anyway.

**Comment by pstibrany** [comment]
> I wonder if it would be possible to fix #2287 at the same time?
> Maybe if we move the point that the metric is computed to after we know what happened to the chunk, we can get away without adding a new metric?

I will take a look at it before merging.

**Comment by pstibrany** [comment]
> > I wonder if it would be possible to fix #2287 at the same time?
> > Maybe if we move the point that the metric is computed to after we know what happened to the chunk, we can get away without adding a new metric?
> 
> I will take a look at it before merging.

I've sent separate PR #2802 for issue #2287.

**Comment by pstibrany** [comment]
I will merge this tomorrow, if there are no objections.
