### PR TITLE
[Querier] Fix Flaky Response Compression Test

### LINKED ISSUE #6242: Flaky test case: TestCompressedResponse
https://github.com/cortexproject/cortex/actions/runs/11045392221/job/30684835319?pr=6237

It might be relevant to https://github.com/cortexproject/cortex/pull/5527

### PR DESCRIPTION
**Pull request by afhassan**
**Which issue(s) this PR fixes**:
Fixes #6242

### CODE REVIEW

File: pkg/querier/tripperware/queryrange/results_cache_test.go [hunk 1]
```diff
@@ -149,6 +150,12 @@ var (
 	}
 )
 
+func sortPrometheusResponseHeader(headers []*tripperware.PrometheusResponseHeader) {
+	sort.Slice(headers, func(i, j int) bool {
+		return headers[i].Name < headers[j].Name
+	})
+}
```
Comment (yeya24) [inline pkg/querier/tripperware/queryrange/results_cache_test.go:157]: Can we move this to `query_range_test.go`?

**Review by yeya24 — APPROVED** [review]
Thanks
