### PR TITLE
Remove check to delete visit marker only if partition group deleted

### LINKED ISSUE #7208: [Compactor] Visit marker left dangling after partition group is deleted
**Describe the bug**
If the compactor is shut down while running the cleanup for a completed partition group, it may leave visit markers dangling in long-term storage. This is because a new flag was introduced in https://github.com/cortexproject/cortex/pull/7130 where the visit markers for a completed group are only deleted if the partition group info file was deleted in the same iteration.

**To Reproduce**
1. Start Cortex in a distributed environment
2. Wait for a compactor to start the cleanup of a completed partition group and force kill the compactor after it deletes the partition group info file but before it deletes the related visit markers.

**Expected behavior**
Visit markers for that partition group should be deleted on a new cleaner cycle.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: Helm

**Additional Context**

### PR DESCRIPTION
**Pull request by anna-tran**
**What this PR does**:

Removes the additional check that the partition group info file needs to be deleted in order to clean up related visit markers for a complete partition. This check was incorrectly added in https://github.com/cortexproject/cortex/pull/7130/files; the visit markers for a completed plan should always be deleted otherwise they will be left dangling if the partition info file is removed but the rest of the cleaning process is interrupted.

**Which issue(s) this PR fixes**:
Fixes #7208

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/compactor/blocks_cleaner.go [hunk 1]
```diff
@@ -812,12 +811,11 @@ func (c *BlocksCleaner) cleanPartitionedGroupInfo(ctx context.Context, userBucke
 					level.Warn(partitionedGroupLogger).Log("msg", "failed to delete partitioned group info", "partitioned_group_file", partitionedGroupInfoFile, "err", err)
 				} else {
 					level.Info(partitionedGroupLogger).Log("msg", "deleted partitioned group info", "partitioned_group_file", partitionedGroupInfoFile)
-					isPartitionGroupInfoDeleted = true
 				}
 			}
 		}
 
-		if isPartitionGroupInfoDeleted && (extraInfo.status.CanDelete || extraInfo.status.DeleteVisitMarker) {
+		if extraInfo.status.CanDelete || extraInfo.status.DeleteVisitMarker {
```
Comment (alexqyle) [inline pkg/compactor/blocks_cleaner.go]: Would this cause visit marker got deleted when partitioned group info not deleted?

Comment (anna-tran) [reply pkg/compactor/blocks_cleaner.go]: Yes, discussed offline with @danielblando and @alexqyle , I'll change this logic so that

- If the plan is complete, delete all visit markers. 
- If not complete but only a few visit markers are invalid then delete those.

File: CHANGELOG.md [hunk 2]
```diff
@@ -42,6 +42,7 @@
 * [BUGFIX] Query Frontend: Add Native Histogram extraction logic in results cache #7167
 * [BUGFIX] Alertmanager: Fix alertmanager reloading bug that removes user template files #7196
 * [BUGFIX] Query Scheduler: If max_outstanding_requests_per_tenant value is updated to lesser value than the current number of requests in the queue, the excess requests (newest ones) will be dropped to prevent deadlocks. #7188
+* [BUGFIX] Compactor: Always clean up visit marker when partition group should be deleted. #7208
```
Comment (yeya24) [inline CHANGELOG.md]: We don't need a new changelog entry for this. Since the previous PR is still not released, you can add this PR number to the previous changelog entry.

Btw the correct PR number should be #7130 not #7129

```
[ENHANCEMENT] Compactor: Avoid double compaction by cleaning partition files in 2 cycles. #7129
```

Comment (anna-tran) [reply CHANGELOG.md]: Thanks, I've updated the Changelog
