### PR TITLE
Join memberlist on starting with no retry

### LINKED ISSUE #4798: Follow up of #4068: Fixed race condition causing queries to fail right after querier startup with the "empty ring" error + Memberlist
When using Memberlist, we are starting the ring service before the ring information is propagated causing query failing with "empty ring" right after the querier has started.

The ring services tries to make sure the ring data is populated before starting the other modules (see https://github.com/cortexproject/cortex/pull/4068) but this is not working well with memberlist as it's service is only joining the cluster when is already running:

https://github.com/cortexproject/cortex/blob/7bc21e5dc579b1aed4d3e88b2d832fcd8019c737/pkg/ring/kv/memberlist/memberlist_client.go#L445-L450

The comment about `is good enough for usage from Client (which checks for Running state), even before it connects to the cluster. ` seems to not hold true as the service states flips to running before calling the running function:

https://github.com/cortexproject/cortex/blob/7bc21e5dc579b1aed4d3e88b2d832fcd8019c737/pkg/util/services/basic_service.go#L182-L191

When this happens we can also see this log line (which should not happen):

https://github.com/cortexproject/cortex/blob/7bc21e5dc579b1aed4d3e88b2d832fcd8019c737/pkg/ring/ring.go#L269

**To Reproduce**
Use memberlist and restart queriers.

**Expected behavior**
Queriers should start to process request only after the ring information is propagated.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Storage Engine**
- [ ] Blocks
- [ ] Chunks

**Additional Context**

### PR DESCRIPTION
**Pull request by danielblando**
Signed-off-by: Daniel Blando <ddeluigg@amazon.com>

**What this PR does**:
Add logic to join memberlist while starting also avoiding 'empty ring'. On startup we dont have retry or failure to not block start of service. We leave these responsibilities to running as it was before.

**Which issue(s) this PR fixes**:
Fixes #4798

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ring/kv/memberlist/memberlist_client.go [hunk 1]
```diff
@@ -556,6 +561,18 @@ func (m *KV) joinMembersOnStartup(ctx context.Context, members []string) error {
 	return lastErr
 }
 
+func (m *KV) joinMembersOnStarting(members []string) error {
+	level.Error(m.logger).Log("msg", "joinMembersOnStartup")
```
Comment (alanprot) [inline pkg/ring/kv/memberlist/memberlist_client.go:565]: Seems this line was forgotten?

File: pkg/ring/kv/memberlist/memberlist_client.go [hunk 2]
```diff
@@ -517,12 +526,8 @@ func (m *KV) JoinMembers(members []string) (int, error) {
...
 }
 
-func (m *KV) joinMembersOnStartup(ctx context.Context, members []string) error {
-	reached, err := m.memberlist.Join(members)
-	if err == nil {
-		level.Info(m.logger).Log("msg", "joined memberlist cluster", "reached_nodes", reached)
-		return nil
-	}
+func (m *KV) joinMembersOnRunning(ctx context.Context, members []string) error {
+	err := m.joinMembersOnStarting(members)
```
Comment (alanprot) [inline pkg/ring/kv/memberlist/memberlist_client.go:530]: nit: i would just leave the body of this function unchanged.

**Review by alanprot — APPROVED** [review]

**Review by alvinlin123 — APPROVED** [review]
