### PR TITLE
Fix memory leak caused by object pool and zero copy

### LINKED ISSUE #2665: About the memory of ingester
Hello, I have a serious memory problem when using Cortex. Cortex is always killed by OOM after running for 30 minutes.

image
After I stopped remote write for more than `10 hours`, the memory of ingester did not drop, and it still holds 98G of memory. At this time, I can see through /metrics that cortex has consumed all series  What is the memory used for? 
I only see 1G of memory on the heap through pprof:
image

At the same time, I triggered ingester to execute `runtime.GC()`  and `debug.FreeOSMemory()` through an external api, but it didn't work.

Do you have any ideas about it?

#### 1. metrics of ingester
```
# HELP alertmanager_dispatcher_aggregation_groups Number of active aggregation groups
# TYPE alertmanager_dispatcher_aggregation_groups gauge
alertmanager_dispatcher_aggregation_groups 0
# HELP alertmanager_dispatcher_alert_processing_duration_seconds Summary of latencies for the processing of alerts.
# TYPE alertmanager_dispatcher_alert_processing_duration_seconds summary
alertmanager_dispatcher_alert_processing_duration_seconds_sum 0
alertmanager_dispatcher_alert_processing_duration_seconds_count 0
# HELP cortex_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which cortex was built.
# TYPE cortex_build_info gauge
cortex_build_info{branch="",goversion="go1.13.8",revision="",version=""} 1
# HELP cortex_cache_corrupt_chunks_total Total count of corrupt chunks found in cache.
# TYPE cortex_cache_corrupt_chunks_total counter
cortex_cache_corrupt_chunks_total 0
# HELP cortex_cassandra_request_duration_seconds Time spent doing Cassandra requests.
# TYPE cortex_cassandra_request_duration_seconds histogram
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="0.001"} 2.0482032e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="0.004"} 2.0963156e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="0.016"} 2.11180684e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="0.064"} 2.11692043e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="0.256"} 2.11720123e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="1.024"} 2.1172034e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="4.096"} 2.1172034e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="16.384"} 2.1172034e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="65.536"} 2.1172034e+08
cortex_cassandra_request_duration_seconds_bucket{operation="INSERT",status_code="200",le="+Inf"} 2.1172034e+08
cortex_cassandra_request_duration_seconds_sum{operation="INSERT",status_code="200"} 147647.05328182015
cortex_cassandra_request_duration_seconds_count{operation="INSERT",status_code="200"} 2.1172034e+08
# HELP cortex_chunk_store_chunks_per_query Distribution of #chunks per query.
# TYPE cortex_chunk_store_chunks_per_query histogram
cortex_chunk_store_chunks_per_query_bucket{le="10"} 0
cortex_chunk_store_chunks_per_query_bucket{le="80"} 0
cortex_chunk_store_chunks_per_query_bucket{le="640"} 0
cortex_chunk_store_chunks_per_query_bucket{le="5120"} 0
cortex_chunk_store_chunks_per_query_bucket{le="40960"} 0
cortex_chunk_store_chunks_per_query_bucket{le="327680"} 0
cortex_chunk_store_chunks_per_query_bucket{le="2.62144e+06"} 0
cortex_chunk_store_chunks_per_query_bucket{le="+Inf"} 0
cortex_chunk_store_chunks_per_query_sum 0
cortex_chunk_store_chunks_per_query_count 0
# HELP cortex_chunk_store_deduped_chunks_total Count of chunks which were not stored because they have already been stored by another replica.
# TYPE cortex_chunk_store_deduped_chunks_total counter
cortex_chunk_store_deduped_chunks_total 0
# HELP cortex_chunk_store_index_entries_per_chunk Number of entries written to storage per chunk.
# TYPE cortex_chunk_store_index_entries_per_chunk histogram
cortex_chunk_store_index_entries_per_chunk_bucket{le="1"} 0
cortex_chunk_store_index_entries_per_chunk_bucket{le="2"} 0
cortex_chunk_store_index_entries_per_chunk_bucket{le="4"} 0
cortex_chunk_store_index_entries_per_chunk_bucket{le="8"} 5.024061e+06
cortex_chunk_store_index_entries_per_chunk_bucket{le="16"} 2.066086e+07
cortex_chunk_store_index_entries_per_chunk_bucket{le="+Inf"} 2.0661069e+07
cortex_chunk_store_index_entries_per_chunk_sum 1.91059271e+08
cortex_chunk_store_index_entries_per_chunk_count 2.0661069e+07
# HELP cortex_chunk_store_index_lookups_per_query Distribution of #index lookups per query.
# TYPE cortex_chunk_store_index_lookups_per_query histogram
cortex_chunk_store_index_lookups_per_query_bucket{le="0.005"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.01"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.025"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.05"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.1"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.25"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="0.5"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="1"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="2.5"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="5"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="10"} 0
cortex_chunk_store_index_lookups_per_query_bucket{le="+Inf"} 0
cortex_chunk_store_index_lookups_per_query_sum 0
cortex_chunk_store_index_lookups_per_query_count 0
# HELP cortex_chunk_store_series_post_intersection_per_query Distribution of #series (post intersection) per query.
# TYPE cortex_chunk_store_series_post_intersection_per_query histogram
cortex_chunk_store_series_post_intersection_per_query_bucket{le="10"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="80"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="640"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="5120"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="40960"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="327680"} 0
cortex_chunk_store_series_post_intersection_per_query_bucket{le="+Inf"} 0
cortex_chunk_store_series_post_intersection_per_query_sum 0
cortex_chunk_store_series_post_intersection_per_query_count 0
# HELP cortex_chunk_store_series_pre_intersection_per_query Distribution of #series (pre intersection) per query.
# TYPE cortex_chunk_store_series_pre_intersection_per_query histogram
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="10"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="80"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="640"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="5120"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="40960"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="327680"} 0
cortex_chunk_store_series_pre_intersection_per_query_bucket{le="+Inf"} 0
cortex_chunk_store_series_pre_intersection_per_query_sum 0
cortex_chunk_store_series_pre_intersection_per_query_count 0
# HELP cortex_chunk_store_stored_chunk_bytes_total Total bytes stored in chunks per user.
# TYPE cortex_chunk_store_stored_chunk_bytes_total counter
cortex_chunk_store_stored_chunk_bytes_total{user="fake"} 3.490694713e+09
# HELP cortex_chunk_store_stored_chunks_total Total stored chunks per user.
# TYPE cortex_chunk_store_stored_chunks_total counter
cortex_chunk_store_stored_chunks_total{user="fake"} 2.0661069e+07
# HELP cortex_consul_request_duration_seconds Time spent on consul requests.
# TYPE cortex_consul_request_duration_seconds histogram
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.005"} 15861
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.01"} 15992
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.025"} 16029
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.05"} 16038
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.1"} 16057
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.25"} 16070
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.5"} 16072
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="1"} 16074
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="2.5"} 16074
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="5"} 16075
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="10"} 16075
cortex_consul_request_duration_seconds_bucket{operation="CAS",status_code="200",le="+Inf"} 16076
cortex_consul_request_duration_seconds_sum{operation="CAS",status_code="200"} 78.17985602499975
cortex_consul_request_duration_seconds_count{operation="CAS",status_code="200"} 16076
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.005"} 13340
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.01"} 14927
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.025"} 15193
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.05"} 15214
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.1"} 15237
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.25"} 15247
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="0.5"} 15249
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="1"} 15252
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="2.5"} 15253
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="5"} 15253
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="10"} 15254
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="200",le="+Inf"} 15255
cortex_consul_request_duration_seconds_sum{operation="CAS loop",status_code="200"} 145.78952918399938
cortex_consul_request_duration_seconds_count{operation="CAS loop",status_code="200"} 15255
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.005"} 0
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.01"} 0
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.025"} 0
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.05"} 5
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.1"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.25"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="0.5"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="1"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="2.5"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="5"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="10"} 7
cortex_consul_request_duration_seconds_bucket{operation="CAS loop",status_code="500",le="+Inf"} 7
cortex_consul_request_duration_seconds_sum{operation="CAS loop",status_code="500"} 0.324946323
cortex_consul_request_duration_seconds_count{operation="CAS loop",status_code="500"} 7
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.005"} 16023
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.01"} 16044
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.025"} 16061
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.05"} 16067
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.1"} 16069
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.25"} 16072
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="0.5"} 16072
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="1"} 16073
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="2.5"} 16073
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="5"} 16074
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="10"} 16075
cortex_consul_request_duration_seconds_bucket{operation="Get",status_code="200",le="+Inf"} 16077
cortex_consul_request_duration_seconds_sum{operation="Get",status_code="200"} 66.0013436970004
cortex_consul_request_duration_seconds_count{operation="Get",status_code="200"} 16077
# HELP cortex_deprecated_flags_inuse_total The number of deprecated flags currently set.
# TYPE cortex_deprecated_flags_inuse_total counter
cortex_deprecated_flags_inuse_total 0
# HELP cortex_discarded_samples_total The total number of samples that were discarded.
# TYPE cortex_discarded_samples_total counter
cortex_discarded_samples_total{reason="duplicate-sample",user="fake"} 8.3592e+07
# HELP cortex_distributor_ingester_clients The current number of ingester clients.
# TYPE cortex_distributor_ingester_clients gauge
cortex_distributor_ingester_clients 0
# HELP cortex_distributor_replication_factor The configured replication factor.
# TYPE cortex_distributor_replication_factor gauge
cortex_distributor_replication_factor 0
# HELP cortex_dynamo_query_pages_count Number of pages per query.
# TYPE cortex_dynamo_query_pages_count histogram
cortex_dynamo_query_pages_count_bucket{le="1"} 0
cortex_dynamo_query_pages_count_bucket{le="4"} 0
cortex_dynamo_query_pages_count_bucket{le="16"} 0
cortex_dynamo_query_pages_count_bucket{le="64"} 0
cortex_dynamo_query_pages_count_bucket{le="256"} 0
cortex_dynamo_query_pages_count_bucket{le="1024"} 0
cortex_dynamo_query_pages_count_bucket{le="+Inf"} 0
cortex_dynamo_query_pages_count_sum 0
cortex_dynamo_query_pages_count_count 0
# HELP cortex_experimental_features_in_use_total The number of experimental features in use.
# TYPE cortex_experimental_features_in_use_total counter
cortex_experimental_features_in_use_total 2
# HELP cortex_ha_tracker_elected_replica_change_propagation_time_seconds The time it for the distributor to update the replica change.
# TYPE cortex_ha_tracker_elected_replica_change_propagation_time_seconds histogram
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.005"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.01"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.025"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.05"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.1"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.25"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="0.5"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="1"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="2.5"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="5"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="10"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_bucket{le="+Inf"} 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_sum 0
cortex_ha_tracker_elected_replica_change_propagation_time_seconds_count 0
# HELP cortex_ingester_chunk_age_seconds Distribution of chunk ages (when stored).
# TYPE cortex_ingester_chunk_age_seconds histogram
cortex_ingester_chunk_age_seconds_bucket{le="60"} 0
cortex_ingester_chunk_age_seconds_bucket{le="300"} 0
cortex_ingester_chunk_age_seconds_bucket{le="600"} 0
cortex_ingester_chunk_age_seconds_bucket{le="1800"} 0
cortex_ingester_chunk_age_seconds_bucket{le="3600"} 0
cortex_ingester_chunk_age_seconds_bucket{le="7200"} 3.409966e+06
cortex_ingester_chunk_age_seconds_bucket{le="14400"} 2.0661069e+07
cortex_ingester_chunk_age_seconds_bucket{le="36000"} 2.0661069e+07
cortex_ingester_chunk_age_seconds_bucket{le="43200"} 2.0661069e+07
cortex_ingester_chunk_age_seconds_bucket{le="57600"} 2.0661069e+07
cortex_ingester_chunk_age_seconds_bucket{le="+Inf"} 2.0661069e+07
cortex_ingester_chunk_age_seconds_sum 2.0203848270287128e+11
cortex_ingester_chunk_age_seconds_count 2.0661069e+07
# HELP cortex_ingester_chunk_length Distribution of stored chunk lengths (when stored).
# TYPE cortex_ingester_chunk_length histogram
cortex_ingester_chunk_length_bucket{le="5"} 884008
cortex_ingester_chunk_length_bucket{le="10"} 1.565347e+06
cortex_ingester_chunk_length_bucket{le="20"} 2.709061e+06
cortex_ingester_chunk_length_bucket{le="40"} 5.264011e+06
cortex_ingester_chunk_length_bucket{le="80"} 7.671074e+06
cortex_ingester_chunk_length_bucket{le="160"} 1.2431472e+07
cortex_ingester_chunk_length_bucket{le="320"} 2.0661069e+07
cortex_ingester_chunk_length_bucket{le="640"} 2.0661069e+07
cortex_ingester_chunk_length_bucket{le="1280"} 2.0661069e+07
cortex_ingester_chunk_length_bucket{le="2560"} 2.0661069e+07
cortex_ingester_chunk_length_bucket{le="5120"} 2.0661069e+07
cortex_ingester_chunk_length_bucket{le="+Inf"} 2.0661069e+07
cortex_ingester_chunk_length_sum 2.604505174e+09
cortex_ingester_chunk_length_count 2.0661069e+07
# HELP cortex_ingester_chunk_size_bytes Distribution of stored chunk sizes (when stored).
# TYPE cortex_ingester_chunk_size_bytes histogram
cortex_ingester_chunk_size_bytes_bucket{le="500"} 1.9098363e+07
cortex_ingester_chunk_size_bytes_bucket{le="1000"} 2.0017709e+07
cortex_ingester_chunk_size_bytes_bucket{le="2000"} 2.0660539e+07
cortex_ingester_chunk_size_bytes_bucket{le="4000"} 2.0661069e+07
cortex_ingester_chunk_size_bytes_bucket{le="8000"} 2.0661069e+07
cortex_ingester_chunk_size_bytes_bucket{le="16000"} 2.0661069e+07
cortex_ingester_chunk_size_bytes_bucket{le="32000"} 2.0661069e+07
cortex_ingester_chunk_size_bytes_bucket{le="+Inf"} 2.0661069e+07
cortex_ingester_chunk_size_bytes_sum 3.490694713e+09
cortex_ingester_chunk_size_bytes_count 2.0661069e+07
# HELP cortex_ingester_chunk_utilization Distribution of stored chunk utilization (when stored).
# TYPE cortex_ingester_chunk_utilization histogram
cortex_ingester_chunk_utilization_bucket{le="0"} 0
cortex_ingester_chunk_utilization_bucket{le="0.2"} 0
cortex_ingester_chunk_utilization_bucket{le="0.4"} 0
cortex_ingester_chunk_utilization_bucket{le="0.6000000000000001"} 0
cortex_ingester_chunk_utilization_bucket{le="0.8"} 0
cortex_ingester_chunk_utilization_bucket{le="1"} 2.0661069e+07
cortex_ingester_chunk_utilization_bucket{le="+Inf"} 2.0661069e+07
cortex_ingester_chunk_utilization_sum 2.0661069e+07
cortex_ingester_chunk_utilization_count 2.0661069e+07
# HELP cortex_ingester_chunks_created_total The total number of chunks the ingester has created.
# TYPE cortex_ingester_chunks_created_total counter
cortex_ingester_chunks_created_total 2.0661069e+07
# HELP cortex_ingester_dropped_chunks_total Total number of chunks dropped from flushing because they have too few samples.
# TYPE cortex_ingester_dropped_chunks_total counter
cortex_ingester_dropped_chunks_total 0
# HELP cortex_ingester_flush_queue_length The total number of series pending in the flush queue.
# TYPE cortex_ingester_flush_queue_length gauge
cortex_ingester_flush_queue_length 0
# HELP cortex_ingester_flush_reasons Total number of series scheduled for flushing, with reasons.
# TYPE cortex_ingester_flush_reasons counter
cortex_ingester_flush_reasons{reason="Idle"} 1.2179127e+07
cortex_ingester_flush_reasons{reason="MultipleChunksInSeries"} 253
cortex_ingester_flush_reasons{reason="Spread"} 7.896349e+06
cortex_ingester_flush_reasons{reason="Stale"} 570573
# HELP cortex_ingester_ingested_metadata_failures_total The total number of metadata that errored on ingestion.
# TYPE cortex_ingester_ingested_metadata_failures_total counter
cortex_ingester_ingested_metadata_failures_total 0
# HELP cortex_ingester_ingested_metadata_total The total number of metadata ingested.
# TYPE cortex_ingester_ingested_metadata_total counter
cortex_ingester_ingested_metadata_total 0
# HELP cortex_ingester_ingested_samples_failures_total The total number of samples that errored on ingestion.
# TYPE cortex_ingester_ingested_samples_failures_total counter
cortex_ingester_ingested_samples_failures_total 0
# HELP cortex_ingester_ingested_samples_total The total number of samples ingested.
# TYPE cortex_ingester_ingested_samples_total counter
cortex_ingester_ingested_samples_total 2.604505174e+09
# HELP cortex_ingester_memory_chunks The total number of chunks in memory.
# TYPE cortex_ingester_memory_chunks gauge
cortex_ingester_memory_chunks 0
# HELP cortex_ingester_memory_metadata The current number of metadata in memory.
# TYPE cortex_ingester_memory_metadata gauge
cortex_ingester_memory_metadata 0
# HELP cortex_ingester_memory_series The current number of series in memory.
# TYPE cortex_ingester_memory_series gauge
cortex_ingester_memory_series 0
# HELP cortex_ingester_memory_series_created_total The total number of series that were created per user.
# TYPE cortex_ingester_memory_series_created_total counter
cortex_ingester_memory_series_created_total{user="fake"} 1.2752133e+07
# HELP cortex_ingester_memory_series_removed_total The total number of series that were removed per user.
# TYPE cortex_ingester_memory_series_removed_total counter
cortex_ingester_memory_series_removed_total{user="fake"} 1.2752133e+07
# HELP cortex_ingester_memory_users The current number of users in memory.
# TYPE cortex_ingester_memory_users gauge
cortex_ingester_memory_users 1
# HELP cortex_ingester_queried_chunks The total number of chunks returned from queries.
# TYPE cortex_ingester_queried_chunks histogram
cortex_ingester_queried_chunks_bucket{le="10"} 0
cortex_ingester_queried_chunks_bucket{le="80"} 0
cortex_ingester_queried_chunks_bucket{le="640"} 0
cortex_ingester_queried_chunks_bucket{le="5120"} 0
cortex_ingester_queried_chunks_bucket{le="40960"} 0
cortex_ingester_queried_chunks_bucket{le="327680"} 0
cortex_ingester_queried_chunks_bucket{le="2.62144e+06"} 0
cortex_ingester_queried_chunks_bucket{le="+Inf"} 0
cortex_ingester_queried_chunks_sum 0
cortex_ingester_queried_chunks_count 0
# HELP cortex_ingester_queried_samples The total number of samples returned from queries.
# TYPE cortex_ingester_queried_samples histogram
cortex_ingester_queried_samples_bucket{le="10"} 0
cortex_ingester_queried_samples_bucket{le="80"} 0
cortex_ingester_queried_samples_bucket{le="640"} 0
cortex_ingester_queried_samples_bucket{le="5120"} 0
cortex_ingester_queried_samples_bucket{le="40960"} 0
cortex_ingester_queried_samples_bucket{le="327680"} 0
cortex_ingester_queried_samples_bucket{le="2.62144e+06"} 0
cortex_ingester_queried_samples_bucket{le="2.097152e+07"} 0
cortex_ingester_queried_samples_bucket{le="+Inf"} 0
cortex_ingester_queried_samples_sum 0
cortex_ingester_queried_samples_count 0
# HELP cortex_ingester_queried_series The total number of series returned from queries.
# TYPE cortex_ingester_queried_series histogram
cortex_ingester_queried_series_bucket{le="10"} 0
cortex_ingester_queried_series_bucket{le="80"} 0
cortex_ingester_queried_series_bucket{le="640"} 0
cortex_ingester_queried_series_bucket{le="5120"} 0
cortex_ingester_queried_series_bucket{le="40960"} 0
cortex_ingester_queried_series_bucket{le="327680"} 0
cortex_ingester_queried_series_bucket{le="+Inf"} 0
cortex_ingester_queried_series_sum 0
cortex_ingester_queried_series_count 0
# HELP cortex_ingester_queries_total The total number of queries the ingester has handled.
# TYPE cortex_ingester_queries_total counter
cortex_ingester_queries_total 0
# HELP cortex_ingester_received_bytes_total The total number of bytes received by this ingester whilst joining
# TYPE cortex_ingester_received_bytes_total counter
cortex_ingester_received_bytes_total 0
# HELP cortex_ingester_received_chunks The total number of chunks received by this ingester whilst joining
# TYPE cortex_ingester_received_chunks counter
cortex_ingester_received_chunks 0
# HELP cortex_ingester_received_files The total number of files received by this ingester whilst joining
# TYPE cortex_ingester_received_files counter
cortex_ingester_received_files 0
# HELP cortex_ingester_sent_bytes_total The total number of bytes sent by this ingester whilst leaving
# TYPE cortex_ingester_sent_bytes_total counter
cortex_ingester_sent_bytes_total 0
# HELP cortex_ingester_sent_chunks The total number of chunks sent by this ingester whilst leaving.
# TYPE cortex_ingester_sent_chunks counter
cortex_ingester_sent_chunks 0
# HELP cortex_ingester_sent_files The total number of files sent by this ingester whilst leaving.
# TYPE cortex_ingester_sent_files counter
cortex_ingester_sent_files 0
# HELP cortex_ingester_wal_corruptions_total Total number of WAL corruptions encountered.
# TYPE cortex_ingester_wal_corruptions_total counter
cortex_ingester_wal_corruptions_total 0
# HELP cortex_ingester_wal_replay_duration_seconds Time taken to replay the checkpoint and the WAL.
# TYPE cortex_ingester_wal_replay_duration_seconds gauge
cortex_ingester_wal_replay_duration_seconds 0
# HELP cortex_kv_request_duration_seconds Time spent on consul requests.
# TYPE cortex_kv_request_duration_seconds histogram
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.005"} 13326
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.01"} 14924
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.025"} 15193
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.05"} 15213
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.1"} 15237
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.25"} 15247
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="0.5"} 15249
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="1"} 15252
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="2.5"} 15253
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="5"} 15253
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="10"} 15254
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="200",le="+Inf"} 15255
cortex_kv_request_duration_seconds_sum{operation="CAS",status_code="200"} 145.92407857799998
cortex_kv_request_duration_seconds_count{operation="CAS",status_code="200"} 15255
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.005"} 0
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.01"} 0
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.025"} 0
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.05"} 5
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.1"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.25"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="0.5"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="1"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="2.5"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="5"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="10"} 7
cortex_kv_request_duration_seconds_bucket{operation="CAS",status_code="500",le="+Inf"} 7
cortex_kv_request_duration_seconds_sum{operation="CAS",status_code="500"} 0.325070598
cortex_kv_request_duration_seconds_count{operation="CAS",status_code="500"} 7
# HELP cortex_labels_per_sample Number of labels per sample.
# TYPE cortex_labels_per_sample histogram
cortex_labels_per_sample_bucket{le="5"} 0
cortex_labels_per_sample_bucket{le="10"} 0
cortex_labels_per_sample_bucket{le="15"} 0
cortex_labels_per_sample_bucket{le="20"} 0
cortex_labels_per_sample_bucket{le="25"} 0
cortex_labels_per_sample_bucket{le="+Inf"} 0
cortex_labels_per_sample_sum 0
cortex_labels_per_sample_count 0
# HELP cortex_member_consul_heartbeats_total The total number of heartbeats sent to consul.
# TYPE cortex_member_consul_heartbeats_total counter
cortex_member_consul_heartbeats_total{name="ingester"} 15261
# HELP cortex_member_ring_tokens_owned The number of tokens owned in the ring.
# TYPE cortex_member_ring_tokens_owned gauge
cortex_member_ring_tokens_owned{name="ingester"} 512
# HELP cortex_member_ring_tokens_to_own The number of tokens to own in the ring.
# TYPE cortex_member_ring_tokens_to_own gauge
cortex_member_ring_tokens_to_own{name="ingester"} 512
# HELP cortex_multikv_mirror_enabled Is mirroring to secondary store enabled
# TYPE cortex_multikv_mirror_enabled gauge
cortex_multikv_mirror_enabled 0
# HELP cortex_multikv_mirror_write_errors_total Number of failures to mirror-write to secondary store
# TYPE cortex_multikv_mirror_write_errors_total counter
cortex_multikv_mirror_write_errors_total 0
# HELP cortex_multikv_mirror_writes_total Number of mirror-writes to secondary store
# TYPE cortex_multikv_mirror_writes_total counter
cortex_multikv_mirror_writes_total 0
# HELP cortex_oldest_unflushed_chunk_timestamp_seconds Unix timestamp of the oldest unflushed chunk in the memory
# TYPE cortex_oldest_unflushed_chunk_timestamp_seconds gauge
cortex_oldest_unflushed_chunk_timestamp_seconds 0
# HELP cortex_overrides_last_reload_successful Whether the last config reload attempt was successful.
# TYPE cortex_overrides_last_reload_successful gauge
cortex_overrides_last_reload_successful 0
# HELP cortex_request_duration_seconds Time (in seconds) spent serving HTTP requests.
# TYPE cortex_request_duration_seconds histogram
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.005"} 10
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.01"} 10
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.025"} 10
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.05"} 10
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.1"} 11
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.25"} 11
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="0.5"} 11
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="1"} 11
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="2.5"} 12
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="5"} 12
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="10"} 12
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="25"} 12
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="50"} 13
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="100"} 13
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="200",ws="false",le="+Inf"} 13
cortex_request_duration_seconds_sum{method="GET",route="debug_pprof",status_code="200",ws="false"} 31.067121585
cortex_request_duration_seconds_count{method="GET",route="debug_pprof",status_code="200",ws="false"} 13
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.005"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.01"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.025"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.05"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.1"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.25"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="0.5"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="1"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="2.5"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="5"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="10"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="25"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="50"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="100"} 1
cortex_request_duration_seconds_bucket{method="GET",route="debug_pprof",status_code="301",ws="false",le="+Inf"} 1
cortex_request_duration_seconds_sum{method="GET",route="debug_pprof",status_code="301",ws="false"} 0.000439812
cortex_request_duration_seconds_count{method="GET",route="debug_pprof",status_code="301",ws="false"} 1
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.005"} 5
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.01"} 162
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.025"} 207
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.05"} 209
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.1"} 210
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.25"} 223
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="0.5"} 224
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="1"} 225
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="2.5"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="5"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="10"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="25"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="50"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="100"} 228
cortex_request_duration_seconds_bucket{method="GET",route="metrics",status_code="200",ws="false",le="+Inf"} 228
cortex_request_duration_seconds_sum{method="GET",route="metrics",status_code="200",ws="false"} 9.048584343
cortex_request_duration_seconds_count{method="GET",route="metrics",status_code="200",ws="false"} 228
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.005"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.01"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.025"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.05"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.1"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.25"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="0.5"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="1"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="2.5"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="5"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="10"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="25"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="50"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="100"} 2
cortex_request_duration_seconds_bucket{method="GET",route="other",status_code="404",ws="false",le="+Inf"} 2
cortex_request_duration_seconds_sum{method="GET",route="other",status_code="404",ws="false"} 3.8818999999999995e-05
cortex_request_duration_seconds_count{method="GET",route="other",status_code="404",ws="false"} 2
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.005"} 2
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.01"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.025"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.05"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.1"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.25"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="0.5"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="1"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="2.5"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="5"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="10"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="25"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="50"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="100"} 3
cortex_request_duration_seconds_bucket{method="GET",route="root",status_code="200",ws="false",le="+Inf"} 3
cortex_request_duration_seconds_sum{method="GET",route="root",status_code="200",ws="false"} 0.009229008999999998
cortex_request_duration_seconds_count{method="GET",route="root",status_code="200",ws="false"} 3
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.005"} 2632
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.01"} 254748
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.025"} 846068
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.05"} 851167
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.1"} 852352
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.25"} 854368
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="0.5"} 856681
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="1"} 860122
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="2.5"} 869666
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="5"} 877697
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="10"} 883907
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="25"} 890230
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="50"} 894599
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="100"} 898994
cortex_request_duration_seconds_bucket{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false",le="+Inf"} 903861
cortex_request_duration_seconds_sum{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false"} 1.3237461937719362e+06
cortex_request_duration_seconds_count{method="gRPC",route="/cortex.Ingester/Push",status_code="success",ws="false"} 903861
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.005"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.01"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.025"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.05"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.1"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.25"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="0.5"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="1"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="2.5"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="5"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="10"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="25"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="50"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="100"} 15244
cortex_request_duration_seconds_bucket{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false",le="+Inf"} 15244
cortex_request_duration_seconds_sum{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false"} 0.387371484999998
cortex_request_duration_seconds_count{method="gRPC",route="/grpc.health.v1.Health/Check",status_code="success",ws="false"} 15244
# HELP cortex_ruler_managers_total Total number of managers registered and running in the ruler
# TYPE cortex_ruler_managers_total gauge
cortex_ruler_managers_total 0
# HELP cortex_ruler_ring_check_errors_total Number of errors that have occurred when checking the ring for ownership
# TYPE cortex_ruler_ring_check_errors_total counter
cortex_ruler_ring_check_errors_total 0
# HELP etcd_debugging_disk_backend_commit_rebalance_duration_seconds The latency distributions of commit.rebalance called by bboltdb backend.
# TYPE etcd_debugging_disk_backend_commit_rebalance_duration_seconds histogram
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.002"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.004"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.008"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.016"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.032"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.064"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.128"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.256"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.512"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="1.024"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="2.048"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="4.096"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="8.192"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="+Inf"} 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_sum 0
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_count 0
# HELP etcd_debugging_disk_backend_commit_spill_duration_seconds The latency distributions of commit.spill called by bboltdb backend.
# TYPE etcd_debugging_disk_backend_commit_spill_duration_seconds histogram
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.002"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.004"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.008"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.016"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.032"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.064"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.128"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.256"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="0.512"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="1.024"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="2.048"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="4.096"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="8.192"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{le="+Inf"} 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_sum 0
etcd_debugging_disk_backend_commit_spill_duration_seconds_count 0
# HELP etcd_debugging_disk_backend_commit_write_duration_seconds The latency distributions of commit.write called by bboltdb backend.
# TYPE etcd_debugging_disk_backend_commit_write_duration_seconds histogram
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.002"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.004"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.008"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.016"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.032"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.064"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.128"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.256"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="0.512"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="1.024"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="2.048"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="4.096"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="8.192"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{le="+Inf"} 0
etcd_debugging_disk_backend_commit_write_duration_seconds_sum 0
etcd_debugging_disk_backend_commit_write_duration_seconds_count 0
# HELP etcd_debugging_lease_granted_total The total number of granted leases.
# TYPE etcd_debugging_lease_granted_total counter
etcd_debugging_lease_granted_total 0
# HELP etcd_debugging_lease_renewed_total The number of renewed leases seen by the leader.
# TYPE etcd_debugging_lease_renewed_total counter
etcd_debugging_lease_renewed_total 0
# HELP etcd_debugging_lease_revoked_total The total number of revoked leases.
# TYPE etcd_debugging_lease_revoked_total counter
etcd_debugging_lease_revoked_total 0
# HELP etcd_debugging_lease_ttl_total Bucketed histogram of lease TTLs.
# TYPE etcd_debugging_lease_ttl_total histogram
etcd_debugging_lease_ttl_total_bucket{le="1"} 0
etcd_debugging_lease_ttl_total_bucket{le="2"} 0
etcd_debugging_lease_ttl_total_bucket{le="4"} 0
etcd_debugging_lease_ttl_total_bucket{le="8"} 0
etcd_debugging_lease_ttl_total_bucket{le="16"} 0
etcd_debugging_lease_ttl_total_bucket{le="32"} 0
etcd_debugging_lease_ttl_total_bucket{le="64"} 0
etcd_debugging_lease_ttl_total_bucket{le="128"} 0
etcd_debugging_lease_ttl_total_bucket{le="256"} 0
etcd_debugging_lease_ttl_total_bucket{le="512"} 0
etcd_debugging_lease_ttl_total_bucket{le="1024"} 0
etcd_debugging_lease_ttl_total_bucket{le="2048"} 0
etcd_debugging_lease_ttl_total_bucket{le="4096"} 0
etcd_debugging_lease_ttl_total_bucket{le="8192"} 0
etcd_debugging_lease_ttl_total_bucket{le="16384"} 0
etcd_debugging_lease_ttl_total_bucket{le="32768"} 0
etcd_debugging_lease_ttl_total_bucket{le="65536"} 0
etcd_debugging_lease_ttl_total_bucket{le="131072"} 0
etcd_debugging_lease_ttl_total_bucket{le="262144"} 0
etcd_debugging_lease_ttl_total_bucket{le="524288"} 0
etcd_debugging_lease_ttl_total_bucket{le="1.048576e+06"} 0
etcd_debugging_lease_ttl_total_bucket{le="2.097152e+06"} 0
etcd_debugging_lease_ttl_total_bucket{le="4.194304e+06"} 0
etcd_debugging_lease_ttl_total_bucket{le="8.388608e+06"} 0
etcd_debugging_lease_ttl_total_bucket{le="+Inf"} 0
etcd_debugging_lease_ttl_total_sum 0
etcd_debugging_lease_ttl_total_count 0
# HELP etcd_debugging_mvcc_compact_revision The revision of the last compaction in store.
# TYPE etcd_debugging_mvcc_compact_revision gauge
etcd_debugging_mvcc_compact_revision 0
# HELP etcd_debugging_mvcc_current_revision The current revision of store.
# TYPE etcd_debugging_mvcc_current_revision gauge
etcd_debugging_mvcc_current_revision 0
# HELP etcd_debugging_mvcc_db_compaction_keys_total Total number of db keys compacted.
# TYPE etcd_debugging_mvcc_db_compaction_keys_total counter
etcd_debugging_mvcc_db_compaction_keys_total 0
# HELP etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds Bucketed histogram of db compaction pause duration.
# TYPE etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds histogram
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="1"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="2"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="4"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="8"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="16"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="32"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="64"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="128"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="256"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="512"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="1024"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="2048"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="4096"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket{le="+Inf"} 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_sum 0
etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_count 0
# HELP etcd_debugging_mvcc_db_compaction_total_duration_milliseconds Bucketed histogram of db compaction total duration.
# TYPE etcd_debugging_mvcc_db_compaction_total_duration_milliseconds histogram
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="100"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="200"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="400"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="800"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="1600"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="3200"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="6400"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="12800"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="25600"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="51200"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="102400"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="204800"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="409600"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="819200"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="+Inf"} 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_sum 0
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_count 0
# HELP etcd_debugging_mvcc_db_total_size_in_bytes Total size of the underlying database physically allocated in bytes.
# TYPE etcd_debugging_mvcc_db_total_size_in_bytes gauge
etcd_debugging_mvcc_db_total_size_in_bytes 0
# HELP etcd_debugging_mvcc_delete_total Total number of deletes seen by this member.
# TYPE etcd_debugging_mvcc_delete_total counter
etcd_debugging_mvcc_delete_total 0
# HELP etcd_debugging_mvcc_events_total Total number of events sent by this member.
# TYPE etcd_debugging_mvcc_events_total counter
etcd_debugging_mvcc_events_total 0
# HELP etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds Bucketed histogram of index compaction pause duration.
# TYPE etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds histogram
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="0.5"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="1"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="2"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="4"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="8"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="16"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="32"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="64"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="128"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="256"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="512"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="1024"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="2048"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="4096"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket{le="+Inf"} 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_sum 0
etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_count 0
# HELP etcd_debugging_mvcc_keys_total Total number of keys.
# TYPE etcd_debugging_mvcc_keys_total gauge
etcd_debugging_mvcc_keys_total 0
# HELP etcd_debugging_mvcc_pending_events_total Total number of pending events to be sent.
# TYPE etcd_debugging_mvcc_pending_events_total gauge
etcd_debugging_mvcc_pending_events_total 0
# HELP etcd_debugging_mvcc_put_total Total number of puts seen by this member.
# TYPE etcd_debugging_mvcc_put_total counter
etcd_debugging_mvcc_put_total 0
# HELP etcd_debugging_mvcc_range_total Total number of ranges seen by this member.
# TYPE etcd_debugging_mvcc_range_total counter
etcd_debugging_mvcc_range_total 0
# HELP etcd_debugging_mvcc_slow_watcher_total Total number of unsynced slow watchers.
# TYPE etcd_debugging_mvcc_slow_watcher_total gauge
etcd_debugging_mvcc_slow_watcher_total 0
# HELP etcd_debugging_mvcc_txn_total Total number of txns seen by this member.
# TYPE etcd_debugging_mvcc_txn_total counter
etcd_debugging_mvcc_txn_total 0
# HELP etcd_debugging_mvcc_watch_stream_total Total number of watch streams.
# TYPE etcd_debugging_mvcc_watch_stream_total gauge
etcd_debugging_mvcc_watch_stream_total 0
# HELP etcd_debugging_mvcc_watcher_total Total number of watchers.
# TYPE etcd_debugging_mvcc_watcher_total gauge
etcd_debugging_mvcc_watcher_total 0
# HELP etcd_debugging_server_lease_expired_total The total number of expired leases.
# TYPE etcd_debugging_server_lease_expired_total counter
etcd_debugging_server_lease_expired_total 0
# HELP etcd_debugging_snap_save_marshalling_duration_seconds The marshalling cost distributions of save called by snapshot.
# TYPE etcd_debugging_snap_save_marshalling_duration_seconds histogram
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.002"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.004"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.008"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.016"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.032"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.064"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.128"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.256"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="0.512"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="1.024"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="2.048"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="4.096"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="8.192"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_bucket{le="+Inf"} 0
etcd_debugging_snap_save_marshalling_duration_seconds_sum 0
etcd_debugging_snap_save_marshalling_duration_seconds_count 0
# HELP etcd_debugging_snap_save_total_duration_seconds The total latency distributions of save called by snapshot.
# TYPE etcd_debugging_snap_save_total_duration_seconds histogram
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.001"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.002"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.004"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.008"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.016"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.032"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.064"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.128"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.256"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="0.512"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="1.024"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="2.048"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="4.096"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="8.192"} 0
etcd_debugging_snap_save_total_duration_seconds_bucket{le="+Inf"} 0
etcd_debugging_snap_save_total_duration_seconds_sum 0
etcd_debugging_snap_save_total_duration_seconds_count 0
# HELP etcd_debugging_store_expires_total Total number of expired keys.
# TYPE etcd_debugging_store_expires_total counter
etcd_debugging_store_expires_total 0
# HELP etcd_debugging_store_watch_requests_total Total number of incoming watch requests (new or reestablished).
# TYPE etcd_debugging_store_watch_requests_total counter
etcd_debugging_store_watch_requests_total 0
# HELP etcd_debugging_store_watchers Count of currently active watchers.
# TYPE etcd_debugging_store_watchers gauge
etcd_debugging_store_watchers 0
# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_commit_duration_seconds_sum 0
etcd_disk_backend_commit_duration_seconds_count 0
# HELP etcd_disk_backend_defrag_duration_seconds The latency distribution of backend defragmentation.
# TYPE etcd_disk_backend_defrag_duration_seconds histogram
etcd_disk_backend_defrag_duration_seconds_bucket{le="0.1"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="0.2"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="0.4"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="0.8"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="1.6"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="3.2"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="6.4"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="12.8"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="25.6"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="51.2"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="102.4"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="204.8"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="409.6"} 0
etcd_disk_backend_defrag_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_defrag_duration_seconds_sum 0
etcd_disk_backend_defrag_duration_seconds_count 0
# HELP etcd_disk_backend_snapshot_duration_seconds The latency distribution of backend snapshots.
# TYPE etcd_disk_backend_snapshot_duration_seconds histogram
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.01"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.02"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.04"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.08"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.16"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.32"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.64"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="1.28"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="2.56"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="5.12"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="10.24"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="20.48"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="40.96"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="81.92"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="163.84"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="327.68"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="655.36"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_snapshot_duration_seconds_sum 0
etcd_disk_backend_snapshot_duration_seconds_count 0
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by WAL.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_wal_fsync_duration_seconds_sum 0
etcd_disk_wal_fsync_duration_seconds_count 0
# HELP etcd_mvcc_db_open_read_transactions The number of currently open read transactions
# TYPE etcd_mvcc_db_open_read_transactions gauge
etcd_mvcc_db_open_read_transactions 0
# HELP etcd_mvcc_db_total_size_in_bytes Total size of the underlying database physically allocated in bytes.
# TYPE etcd_mvcc_db_total_size_in_bytes gauge
etcd_mvcc_db_total_size_in_bytes 0
# HELP etcd_mvcc_db_total_size_in_use_in_bytes Total size of the underlying database logically in use in bytes.
# TYPE etcd_mvcc_db_total_size_in_use_in_bytes gauge
etcd_mvcc_db_total_size_in_use_in_bytes 0
# HELP etcd_mvcc_delete_total Total number of deletes seen by this member.
# TYPE etcd_mvcc_delete_total counter
etcd_mvcc_delete_total 0
# HELP etcd_mvcc_hash_duration_seconds The latency distribution of storage hash operation.
# TYPE etcd_mvcc_hash_duration_seconds histogram
etcd_mvcc_hash_duration_seconds_bucket{le="0.01"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.02"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.04"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.08"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.16"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.32"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="0.64"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="1.28"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="2.56"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="5.12"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="10.24"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="20.48"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="40.96"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="81.92"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="163.84"} 0
etcd_mvcc_hash_duration_seconds_bucket{le="+Inf"} 0
etcd_mvcc_hash_duration_seconds_sum 0
etcd_mvcc_hash_duration_seconds_count 0
# HELP etcd_mvcc_hash_rev_duration_seconds The latency distribution of storage hash by revision operation.
# TYPE etcd_mvcc_hash_rev_duration_seconds histogram
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.01"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.02"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.04"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.08"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.16"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.32"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="0.64"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="1.28"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="2.56"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="5.12"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="10.24"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="20.48"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="40.96"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="81.92"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="163.84"} 0
etcd_mvcc_hash_rev_duration_seconds_bucket{le="+Inf"} 0
etcd_mvcc_hash_rev_duration_seconds_sum 0
etcd_mvcc_hash_rev_duration_seconds_count 0
# HELP etcd_mvcc_put_total Total number of puts seen by this member.
# TYPE etcd_mvcc_put_total counter
etcd_mvcc_put_total 0
# HELP etcd_mvcc_range_total Total number of ranges seen by this member.
# TYPE etcd_mvcc_range_total counter
etcd_mvcc_range_total 0
# HELP etcd_mvcc_txn_total Total number of txns seen by this member.
# TYPE etcd_mvcc_txn_total counter
etcd_mvcc_txn_total 0
# HELP etcd_network_client_grpc_received_bytes_total The total number of bytes received from grpc clients.
# TYPE etcd_network_client_grpc_received_bytes_total counter
etcd_network_client_grpc_received_bytes_total 0
# HELP etcd_network_client_grpc_sent_bytes_total The total number of bytes sent to grpc clients.
# TYPE etcd_network_client_grpc_sent_bytes_total counter
etcd_network_client_grpc_sent_bytes_total 0
# HELP etcd_server_go_version Which Go version server is running with. 1 for 'server_go_version' label with current version.
# TYPE etcd_server_go_version gauge
etcd_server_go_version{server_go_version="go1.13.8"} 1
# HELP etcd_server_has_leader Whether or not a leader exists. 1 is existence, 0 is not.
# TYPE etcd_server_has_leader gauge
etcd_server_has_leader 0
# HELP etcd_server_health_failures The total number of failed health checks
# TYPE etcd_server_health_failures counter
etcd_server_health_failures 0
# HELP etcd_server_health_success The total number of successful health checks
# TYPE etcd_server_health_success counter
etcd_server_health_success 0
# HELP etcd_server_heartbeat_send_failures_total The total number of leader heartbeat send failures (likely overloaded from slow disk).
# TYPE etcd_server_heartbeat_send_failures_total counter
etcd_server_heartbeat_send_failures_total 0
# HELP etcd_server_is_leader Whether or not this member is a leader. 1 if is, 0 otherwise.
# TYPE etcd_server_is_leader gauge
etcd_server_is_leader 0
# HELP etcd_server_is_learner Whether or not this member is a learner. 1 if is, 0 otherwise.
# TYPE etcd_server_is_learner gauge
etcd_server_is_learner 0
# HELP etcd_server_leader_changes_seen_total The number of leader changes seen.
# TYPE etcd_server_leader_changes_seen_total counter
etcd_server_leader_changes_seen_total 0
# HELP etcd_server_learner_promote_successes The total number of successful learner promotions while this member is leader.
# TYPE etcd_server_learner_promote_successes counter
etcd_server_learner_promote_successes 0
# HELP etcd_server_proposals_applied_total The total number of consensus proposals applied.
# TYPE etcd_server_proposals_applied_total gauge
etcd_server_proposals_applied_total 0
# HELP etcd_server_proposals_committed_total The total number of consensus proposals committed.
# TYPE etcd_server_proposals_committed_total gauge
etcd_server_proposals_committed_total 0
# HELP etcd_server_proposals_failed_total The total number of failed proposals seen.
# TYPE etcd_server_proposals_failed_total counter
etcd_server_proposals_failed_total 0
# HELP etcd_server_proposals_pending The current number of pending proposals to commit.
# TYPE etcd_server_proposals_pending gauge
etcd_server_proposals_pending 0
# HELP etcd_server_quota_backend_bytes Current backend storage quota size in bytes.
# TYPE etcd_server_quota_backend_bytes gauge
etcd_server_quota_backend_bytes 0
# HELP etcd_server_read_indexes_failed_total The total number of failed read indexes seen.
# TYPE etcd_server_read_indexes_failed_total counter
etcd_server_read_indexes_failed_total 0
# HELP etcd_server_slow_apply_total The total number of slow apply requests (likely overloaded from slow disk).
# TYPE etcd_server_slow_apply_total counter
etcd_server_slow_apply_total 0
# HELP etcd_server_slow_read_indexes_total The total number of pending read indexes not in sync with leader's or timed out read index requests.
# TYPE etcd_server_slow_read_indexes_total counter
etcd_server_slow_read_indexes_total 0
# HELP etcd_server_snapshot_apply_in_progress_total 1 if the server is applying the incoming snapshot. 0 if none.
# TYPE etcd_server_snapshot_apply_in_progress_total gauge
etcd_server_snapshot_apply_in_progress_total 0
# HELP etcd_server_version Which version is running. 1 for 'server_version' label with current version.
# TYPE etcd_server_version gauge
etcd_server_version{server_version="3.4.3"} 1
# HELP etcd_snap_db_fsync_duration_seconds The latency distributions of fsyncing .snap.db file
# TYPE etcd_snap_db_fsync_duration_seconds histogram
etcd_snap_db_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.002"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.004"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.008"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.016"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.032"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.064"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.128"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.256"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="0.512"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="1.024"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="2.048"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="4.096"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="8.192"} 0
etcd_snap_db_fsync_duration_seconds_bucket{le="+Inf"} 0
etcd_snap_db_fsync_duration_seconds_sum 0
etcd_snap_db_fsync_duration_seconds_count 0
# HELP etcd_snap_db_save_total_duration_seconds The total latency distributions of v3 snapshot save
# TYPE etcd_snap_db_save_total_duration_seconds histogram
etcd_snap_db_save_total_duration_seconds_bucket{le="0.1"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="0.2"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="0.4"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="0.8"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="1.6"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="3.2"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="6.4"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="12.8"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="25.6"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="51.2"} 0
etcd_snap_db_save_total_duration_seconds_bucket{le="+Inf"} 0
etcd_snap_db_save_total_duration_seconds_sum 0
etcd_snap_db_save_total_duration_seconds_count 0
# HELP etcd_snap_fsync_duration_seconds The latency distributions of fsync called by snap.
# TYPE etcd_snap_fsync_duration_seconds histogram
etcd_snap_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.002"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.004"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.008"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.016"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.032"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.064"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.128"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.256"} 0
etcd_snap_fsync_duration_seconds_bucket{le="0.512"} 0
etcd_snap_fsync_duration_seconds_bucket{le="1.024"} 0
etcd_snap_fsync_duration_seconds_bucket{le="2.048"} 0
etcd_snap_fsync_duration_seconds_bucket{le="4.096"} 0
etcd_snap_fsync_duration_seconds_bucket{le="8.192"} 0
etcd_snap_fsync_duration_seconds_bucket{le="+Inf"} 0
etcd_snap_fsync_duration_seconds_sum 0
etcd_snap_fsync_duration_seconds_count 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 5.3234e-05
go_gc_duration_seconds{quantile="0.25"} 6.0873e-05
go_gc_duration_seconds{quantile="0.5"} 6.3193e-05
go_gc_duration_seconds{quantile="0.75"} 6.6474e-05
go_gc_duration_seconds{quantile="1"} 0.008191262
go_gc_duration_seconds_sum 0.31133241
go_gc_duration_seconds_count 764
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 146
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.13.8"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.352794808e+09
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 3.243068391176e+12
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.842255e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1.4733050886e+10
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 0.002024465123759951
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.705706496e+09
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.352794808e+09
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 9.9051773952e+10
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.013271552e+09
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 1.0951074e+07
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 9.8769731584e+10
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.02065045504e+11
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.5909174477313414e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 1.474400196e+10
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 83328
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 98304
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 7.0468536e+07
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 6.90143232e+08
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 2.684772192e+09
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.72319713e+08
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 7.53664e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 7.53664e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.06642692144e+11
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 115
# HELP jaeger_tracer_baggage_restrictions_updates_total Number of times baggage restrictions were successfully updated
# TYPE jaeger_tracer_baggage_restrictions_updates_total counter
jaeger_tracer_baggage_restrictions_updates_total{result="err"} 0
jaeger_tracer_baggage_restrictions_updates_total{result="ok"} 0
# HELP jaeger_tracer_baggage_truncations_total Number of times baggage was truncated as per baggage restrictions
# TYPE jaeger_tracer_baggage_truncations_total counter
jaeger_tracer_baggage_truncations_total 0
# HELP jaeger_tracer_baggage_updates_total Number of times baggage was successfully written or updated on spans
# TYPE jaeger_tracer_baggage_updates_total counter
jaeger_tracer_baggage_updates_total{result="err"} 0
jaeger_tracer_baggage_updates_total{result="ok"} 0
# HELP jaeger_tracer_finished_spans_total Number of sampled spans finished by this tracer
# TYPE jaeger_tracer_finished_spans_total counter
jaeger_tracer_finished_spans_total{sampled="delayed"} 0
jaeger_tracer_finished_spans_total{sampled="n"} 2.1605478e+07
jaeger_tracer_finished_spans_total{sampled="y"} 21100
# HELP jaeger_tracer_reporter_queue_length Current number of spans in the reporter queue
# TYPE jaeger_tracer_reporter_queue_length gauge
jaeger_tracer_reporter_queue_length 0
# HELP jaeger_tracer_reporter_spans_total Number of spans successfully reported
# TYPE jaeger_tracer_reporter_spans_total counter
jaeger_tracer_reporter_spans_total{result="dropped"} 0
jaeger_tracer_reporter_spans_total{result="err"} 0
jaeger_tracer_reporter_spans_total{result="ok"} 21100
# HELP jaeger_tracer_sampler_queries_total Number of times the Sampler succeeded to retrieve sampling strategy
# TYPE jaeger_tracer_sampler_queries_total counter
jaeger_tracer_sampler_queries_total{result="err"} 0
jaeger_tracer_sampler_queries_total{result="ok"} 1273
# HELP jaeger_tracer_sampler_updates_total Number of times the Sampler succeeded to retrieve and update sampling strategy
# TYPE jaeger_tracer_sampler_updates_total counter
jaeger_tracer_sampler_updates_total{result="err"} 0
jaeger_tracer_sampler_updates_total{result="ok"} 1273
# HELP jaeger_tracer_span_context_decoding_errors_total Number of errors decoding tracing context
# TYPE jaeger_tracer_span_context_decoding_errors_total counter
jaeger_tracer_span_context_decoding_errors_total 0
# HELP jaeger_tracer_started_spans_total Number of spans started by this tracer as sampled
# TYPE jaeger_tracer_started_spans_total counter
jaeger_tracer_started_spans_total{sampled="delayed"} 0
jaeger_tracer_started_spans_total{sampled="n"} 4.2245745e+07
jaeger_tracer_started_spans_total{sampled="y"} 41903
# HELP jaeger_tracer_throttled_debug_spans_total Number of times debug spans were throttled
# TYPE jaeger_tracer_throttled_debug_spans_total counter
jaeger_tracer_throttled_debug_spans_total 0
# HELP jaeger_tracer_throttler_updates_total Number of times throttler successfully updated
# TYPE jaeger_tracer_throttler_updates_total counter
jaeger_tracer_throttler_updates_total{result="err"} 0
jaeger_tracer_throttler_updates_total{result="ok"} 0
# HELP jaeger_tracer_traces_total Number of traces started by this tracer as sampled
# TYPE jaeger_tracer_traces_total counter
jaeger_tracer_traces_total{sampled="n",state="joined"} 918830
jaeger_tracer_traces_total{sampled="n",state="started"} 2.0639263e+07
jaeger_tracer_traces_total{sampled="y",state="joined"} 275
jaeger_tracer_traces_total{sampled="y",state="started"} 20796
# HELP log_messages_total Total number of log messages.
# TYPE log_messages_total counter
log_messages_total{level="debug"} 920185
log_messages_total{level="error"} 9
log_messages_total{level="info"} 9
log_messages_total{level="warn"} 4
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 95894.67
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 100000
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 25
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.05635426304e+11
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.59083615923e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.06772217856e+11
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP prometheus_api_remote_read_queries The current number of remote read queries being executed or waiting.
# TYPE prometheus_api_remote_read_queries gauge
prometheus_api_remote_read_queries 0
# HELP prometheus_local_storage_memory_chunkdescs The current number of chunk descriptors in memory.
# TYPE prometheus_local_storage_memory_chunkdescs gauge
prometheus_local_storage_memory_chunkdescs 0
# HELP prometheus_remote_storage_highest_timestamp_in_seconds Highest timestamp that has come into the remote storage via the Appender interface, in seconds since epoch.
# TYPE prometheus_remote_storage_highest_timestamp_in_seconds gauge
prometheus_remote_storage_highest_timestamp_in_seconds 0
# HELP prometheus_remote_storage_samples_in_total Samples in to remote storage, compare to samples out for queue managers.
# TYPE prometheus_remote_storage_samples_in_total counter
prometheus_remote_storage_samples_in_total 0
# HELP prometheus_remote_storage_string_interner_zero_reference_releases_total The number of times release has been called for strings that are not interned.
# TYPE prometheus_remote_storage_string_interner_zero_reference_releases_total counter
prometheus_remote_storage_string_interner_zero_reference_releases_total 0
# HELP prometheus_sd_consul_rpc_duration_seconds The duration of a Consul RPC call in seconds.
# TYPE prometheus_sd_consul_rpc_duration_seconds summary
prometheus_sd_consul_rpc_duration_seconds{call="service",endpoint="catalog",quantile="0.5"} NaN
prometheus_sd_consul_rpc_duration_seconds{call="service",endpoint="catalog",quantile="0.9"} NaN
prometheus_sd_consul_rpc_duration_seconds{call="service",endpoint="catalog",quantile="0.99"} NaN
prometheus_sd_consul_rpc_duration_seconds_sum{call="service",endpoint="catalog"} 0
prometheus_sd_consul_rpc_duration_seconds_count{call="service",endpoint="catalog"} 0
prometheus_sd_consul_rpc_duration_seconds{call="services",endpoint="catalog",quantile="0.5"} NaN
prometheus_sd_consul_rpc_duration_seconds{call="services",endpoint="catalog",quantile="0.9"} NaN
prometheus_sd_consul_rpc_duration_seconds{call="services",endpoint="catalog",quantile="0.99"} NaN
prometheus_sd_consul_rpc_duration_seconds_sum{call="services",endpoint="catalog"} 0
prometheus_sd_consul_rpc_duration_seconds_count{call="services",endpoint="catalog"} 0
# HELP prometheus_sd_consul_rpc_failures_total The number of Consul RPC call failures.
# TYPE prometheus_sd_consul_rpc_failures_total counter
prometheus_sd_consul_rpc_failures_total 0
# HELP prometheus_sd_dns_lookup_failures_total The number of DNS-SD lookup failures.
# TYPE prometheus_sd_dns_lookup_failures_total counter
prometheus_sd_dns_lookup_failures_total 0
# HELP prometheus_sd_dns_lookups_total The number of DNS-SD lookups.
# TYPE prometheus_sd_dns_lookups_total counter
prometheus_sd_dns_lookups_total 0
# HELP prometheus_sd_file_read_errors_total The number of File-SD read errors.
# TYPE prometheus_sd_file_read_errors_total counter
prometheus_sd_file_read_errors_total 0
# HELP prometheus_sd_file_scan_duration_seconds The duration of the File-SD scan in seconds.
# TYPE prometheus_sd_file_scan_duration_seconds summary
prometheus_sd_file_scan_duration_seconds{quantile="0.5"} NaN
prometheus_sd_file_scan_duration_seconds{quantile="0.9"} NaN
prometheus_sd_file_scan_duration_seconds{quantile="0.99"} NaN
prometheus_sd_file_scan_duration_seconds_sum 0
prometheus_sd_file_scan_duration_seconds_count 0
# HELP prometheus_sd_kubernetes_events_total The number of Kubernetes events handled.
# TYPE prometheus_sd_kubernetes_events_total counter
prometheus_sd_kubernetes_events_total{event="add",role="endpoints"} 0
prometheus_sd_kubernetes_events_total{event="add",role="ingress"} 0
prometheus_sd_kubernetes_events_total{event="add",role="node"} 0
prometheus_sd_kubernetes_events_total{event="add",role="pod"} 0
prometheus_sd_kubernetes_events_total{event="add",role="service"} 0
prometheus_sd_kubernetes_events_total{event="delete",role="endpoints"} 0
prometheus_sd_kubernetes_events_total{event="delete",role="ingress"} 0
prometheus_sd_kubernetes_events_total{event="delete",role="node"} 0
prometheus_sd_kubernetes_events_total{event="delete",role="pod"} 0
prometheus_sd_kubernetes_events_total{event="delete",role="service"} 0
prometheus_sd_kubernetes_events_total{event="update",role="endpoints"} 0
prometheus_sd_kubernetes_events_total{event="update",role="ingress"} 0
prometheus_sd_kubernetes_events_total{event="update",role="node"} 0
prometheus_sd_kubernetes_events_total{event="update",role="pod"} 0
prometheus_sd_kubernetes_events_total{event="update",role="service"} 0
# HELP prometheus_target_scrape_pool_reloads_failed_total Total number of failed scrape loop reloads.
# TYPE prometheus_target_scrape_pool_reloads_failed_total counter
prometheus_target_scrape_pool_reloads_failed_total 0
# HELP prometheus_target_scrape_pool_reloads_total Total number of scrape loop reloads.
# TYPE prometheus_target_scrape_pool_reloads_total counter
prometheus_target_scrape_pool_reloads_total 0
# HELP prometheus_target_scrape_pools_failed_total Total number of scrape pool creations that failed.
# TYPE prometheus_target_scrape_pools_failed_total counter
prometheus_target_scrape_pools_failed_total 0
# HELP prometheus_target_scrape_pools_total Total number of scrape pool creation attempts.
# TYPE prometheus_target_scrape_pools_total counter
prometheus_target_scrape_pools_total 0
# HELP prometheus_target_scrapes_cache_flush_forced_total How many times a scrape cache was flushed due to getting big while scrapes are failing.
# TYPE prometheus_target_scrapes_cache_flush_forced_total counter
prometheus_target_scrapes_cache_flush_forced_total 0
# HELP prometheus_target_scrapes_exceeded_sample_limit_total Total number of scrapes that hit the sample limit and were rejected.
# TYPE prometheus_target_scrapes_exceeded_sample_limit_total counter
prometheus_target_scrapes_exceeded_sample_limit_total 0
# HELP prometheus_target_scrapes_sample_duplicate_timestamp_total Total number of samples rejected due to duplicate timestamps but different values
# TYPE prometheus_target_scrapes_sample_duplicate_timestamp_total counter
prometheus_target_scrapes_sample_duplicate_timestamp_total 0
# HELP prometheus_target_scrapes_sample_out_of_bounds_total Total number of samples rejected due to timestamp falling outside of the time bounds
# TYPE prometheus_target_scrapes_sample_out_of_bounds_total counter
prometheus_target_scrapes_sample_out_of_bounds_total 0
# HELP prometheus_target_scrapes_sample_out_of_order_total Total number of samples rejected due to not being out of the expected order
# TYPE prometheus_target_scrapes_sample_out_of_order_total counter
prometheus_target_scrapes_sample_out_of_order_total 0
# HELP prometheus_template_text_expansion_failures_total The total number of template text expansion failures.
# TYPE prometheus_template_text_expansion_failures_total counter
prometheus_template_text_expansion_failures_total 0
# HELP prometheus_template_text_expansions_total The total number of template text expansions.
# TYPE prometheus_template_text_expansions_total counter
prometheus_template_text_expansions_total 0
# HELP prometheus_treecache_watcher_goroutines The current number of watcher goroutines.
# TYPE prometheus_treecache_watcher_goroutines gauge
prometheus_treecache_watcher_goroutines 0
# HELP prometheus_treecache_zookeeper_failures_total The total number of ZooKeeper failures.
# TYPE prometheus_treecache_zookeeper_failures_total counter
prometheus_treecache_zookeeper_failures_total 0
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 226
promhttp_metric_handler_requests_total{code="500"} 2
promhttp_metric_handler_requests_total{code="503"} 0
# HELP querier_index_cache_corruptions_total The number of cache corruptions for the index cache.
# TYPE querier_index_cache_corruptions_total counter
querier_index_cache_corruptions_total 0
# HELP querier_index_cache_encode_errors_total The number of errors for the index cache while encoding the body.
# TYPE querier_index_cache_encode_errors_total counter
querier_index_cache_encode_errors_total 0
# HELP querier_index_cache_gets_total The number of gets for the index cache.
# TYPE querier_index_cache_gets_total counter
querier_index_cache_gets_total 0
# HELP querier_index_cache_hits_total The number of cache hits for the index cache.
# TYPE querier_index_cache_hits_total counter
querier_index_cache_hits_total 0
# HELP querier_index_cache_puts_total The number of puts for the index cache.
# TYPE querier_index_cache_puts_total counter
querier_index_cache_puts_total 0
```

#### 2. smaps info
```
00400000-02b2a000 r-xp 00000000 08:03 134219526                          /data/app/cortex/cortex
Size:              40104 kB
Rss:                6732 kB
Pss:                3163 kB
Shared_Clean:       5344 kB
Shared_Dirty:          0 kB
Private_Clean:      1388 kB
Private_Dirty:         0 kB
Referenced:         6732 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd ex mr mw me dw ?? sd
02b2a000-05b7c000 r--p 0272a000 08:03 134219526                          /data/app/cortex/cortex
Size:              49480 kB
Rss:               21516 kB
Pss:                7825 kB
Shared_Clean:      18484 kB
Shared_Dirty:          0 kB
Private_Clean:      3032 kB
Private_Dirty:         0 kB
Referenced:        21480 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd mr mw me dw ?? sd
05b7c000-05c2d000 rw-p 0577c000 08:03 134219526                          /data/app/cortex/cortex
Size:                708 kB
Rss:                 560 kB
Pss:                 365 kB
Shared_Clean:        288 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       272 kB
Referenced:          560 kB
Anonymous:           272 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me dw ac ?? sd
05c2d000-05c68000 rw-p 00000000 00:00 0
Size:                236 kB
Rss:                 216 kB
Pss:                 216 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:       216 kB
Referenced:          216 kB
Anonymous:           216 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
c000000000-d7c4000000 rw-p 00000000 00:00 0
Size:           99680256 kB
Rss:            98713804 kB
Pss:            98713804 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:  95498752 kB
Private_Dirty:   3215052 kB
Referenced:      4931500 kB
Anonymous:      98713804 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 36 kB
SwapPss:              36 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac ?? sd
7f29dfb1c000-7f2a765a4000 rw-p 00000000 00:00 0
Size:            2468384 kB
Rss:             2442956 kB
Pss:             2442956 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:   2442956 kB
Referenced:      2442956 kB
Anonymous:       2442956 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2a765b3000-7f2ab17e1000 rw-p 00000000 00:00 0
Size:             968888 kB
Rss:              964032 kB
Pss:              964032 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    964032 kB
Referenced:       960160 kB
Anonymous:        964032 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2ab17e8000-7f2ac8d0a000 rw-p 00000000 00:00 0
Size:             382088 kB
Rss:              379604 kB
Pss:              379604 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:        12 kB
Private_Dirty:    379592 kB
Referenced:       371736 kB
Anonymous:        379604 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 36 kB
SwapPss:              36 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2ac8d11000-7f2ad72dc000 rw-p 00000000 00:00 0
Size:             235308 kB
Rss:              233432 kB
Pss:              233432 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:        24 kB
Private_Dirty:    233408 kB
Referenced:       232952 kB
Anonymous:        233432 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2ad72e6000-7f2adf820000 rw-p 00000000 00:00 0
Size:             136424 kB
Rss:              135236 kB
Pss:              135236 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    135236 kB
Referenced:       135236 kB
Anonymous:        135236 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  8 kB
SwapPss:               8 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2adf826000-7f2ae5745000 rw-p 00000000 00:00 0
Size:              97404 kB
Rss:               93808 kB
Pss:               93808 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:     93808 kB
Referenced:        93808 kB
Anonymous:         93808 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:               2872 kB
SwapPss:            2872 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2ae574f000-7f2ae8ef1000 rw-p 00000000 00:00 0
Size:              56968 kB
Rss:               55660 kB
Pss:               55660 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:        80 kB
Private_Dirty:     55580 kB
Referenced:        55624 kB
Anonymous:         55660 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                840 kB
SwapPss:             840 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2ae8ef9000-7f2aeb062000 rw-p 00000000 00:00 0
Size:              34212 kB
Rss:               33600 kB
Pss:               33600 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:       120 kB
Private_Dirty:     33480 kB
Referenced:        33508 kB
Anonymous:         33600 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                240 kB
SwapPss:             240 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aeb06d000-7f2aec9c5000 rw-p 00000000 00:00 0
Size:              25952 kB
Rss:               25668 kB
Pss:               25668 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:        24 kB
Private_Dirty:     25644 kB
Referenced:        25668 kB
Anonymous:         25668 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 12 kB
SwapPss:              12 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aec9c7000-7f2aeda5c000 rw-p 00000000 00:00 0
Size:              16980 kB
Rss:               16684 kB
Pss:               16684 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:     16684 kB
Referenced:        16684 kB
Anonymous:         16684 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                148 kB
SwapPss:             148 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aeda63000-7f2aee406000 rw-p 00000000 00:00 0
Size:               9868 kB
Rss:                9764 kB
Pss:                9764 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      9764 kB
Referenced:         9764 kB
Anonymous:          9764 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aee410000-7f2aeedb3000 rw-p 00000000 00:00 0
Size:               9868 kB
Rss:                9692 kB
Pss:                9692 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         8 kB
Private_Dirty:      9684 kB
Referenced:         9692 kB
Anonymous:          9692 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                120 kB
SwapPss:             120 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aeedb4000-7f2aef095000 rw-p 00000000 00:00 0
Size:               2948 kB
Rss:                2920 kB
Pss:                2920 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      2920 kB
Referenced:         2920 kB
Anonymous:          2920 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 16 kB
SwapPss:              16 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aef09b000-7f2aef41c000 rw-p 00000000 00:00 0
Size:               3588 kB
Rss:                3492 kB
Pss:                3492 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      3492 kB
Referenced:         3492 kB
Anonymous:          3492 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 60 kB
SwapPss:              60 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aef420000-7f2aef741000 rw-p 00000000 00:00 0
Size:               3204 kB
Rss:                3104 kB
Pss:                3104 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      3104 kB
Referenced:         3104 kB
Anonymous:          3104 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 76 kB
SwapPss:              76 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7f2aef749000-7f2af24eb000 rw-p 00000000 00:00 0
Size:              46728 kB
Rss:               13584 kB
Pss:               13584 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:        96 kB
Private_Dirty:     13488 kB
Referenced:        13584 kB
Anonymous:         13584 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 72 kB
SwapPss:              72 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me ac sd
7ffe63550000-7ffe63571000 rw-p 00000000 00:00 0                          [stack]
Size:                132 kB
Rss:                  12 kB
Pss:                  12 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:        12 kB
Referenced:           12 kB
Anonymous:            12 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd wr mr mw me gd ac
7ffe635ce000-7ffe635d0000 r--p 00000000 00:00 0                          [vvar]
Size:                  8 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd mr pf io de dd sd
7ffe635d0000-7ffe635d2000 r-xp 00000000 00:00 0                          [vdso]
Size:                  8 kB
Rss:                   8 kB
Pss:                   2 kB
Shared_Clean:          8 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            8 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd ex mr mw me de sd
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Size:                  4 kB
Rss:                   0 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:            0 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
ProtectionKey:         0
VmFlags: rd ex
```

#### 3. cortex configuration
```
auth_enabled: false

server:
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
  log_level: error
  http_server_read_timeout: 1000s
  http_server_write_timeout: 1000s

distributor:
  max_recv_msg_size: 104857600
  shard_by_all_labels: false
  pool:
    health_check_ingesters: true
  remote_timeout: 300s

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:
  spread_flushes: true
  chunk_age_jitter: 0
  flush_period: 15m
  retain_period: 0s
  max_chunk_idle_time: 15m
  max_stale_chunk_idle_time: 2m
  max_chunk_age: 2h
  walconfig:
    wal_enabled: false
    recover_from_wal: false
    checkpoint_duration: 5m
    wal_dir: /mnt/storage00/cortex/wal

  lifecycler:
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /mnt/storage00/cortex/tokens
    interface_names:
      - bond0

    ring:
      kvstore:
        store: consul
        consul:
          host: 127.0.0.1:8500
      replication_factor: 3

querier:
  max_concurrent: 300
  query_ingesters_within: 999999999999

schema:
  configs:
  - from: 2019-07-29
    store: cassandra
    object_store: cassandra
    schema: v9
    index:
        prefix: index_
        period: 24h
    chunks:
        prefix: chunk_
        period: 24h

frontend_worker:
    frontend_address: 127.0.0.1:9104
    parallelism: 100
    grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600

query_range:
  split_queries_by_interval: 24h
  align_queries_with_step: true
  parallelise_shardable_queries: true
  cache_results: true
  results_cache:
    max_freshness: 1m

frontend:
    downstream_url: 'http://127.0.0.1:9003'
    log_queries_longer_than: 1s
    compress_responses: true

storage:
    cassandra:
        addresses: localhost
        keyspace: cortex
        replication_factor: 1
        timeout: 3000s
        connect_timeout: 3000s
```

Cortex uses three 252G, 48Core machines, does anyone have any ideas ?

---- 

This problem still exists when using TSDB as the back-end storage, but the Cortex in TSDB mode can be maintained for 12h and then be killed by OOM Killer.
Similar to the Chunk mode, the memory of the Ingester and Distributor of the TSDB mode continues to increase (finally stabilized at 100G+, then OOM), and after stopping Remote Write, the memory usage will not decrease.

### PR DESCRIPTION
**Pull request by storyicon**
**What this PR does**:
The purpose of this PR is to fix the memory leak of Cortex Ingester. After this PR is merged, it is expected to reduce the runtime memory of Ingester by at least 30%.

**Which issue(s) this PR fixes**:
Fixes #2665 

Although the PR code looks very simple, the principle inside is more complicated. I try to make it as easy to understand as possible. If there are errors in some parts, please correct me.
When troubleshooting the memory problem of Ingester, I simplified Ingester.Push to make it do almost nothing. Like below：
```
// Push implements client.IngesterServer
func (i *Ingester) Push(ctx context.Context, req *client.WriteRequest) (*client.WriteResponse, error) {
    defer client.ReuseSlice(req.Timeseries)
    return &client.WriteResponse{}, nil
}
```
After the above modifications, Ingester still takes up very high memory (60G+), until OOM, I think it must be a problem with `client.ReuseSlice`.

However, when I commented out the reuse of TimeSeries, the problem was solved, Ingester only took up 700M memory, and it was very stable, like the following:
```
func ReuseTimeseries(ts *TimeSeries) {
	// ts.Labels = ts.Labels[:0]
	// ts.Samples = ts.Samples[:0]
	// timeSeriesPool.Put(ts)
}
```

By looking closely at the code, I found the source of the problem. First, in `ReuseTimeseries`，
```
ts.Labels = ts.Labels[:0]
ts.Samples = ts.Samples[:0]
```
It does not release the real underlying array. We know that slice’s real structure is as follows：
```
type sliceHeader struct {
    Length        int
    Capacity      int
    ZerothElement *byte
}
```
The above operation will only change the Length in sliceHeader to 0, the underlying array still cannot be released. Secondly, you can see in the deserialization of Label:
https://github.com/cortexproject/cortex/blob/8fe97dcc707a3e774229d9fd3b20425214e0ac9b/pkg/ingester/client/timeseries.go#L205
https://github.com/cortexproject/cortex/blob/8fe97dcc707a3e774229d9fd3b20425214e0ac9b/pkg/ingester/client/timeseries.go#L232-L234
In the deserialization, the zero-copy is used. `Label.Name` and `Label.Value` refer to the original []byte, which will cause the original request body to not be released.

This may have some abstractions, I can cite such an example：

The A request body has a total of 1M []byte (I call it `RawSliceA`). After Unmarshal, `timeSeriesA0` contains 10 Labels. Due to the use of zero copy, these 10 Labels actually refer to `RawSliceA`.
After the A request is processed, `timeSeriesA0` is put into `timeSeriesPool`, and the reference to `RawSliceA` is still not canceled at this time。
The B request body has a total of 500KB []byte. After Unmarshal, `timeSeriesB0` contains 3 Labels. In Unmarshal, it takes and reuses `timeSeriesA0` from `timeSeriesPool`. At this time, `RawSliceA` was released?
No, `RawSliceA` may not be released until the B request processing is completed, and even to the next request.
The whole process is like this：
image

This example is a bit similar to：https://github.com/golang/go/issues/23199

For the problems mentioned above, I have the following thoughts:
1. I think there is no problem using zero copy like `yoloString`, because most of the bytes of `RawSlice` are describing Labels, which is cost-effective.
2. I think it is no problem to use memory pool for `timeSeries`, it can reuse `Labels` and `Samples` Slice.
3. Even though the GC will periodically clean up the Pool, a large number of consecutive requests will still cause a lot of memory to be wasted.
4. Before putting `timeSeries` into `timeSeriesPool`, must clear the `Name` and `Value` of `timeSeries.Labels` to dereference `RawSlice`.

After testing, this modification can greatly reduce the runtime memory of Ingester without introducing new problems.

**before**:
image

**after**:
image
(The illustration above was made after commenting out Push's real logic)

### CODE REVIEW

**Comment by bboreham** [comment]
May I ask how large the incoming messages are?  E.g. how many samples do you allow per `Push()` ?

File: pkg/ingester/client/timeseries.go [hunk 1]
```diff
@@ -276,6 +276,10 @@ func ReuseSlice(ts []PreallocTimeseries) {
 
 // ReuseTimeseries puts the timeseries back into a sync.Pool for reuse.
 func ReuseTimeseries(ts *TimeSeries) {
+	for i := 0; i < len(ts.Labels); i++ {
+		ts.Labels[i].Name = ""
```
Comment (bboreham) [inline pkg/ingester/client/timeseries.go:280]: Suggest `// Name and Value may point into a large gRPC buffer, so clear the reference to allow GC`

Comment (storyicon) [reply pkg/ingester/client/timeseries.go:281]: I accepted your suggestion, thanks!

**Comment by storyicon** [comment]
@bboreham In my production environment, the scrape_interval of Prometheus is `25s`, Cortex receives `53` Pushes per second on average, and each Push contains `5530` Timeseries on average, among them:

1. A single TimeSeries has up to 16 Labels and at least 1 Label
2. Each TimeSeries contains only 1 sample.

On average, the buffer for each `Push` request is `1211066byte`, of which samples occupy `88480byte` and labels occupy `1122582byte`.
At present, my cortex uses `BlockStorage`+`S3`, and it will always be OOM after running `10h`. I am committed to reducing `scrape_interval` to `10s`, and keep the memory of Cortex stable, I use three `252GB`, `48Core` linux machines, replication_factor is `2`(configuring 3 will make OOM faster).
If you can give me some suggestions, I would appreciate it.

**Comment by storyicon** [comment]
Reproducing this problem is simple, I can give this Demo:

## Test0
```
package main

import (
	"fmt"
	"runtime"
	"runtime/debug"
	"sync"
	"time"
	"unsafe"
)

var timeSeriesPool = sync.Pool{
	New: func() interface{} {
		return &TimeSeries{
			Labels: make([]Label, 0, 10),
		}
	},
}

func yoloString(buf []byte) string {
	return *((*string)(unsafe.Pointer(&buf)))
}

type TimeSeries struct {
	Labels []Label
}

type Label struct {
	Name  string
	Value string
}

func unmarshal(data []byte, labelsSize int) *TimeSeries {
	ts := timeSeriesPool.Get().(*TimeSeries)
	for i := 0; i < labelsSize; i++ {
		ts.Labels = append(ts.Labels, Label{
			Name:  yoloString(data[:5]),
			Value: yoloString(data[5:10]),
		})
	}
	return ts
}

func reuseTimeSeries(ts *TimeSeries) {
	// for i := 0; i < len(ts.Labels); i++ {
	// 	ts.Labels[i].Name = ""
	// 	ts.Labels[i].Value = ""
	// }
	ts.Labels = ts.Labels[:0]
	timeSeriesPool.Put(ts)
}

func Push(data []byte, labelSize int, withGC bool) {
	ts := unmarshal(data, labelSize)
	defer reuseTimeSeries(ts)
	if withGC {
		// Manually trigger GC
		runtime.GC()
		// Return memory to operating system
		debug.FreeOSMemory()
	}
	// Reference variables to prevent memory optimization
	fmt.Println("Push Done", ts)
}

func buildPushBuffer(size int, fillByte byte) []byte {
	data := make([]byte, size)
	for i := 0; i < len(data); i++ {
		// Fill bytes to prevent Unix memory optimization.
		// This is not needed on windows.
		data[i] = fillByte
	}
	return data
}

func main() {
         // allocate 500M memory and pass in Push
	Push(buildPushBuffer(1024*1024*500, 1), 10, false)
        // allocate 500M memory and pass in Push
	Push(buildPushBuffer(1024*1024*500, 1), 1, true)

	// sleep, view memory
	fmt.Println("sleep")
	time.Sleep(time.Hour)
}
```
Running the above code, you can see that the memory usage of the program is `1G` instead of `500M`, the principle is the same as the above picture.

## Test1
Uncomment the following code in `Test0` and re-run：
```
	// for i := 0; i < len(ts.Labels); i++ {
	// 	ts.Labels[i].Name = ""
	// 	ts.Labels[i].Value = ""
	// }
```
You can see that the memory usage is `500M` instead of `1G`, because the reference to the original buffer generated by the zero copy is cleared before it is put into `timeSeriesPool`.

## Test2
Change the following code in `Test0`
```
		ts.Labels = append(ts.Labels, Label{
			Name:  yoloString(data[:5]),
			Value: yoloString(data[5:10]),
		})
```
into：
```
		ts.Labels = append(ts.Labels, Label{
			Name:  string(data[:5]),
			Value: string(data[5:10]),
		})
```

The memory usage should be only 30M+, because no zero copy is used, the `ts` from `unmarshal` no longer refer to the original buffer, and the two `500M` buffers are cleaned up by the GC.

**Comment by bboreham** [comment]
(sorry my comments are somewhat duplicated in #2665)

I understand the behaviour in Go of the part you fixed.  What I don't understand is the gap between Go heap of 1-3GB and a RSS of 90+GB.

In my Cortex clusters RSS between 30% and 50% more than max Go heap.

**Comment by storyicon** [comment]
@pracucci I'm sorry I will provide these data later, because it is already late at night in my city.

**Comment by storyicon** [comment]
@bboreham Hello, I replied in https://github.com/cortexproject/cortex/issues/2665 about the reason for the difference in our pprof data.

**Comment by storyicon** [comment]
@pracucci  The GC gap is huge and even exceeds my expectations.

## Before Fix
image

## After Fix
image

In order to rule out other influences, I modified the Push function like this during testing:
```
func (i *Ingester) Push(ctx context.Context, req *client.WriteRequest) (*client.WriteResponse, error) {
	defer client.ReuseSlice(req.Timeseries)
	return &client.WriteResponse{}, nil
}
```

The latest release version (cd9e38d) was used in the test.
Although this optimization looks exciting, at present I cannot guarantee that Cortex will still enjoy such a large memory advantage after restoring the normal logic of the Push function,  because I guess there should be other object pools in Ingester that refer to some addresses that should be released.

**Comment by pracucci** [comment]
These charts looks something proving my gut feeling, that what you actually get is the GC running way more frequently. This explains why the "leak" is not visible in the heap, because it's all about how frequently the GC runs.

**Comment by storyicon** [comment]
@pracucci Your gut feeling is really great! Can you explain why GC just makes the number of heap objects drop, but fails to reduce ingester's memory resident? Do you think if I use ticker to manually trigger GC (Including `debug.FreeOSMemory()`）frequently, can I keep the memory at 500M instead of 50G?

**Comment by pracucci** [comment]
> @pracucci Your gut feeling is really great! Can you explain why GC just makes the number of heap objects drop, but fails to reduce ingester's memory resident? Do you think if I use ticker to manually trigger GC (Including `debug.FreeOSMemory()`）frequently, can I keep the memory at 500M instead of 50G?

I don't have an answer (I would need to further investigate it, possibly being able to reproduce it locally). Manually triggering the GC could be an experiment you can do just for testing, but if this PR fixes your issue then I would just be happy and move on 😉

**Comment by storyicon** [comment]
> > @pracucci Your gut feeling is really great! Can you explain why GC just makes the number of heap objects drop, but fails to reduce ingester's memory resident? Do you think if I use ticker to manually trigger GC (Including `debug.FreeOSMemory()`）frequently, can I keep the memory at 500M instead of 50G?
> 
> I don't have an answer (I would need to further investigate it, possibly being able to reproduce it locally). Manually triggering the GC could be an experiment you can do just for testing, but if this PR fixes your issue then I would just be happy and move on 😉

@pracucci 
These things are fascinating. I will do relevant experiments to find out. Pracucci, you are the first person to reply to me when I put forward issue under cortex project. Thank you! 😔

**Comment by bboreham** [comment]
Go has a mechanism to control how fast GC runs - the `GOGC` environment variable.
https://golang.org/pkg/runtime/debug/#SetGCPercent

Note frequent GC may chew up a lot of CPU.

**Comment by storyicon** [comment]
> Go has a mechanism to control how fast GC runs - the `GOGC` environment variable.
> https://golang.org/pkg/runtime/debug/#SetGCPercent
> 
> Note frequent GC may chew up a lot of CPU.

@bboreham 
Thanks, bboreham. I will continue to track this problem. If there is an error in my statement of principle above, I hope you can correct me. In fact, I don't care who holds the truth, but what it is.☹️

**Comment by bboreham** [comment]
>  If there is an error in my statement of principle above, I hope you can correct me. 

Sorry I don't know what this refers to.

**Comment by storyicon** [comment]
> > If there is an error in my statement of principle above, I hope you can correct me.
> 
> Sorry I don't know what this refers to.

Sorry, English is not my mother tongue. I mean what I explained in "Which issue(s) this PR fixes"

**Comment by bboreham** [comment]
Fixing the issue is fine; thank you for the PR.

My last comment referred to manually running GC, which is a totally different subject.

**Comment by storyicon** [comment]
> Fixing the issue is fine; thank you for the PR.
> 
> My last comment referred to manually running GC, which is a totally different subject.

I understand, I will continue to dive into it (includes manual triggering of GC tests), thank you!
