### PR TITLE
Expose doc for instance_interface_names

### LINKED ISSUE #3293: compactor needs a hidden config option to run
**Describe the bug**

The compactor rin needs  the undocumented `instance_interface_names` to work if you don't have a standard interface.

https://github.com/cortexproject/cortex/blob/844759ab5a88b7c04df948d3e7340c0373428168/pkg/compactor/compactor_ring.go#L27

**To Reproduce**
1. Start Cortex 1.4.0
2. /usr/local/bin/cortex-linux-amd64 -config.file=/etc/cortex/cortex-compactor.yml -target compactor

```
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.712722543Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=release-1.4, revision=23554ce02)"
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.712910934Z caller=server.go:225 http=127.0.0.1:9015 grpc=172.20.1.133:9915 msg="server listening on addresses"
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.714588696Z caller=module_service.go:58 msg=initialising module=memberlist-kv
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.714710534Z caller=module_service.go:58 msg=initialising module=compactor
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.714813171Z caller=module_service.go:58 msg=initialising module=server
Oct 07 09:36:37 X cortex[49282]: level=warn ts=2020-10-07T07:36:37.716788223Z caller=net.go:15 msg="error getting interface" inf=eth0 err="route ip+net: no such network interface"
Oct 07 09:36:37 X cortex[49282]: level=warn ts=2020-10-07T07:36:37.716993945Z caller=net.go:15 msg="error getting interface" inf=en0 err="route ip+net: no such network interface"
Oct 07 09:36:37 X cortex[49282]: level=error ts=2020-10-07T07:36:37.717085393Z caller=cortex.go:353 msg="module failed" module=compactor err="invalid service state: Failed, expected: Running, failure: unable to initialize compactor ring lifecycler: No address found for [eth0 en0]"
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.717260949Z caller=module_service.go:90 msg="module stopped" module=memberlist-kv
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.717712271Z caller=server_service.go:50 msg="server stopped"
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.718068869Z caller=module_service.go:90 msg="module stopped" module=server
Oct 07 09:36:37 X cortex[49282]: level=info ts=2020-10-07T07:36:37.718116275Z caller=cortex.go:342 msg="Cortex stopped"
Oct 07 09:36:37 X cortex[49282]: level=error ts=2020-10-07T07:36:37.718185314Z caller=log.go:149 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/Users/marco/workspace/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:388\nmain.main\n\t/Users/marco/workspace/src/github.com/cortexproject/cortex/cmd/cortex/main.go:180\nruntime.main\n\t/usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/asm_amd64.s:1373"
```

**Expected behavior**

Compactor to work or needed options to be documented.

Adding `instance_interface_names: [ens160]` to `compactor.sharding_ring` fixes that.

**Environment:**
 - Infrastructure: VM
 - Deployment tool: ansible
**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**

```
blocks_storage:
  backend: s3
  bucket_store:
    sync_dir: /data/cortex/tsdb-sync
  s3:
    access_key_id: XX
    bucket_name: prd-prometheus
    endpoint: ceph.XX
    secret_access_key: XX
  tsdb:
    dir: /data/cortex/tsdb
compactor:
  data_dir: /data/cortex/compactor
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
memberlist:
  bind_port: 8406
  join_members:
  - rbsuXX:8406
  - rbsuYY:8406
server:
  grpc_listen_address: 172.20.1.133
  grpc_listen_port: 9915
  http_listen_address: 127.0.0.1
  http_listen_port: 9015
storage:
  engine: blocks
```

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
The config documentation for `instance_interface_names` was intentionally hidden to keep it simple, but there are legit use cases where our default interfaces don't cover actual ones.

**Which issue(s) this PR fixes**:
Fixes #3293

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/compactor/compactor_ring.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ type RingConfig struct {
 
 	// Instance details
 	InstanceID             string   `yaml:"instance_id" doc:"hidden"`
-	InstanceInterfaceNames []string `yaml:"instance_interface_names" doc:"hidden"`
+	InstanceInterfaceNames []string `yaml:"instance_interface_names"`
```
Comment (pstibrany) [inline pkg/compactor/compactor_ring.go:27]: Since it was hidden until now, should we fix the name to make it consistent with flag?

(Same comment/question applies to other places this PR changes)

Comment (pracucci) [reply pkg/compactor/compactor_ring.go:27]: Good that you spot it! I've renamed the CLI flag to match the YAML config option.

File: CHANGELOG.md [hunk 2]
```diff
@@ -40,6 +40,11 @@
   - `POST <legacy-http-prefix>/push`
   - `POST /push`
   - `POST /ingester/push`
+* [CHANGE] Renamed CLI flags to configure the network interface names from which automatically detect the instance IP. Not a breaking change because these flags were non documented. #3295
```
Comment (pstibrany) [inline CHANGELOG.md:43]:
```suggestion
* [CHANGE] Renamed CLI flags to configure the network interface names from which automatically detect the instance IP. Not a breaking change because these flags were not documented. #3295
```

(or `undocumented`)

File: pkg/compactor/compactor_ring.go (hunk 1 above)
Comment (pstibrany) [reply pkg/compactor/compactor_ring.go:27]: You've trained me well :)

**Review by pstibrany — APPROVED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (roidelapluie) [reply CHANGELOG.md:43]: There were documented in -help, I was using them in tests.

Comment (pracucci) [reply CHANGELOG.md:43]: You're right. `-help` shows everything. Removing that sentence.
