### PR TITLE
Validate empty labels in push

### LINKED ISSUE #7043: PRW2 accepts empty metrics instead of rejecting them
**Describe the bug**
When using PRW2, it is possible to write a metric without labels, or at least, cortex does not return a 4xx error.

**To Reproduce**
1. Start Cortex 0e9721f
2. Send a metric without labels (part of https://github.com/prometheus/compliance/pull/182)

**Expected behavior**

Prometheus returns 400
`"invalid metric name or labels, got {}\n"`

Cortex returns 200.

### PR DESCRIPTION
**Pull request by SungJin1212**
Add label validations to Prometheus remote write 2.0

**Which issue(s) this PR fixes**:
Fixes #7043

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/util/push/push.go [hunk 1]
```diff
@@ -165,15 +167,26 @@ func setPRW2RespHeader(w http.ResponseWriter, samples, histograms, exemplars int
...
 	v1Timeseries := make([]cortexpb.PreallocTimeseries, 0, len(req.Timeseries))
 	var v1Metadata []*cortexpb.MetricMetadata
 
 	b := labels.NewScratchBuilder(0)
 	symbols := req.Symbols
 	for _, v2Ts := range req.Timeseries {
 		lbs := v2Ts.ToLabels(&b, symbols)
+		// PRW2 spec allows UTF-8.
+		// c.f. https://prometheus.io/docs/specs/prw/remote_write_spec_2_0/#series-labels
+		if !lbs.Has(labels.MetricName) || !lbs.IsValid(model.UTF8Validation) {
```
Comment (yeya24) [inline pkg/util/push/push.go]: We may need to check name validation scheme first? UTF-8 may not be enabled.
Or this validation will be applied later in distributor's push logic

**Comment by yeya24** [comment]
https://github.com/cortexproject/cortex/issues/7043#issuecomment-3399937009

I wonder if this is the right problem. I think the validation logic should apply for both v1 and v2

**Comment by SungJin1212** [comment]
@yeya24 
I added empty labels validation logic to the distributor layer.

**Comment by yeya24** [comment]
Let's update the PR title. Now this change is not specific to PRW2
