### PR TITLE
Distributor default sharding should support default 0 value.

### LINKED ISSUE #5189: setting -distributor.ingestion-tenant-shard-size to 0 throws error
**Describe the bug**
setting -distributor.ingestion-tenant-shard-size to 0 throws error . According to the documentation setting this flag to 0 should disable the shuffle sharding. However it throws validation error that value can not be 0.

**To Reproduce**

1. Set -distributor.ingestion-tenant-shard-size to 0
2. Deploy distributors

**Expected behavior**
Documentation should be clear.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

### PR DESCRIPTION
**Pull request by Kramer0x0**
There is a discrepancy between the current behavior of the system and the documented functionality regarding the setting of the ingestion_tenant_shard_size parameter.
Current Behavior

When attempting to set the -distributor.ingestion-tenant-shard-size flag to 0, the system throws an error.
Expected Behavior (As Per Documentation)

The documentation states the following:
```
# The default tenant's shard size when the shuffle-sharding strategy is used.
# Must be set both on ingesters and distributors. When this setting is specified
# in the per-tenant overrides, a value of 0 disables shuffle sharding for the
# tenant.
# CLI flag: -distributor.ingestion-tenant-shard-size
[ingestion_tenant_shard_size: <int> | default = 0]
```

According to this, setting the value to 0 should **be supported** and is intended to disable shuffle sharding for the tenant.
**Rationale for Setting the Value to 0**

The intention behind setting the ingestion_tenant_shard_size to 0 by default is to enable shuffle-sharding, while also allowing a tenant to utilize the entire ring as the shard size. This setup is crucial for overwriting settings for specific tenants who might require shuffle sharding. The issue was identified during an attempt to configure our ingesters with the zero value.

**What this PR does**:

This PR addresses the exception that is thrown, warns a customer when the combination of shuffle sharding enabled and ingestion_tenant_shard_size == 0. Also addressing the `Push()` function to check and update the ring topology accordingly. 

**Which issue(s) this PR fixes**:
Fixes #5189

Related: #5250

**Checklist**
- [X] Tests updated
- [X] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/distributor/distributor.go [hunk 1]
```diff
@@ -691,6 +695,23 @@ func (d *Distributor) Push(ctx context.Context, req *cortexpb.WriteRequest) (*co
...
+	userID, err := tenant.TenantID(ctx)
+	if err != nil {
+		return nil, err
+	}
+	//Get any overrides for the current tenant
+	limits := d.limits.GetOverridesForUser(userID)
+	//Retrieves all the current ingesters rings.
+	subRing := d.ingestersRing
+	//Determines if Shuffle Sharding is enabled and or the overrides has a Sharding Strategy of greater than 0.
+	if d.cfg.ShardingStrategy == util.ShardingStrategyShuffle && limits.IngestionTenantShardSize > 0 {
```
Comment (yeya24) [inline pkg/distributor/distributor.go:708]: This seems unnecessary. Even if you pass `limits.IngestionTenantShardSize <= 0`, `ShuffleShard` still returns the whole ring, which is the same as this behavior.

Comment (yeya24) [reply pkg/distributor/distributor.go:708]: I think we can still keep the code at L680.

File: pkg/distributor/distributor.go [hunk 2]
```diff
@@ -598,17 +614,6 @@ func (d *Distributor) Push(ctx context.Context, req *cortexpb.WriteRequest) (*co
...
-		return nil, errTooManyInflightPushRequests
-	}
-
-	if d.cfg.InstanceLimits.MaxIngestionRate > 0 {
-		if rate := d.ingestionRate.Rate(); rate >= d.cfg.InstanceLimits.MaxIngestionRate {
-			return nil, errMaxSamplesPushRateLimitReached
-		}
-	}
-
-	removeReplica := false
```
Comment (yeya24) [inline pkg/distributor/distributor.go:611]: Is this code related to this pr? It looks like it is the same as https://github.com/cortexproject/cortex/pull/5714/files

File: pkg/distributor/distributor.go [hunk 3]
```diff
@@ -178,10 +178,14 @@ func (cfg *Config) Validate(limits validation.Limits) error {
 		return errInvalidShardingStrategy
 	}
 
-	if cfg.ShardingStrategy == util.ShardingStrategyShuffle && limits.IngestionTenantShardSize <= 0 {
+	if limits.IngestionTenantShardSize < 0 {
```
Comment (yeya24) [inline pkg/distributor/distributor.go:181]:
```
if cfg.ShardingStrategy == util.ShardingStrategyShuffle && limits.IngestionTenantShardSize < 0 {
}
```

I think it is fine to have `IngestionTenantShardSize < 0` when strategy is not shuffle sharding as it is a noop.

File: pkg/distributor/distributor.go [hunk 4]
```diff
@@ -178,10 +178,14 @@ func (cfg *Config) Validate(limits validation.Limits) error {
...
 		return errInvalidTenantShardSize
 	}
 
+	if limits.IngestionTenantShardSize == 0 && cfg.ShardingStrategy == util.ShardingStrategyShuffle {
+		level.Warn(util_log.Logger).Log("msg", "identified sharding strategy: %s, with shard size of 0, this will fallback to default sharding strategy", util.ShardingStrategyShuffle)
+	}
```
Comment (yeya24) [inline pkg/distributor/distributor.go:187]: I think it is fine to skip this log.

File: pkg/distributor/distributor.go (hunk 1 above)
Comment (Kramer0x0) [reply pkg/distributor/distributor.go]: Ahh yes, I should have went further down the call stack! Sorry about that:

Future readers - what I believe @yeya24  is referring to the below block which will just return the entire ring if the size is 0. 
```go
func (r *Ring) shuffleShardWithCache(identifier string, size int, zoneStableSharding bool) ReadRing {
	// Nothing to do if the shard size is not smaller than the actual ring.
	if size <= 0 || r.InstancesCount() <= size {
		return r
}
```

File: pkg/distributor/distributor.go (hunk 2 above)
Comment (Kramer0x0) [reply pkg/distributor/distributor.go]: Yes, sorry Apple's Mirror wasn't updated with this change. Should be corrected now.

File: pkg/distributor/distributor.go (hunk 4 above)
Comment (Kramer0x0) [reply pkg/distributor/distributor.go]: Removed 👍

File: pkg/distributor/distributor.go [hunk 5]
```diff
@@ -178,7 +178,7 @@ func (cfg *Config) Validate(limits validation.Limits) error {
 		return errInvalidShardingStrategy
 	}
 
-	if cfg.ShardingStrategy == util.ShardingStrategyShuffle && limits.IngestionTenantShardSize <= 0 {
+	if cfg.ShardingStrategy == util.ShardingStrategyShuffle && limits.IngestionTenantShardSize < 0 {
 		return errInvalidTenantShardSize
```
Comment (danielblando) [inline pkg/distributor/distributor.go:182]: nit: can you update the error message `invalid tenant shard size, the value must be greater than 0`

Comment (yeya24) [reply pkg/distributor/distributor.go:182]: That's a good call.

**Review by danielblando — APPROVED** [review]
Thanks

**Review by yeya24 — APPROVED** [review]
