### PR TITLE
Fail ingestion when a flush is going on

### LINKED ISSUE #3282: Potential Prometheus memory leak in ingesters
**Describe the bug**
We encountered an issue with Ingester/Prometheus unable to recover from WAL due to `invalid block sequence: block time ranges overlap` issue. Repeatedly calling this Ingester with ingestion request results in OOM.

When an ingester service starts up, it tries to recover TSDB for all UserIds. If a TSDB failed to be recovered, [ingester will skip it and continue on](https://github.com/cortexproject/cortex/blob/012fc0b0fa2fce785388917959b1a8168d29d809/pkg/ingester/ingester_v2.go#L1103). When an ingestion request for the corrupted TSDB comes, ingester will try to create a TSDB for this UserID. Since there is already a TSDB for this user, this action will result in [Prometheus performing recovery once again](https://github.com/cortexproject/cortex/blob/012fc0b0fa2fce785388917959b1a8168d29d809/pkg/ingester/ingester_v2.go#L404). 

I noticed that for the same request, ingesters log different errors

```
level=warn ts=2020-10-01T19:36:19.800983863Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=28.647562844s err="user=some-user-id: failed to open TSDB: /data/tsdb/some-user-id: invalid block sequence: block time ranges overlap: [mint: 1601488821086, maxt: 1601490567894, range: 29m6s, blocks: 2]: <ulid: 01EKG4DJNVRS9KSPQZHVHKD07G, mint: 1601481600000, maxt: 1601490567894, range: 2h29m27s>, <ulid: 01EKGQHG7FP40NRB4SA0GFAV4E, mint: 1601488821086, maxt: 1601496000000, range: 1h59m38s>" msg="gRPC\n"
```

```
level=warn ts=2020-10-01T19:15:41.737350414Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=13m46.278392928s err="user=some-user-id: failed to open TSDB: /data/tsdb/some-user-id: mmap files, file: /data/tsdb/some-user-id/chunks_head/000036: mmap: cannot allocate memory" msg="gRPC\n
```

I see the same chunk-head is memory-mapped about 200 times. I also saw that an ingester is able to handle about 200 requests for this corrupted TSDB before going OOM. I suspect Promethues is memory-mapping files during WAL replay. When Prometheus fails, this mmap is not cleaned up.

```
/ # sysctl vm.max_map_count
vm.max_map_count = 65530

/ # pmap 1 | wc -l
65523
```

```
/ # pmap 1 | grep /data/tsdb/some-user-id/chunks_head/000036 | wc -l
236
```

**To Reproduce**
1. Start Cortex (v1.4.0-rc.1)
2. Have a corrupted TSDB in ingester
3. Perform write operations for the corrupted TSDB
4. Ingester goes OOM

**Expected behavior**
Ingester should not go OOM

**Environment:**
 - Infrastructure: AWS EKS
 - Deployment tool: helm

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does**:

Fails a push request with a 5xx when there is an ongoing flush. This is according to the idea proposed in this comment https://github.com/cortexproject/cortex/issues/3282#issuecomment-714285039

**Which issue(s) this PR fixes**:
Fixes #3282 #3348

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — COMMENTED** [review]
Thanks @codesome about this! We had an offline discussion about a race condition. Ganesh mentioned he will work on this tomorrow. Thanks!

File: pkg/ingester/ingester_v2.go [hunk 1]
```diff
@@ -93,6 +97,16 @@ func (u *userTSDB) Compact() error {
 
 // compactHead compacts the Head block at specified block durations avoiding a single huge block.
 func (u *userTSDB) compactHead(blockDuration int64) error {
+	u.forcedCompactionInProgressMtx.Lock()
+	u.forcedCompactionInProgress = true
+	u.forcedCompactionInProgressMtx.Unlock()
+	defer func() {
+		u.forcedCompactionInProgress = false
```
Comment (pracucci) [inline pkg/ingester/ingester_v2.go:104]: You need to lock around this

**Review by pracucci — APPROVED** [review]
LGTM, but with a little fix, thanks!

File: pkg/ingester/ingester_v2.go (hunk 1 above)
Comment (codesome) [reply pkg/ingester/ingester_v2.go:104]: Instead of lock, what about using an atomic variable? Both would be fine actually.

Comment (codesome) [reply pkg/ingester/ingester_v2.go:105]: Added the lock

File: pkg/ingester/ingester_v2_test.go [hunk 2]
```diff
@@ -2422,3 +2422,39 @@ func TestIngesterNotDeleteUnshippedBlocks(t *testing.T) {
 		require.NotEqual(t, b.Meta().ULID, newBlocks2[1].Meta().ULID)
 	}
 }
+
+func TestIngesterPushErrorDuringForcedCompaction(t *testing.T) {
+	i, cleanup, err := newIngesterMockWithTSDBStorage(defaultIngesterTestConfig(), nil)
+	require.NoError(t, err)
+	t.Cleanup(cleanup)
```
Comment (ranton256) [inline pkg/ingester/ingester_v2_test.go:2429]: I think ideally it would be good to also add a test that verifies compactHead waits on no pushes to be in flight and locks the muutex.

**Comment by pracucci** [comment]
@pstibrany Me and @codesome are discussion a potentially better way to handle this. Please don't merge it you approve it.

File: pkg/ingester/ingester_v2.go [hunk 3]
```diff
@@ -54,6 +54,10 @@ type userTSDB struct {
 	seriesInMetric *metricCounter
 	limiter        *Limiter
 
+	forcedCompactionInProgress    bool
+	forcedCompactionInProgressMtx sync.RWMutex
+	pushesInFlight                sync.WaitGroup
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:59]: Mutex is typically on top of the block of fields that it "protects".

**Review by pstibrany — APPROVED** [review]
LGTM, thanks Ganesh!

**Comment by pracucci** [comment]
> @pstibrany Me and @codesome are discussion a potentially better way to handle this. Please don't merge it you approve it.

@pstibrany Ignore this. After further discussion, Ganesh has no bandwidth to experiment alternative solutions (eg. disable blocks compaction at all in TSDB and enable overlapping blocks in TSB, making sure query performances don't degrade significantly on overlapping blocks), so I think we can get this PR in and then we may reconsider this approach if/when Ganesh will have bandwidth.

_So we can merge if you approve, but let's wait for Ganesh adding the test suggested by Richard first._

File: pkg/ingester/ingester_v2_test.go (hunk 2 above)
Comment (codesome) [reply pkg/ingester/ingester_v2_test.go:2429]: I tried figuring out possible ways to test this, but since it uses a `sync.WaitGroup` for the in-flight requests and all the operations are relatively quick, I am not sure how to deterministically test for no in-flight requests. Do you have any ideas?

Comment (pstibrany) [reply pkg/ingester/ingester_v2_test.go:2429]: One possibility is to call `acquireAppendLock` directly from the test, then call compaction, verify that it updated bool hasn't started compaction, and then call `releaseAppendLock` to simulate finished push.

Verification of compaction could be done via TSDB metrics, or Head minT.

Comment (codesome) [reply pkg/ingester/ingester_v2_test.go:2429]: Nice one, I have added a test with that logic.

File: pkg/ingester/ingester_v2_test.go [hunk 4]
```diff
@@ -2422,3 +2422,96 @@ func TestIngesterNotDeleteUnshippedBlocks(t *testing.T) {
...
+
+	require.NoError(t, services.StartAndAwaitRunning(context.Background(), i))
+	t.Cleanup(func() {
+		_ = services.StopAndAwaitTerminated(context.Background(), i)
+	})
+
+	// Wait until it's ACTIVE
+	test.Poll(t, 10*time.Millisecond, ring.ACTIVE, func() interface{} {
```
Comment (pracucci) [inline pkg/ingester/ingester_v2_test.go:2474]: The 10millis is the timeout, not the poll frequency. Because of this, value should be higher. I would suggest at least 1s.

_This comment applies to the other test too._

File: pkg/ingester/ingester_v2_test.go [hunk 5]
```diff
@@ -2422,3 +2422,96 @@ func TestIngesterNotDeleteUnshippedBlocks(t *testing.T) {
...
+	require.NoError(t, testutil.GatherAndCompare(registry, strings.NewReader(`
+		# HELP cortex_ingester_tsdb_compactions_total Total number of TSDB compactions that were executed.
+		# TYPE cortex_ingester_tsdb_compactions_total counter
+		cortex_ingester_tsdb_compactions_total 0
+	`), "cortex_ingester_tsdb_compactions_total"))
+
+	// No requests in flight after this.
+	db.releaseAppendLock()
+
+	// Let's wait for a moment for flush to finish, and then verify.
```
Comment (pracucci) [inline pkg/ingester/ingester_v2_test.go:2503]:
```suggestion
	// Let's wait until all head series have been flushed.
```

**Review by pracucci — APPROVED** [review]
Very good job. LGTM, modulo a couple of nits. Thanks!

File: pkg/ingester/ingester_v2_test.go [hunk 6]
```diff
@@ -2422,3 +2422,96 @@ func TestIngesterNotDeleteUnshippedBlocks(t *testing.T) {
...
+	})
+
+	// Push a sample, it should succeed.
+	pushSingleSample(t, i)
+
+	// We mock a flushing by setting the boolean.
+	db := i.getTSDB(userID)
+	require.NotNil(t, db)
+	require.False(t, db.forcedCompactionInProgress)
+	db.forcedCompactionInProgress = true
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2_test.go:2448]: To avoid -race reports, I think we should use mutex around the check and setting.

File: pkg/ingester/ingester_v2_test.go [hunk 7]
```diff
@@ -2422,3 +2422,96 @@ func TestIngesterNotDeleteUnshippedBlocks(t *testing.T) {
...
+
+	// Ingestion should fail with a 503.
+	req, _, _ := mockWriteRequest(labels.Labels{{Name: labels.MetricName, Value: "test"}}, 0, util.TimeToMillis(time.Now()))
+	ctx := user.InjectOrgID(context.Background(), userID)
+	_, err = i.v2Push(ctx, req)
+	require.Equal(t, httpgrpc.Errorf(http.StatusServiceUnavailable, wrapWithUser(errors.New("forced compaction in progress"), userID).Error()), err)
+
+	// Ingestion is successful after a flush.
+	require.True(t, db.forcedCompactionInProgress)
+	db.forcedCompactionInProgress = false
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2_test.go:2458]: To avoid -race reports, I think we should use mutex around the check and setting the value.

**Review by pstibrany — APPROVED** [review]
Thanks. I think there may be race errors in the test, but otherwise LGTM.
