### PR TITLE
Return data fetched from a subset of store-gateways instead of returning error if a single store-gateway fails

### LINKED ISSUE #4529: Unable to complete query with a single unavailable store-gateway, with shuffle-sharding and zone-awareness
**Describe the bug**
Queriers do not seem to gracefully handle store-gateway failure, even with zone-awareness, and replication.

I have 3 different store-gateways, each in different AZs, and a replication factor of 3. If queriers loses network connection to store-gateway, or store-gateway fails to response due to any failure, queriers will respond with 5xx.

I'm wondering if this is the expected failure mode, or a misconfiguration on my side.

in https://github.com/cortexproject/cortex/blob/464c4243311eb727395faa0bd2a5ea5f75965250/pkg/querier/blocks_store_queryable.go#L694 , it seems like if we fail to query from any store-gateway, we'll fail the call, even if we have successfully gathered blocks from other store-gateways. Since our replication factor is 3, I expect querier to indeed query from all store-gateways, but a single store-gateway failure should not result in 5xx on query.

if we are failing a query because a single store-gateway failed, can we instead return the blocks that were queried, and have `queryWithConsistencyCheck` https://github.com/cortexproject/cortex/blob/464c4243311eb727395faa0bd2a5ea5f75965250/pkg/querier/blocks_store_queryable.go#L503 reattempt the missing blocks?

**To Reproduce**
1. Start Cortex (3291733c24b77f666dec7a6b632eec285abef44c)
2. Configure store-gateway with shuffle-sharding and zone-awareness

```
store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 3
    zone_awareness_enabled: true
    instance_availability_zone: AZ
```

3. scale up store-gateway to 3 pods
4. cut connection between one of the store-gateways and all queriers
5. make a query
6. query fails with the following error

```
{"status":"error","errorType":"internal","error":"expanding series: failed to fetch series from IP:Port: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp IP:Port: i/o timeout""}
```

**Expected behavior**
I expect queries to succeed instead of failing, since store-gateay is zone-aware, and that the data should be replicated to 3 instances. Any single store-gateway failure shouldn't fail the query.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm
 - AZs: 3 availability zones
 - Number of store-gateway: 3

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**
* I used chaos-mesh to help with simulating network failure

### PR DESCRIPTION
**Pull request by roystchiang**
**What this PR does**:

Previously, if a single store-gateway fails to return data, the whole function fails. This causes queries to fail without reattempting other available store-gateways.

Now, the function responsible for fetching data returns whatever was retrieved, and relies on the caller to determine whether all the necessary blocks were gathered.

**Which issue(s) this PR fixes**:
Fixes #4529 

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by alanprot** [comment]
Hi,
Is it possible to take a look on this? This seems a very important improvement

File: pkg/querier/blocks_store_queryable.go [hunk 1]
```diff
@@ -654,12 +659,14 @@ func (q *blocksStoreQuerier) fetchSeriesFromStores(
 				if h := resp.GetHints(); h != nil {
 					hints := hintspb.SeriesResponseHints{}
 					if err := types.UnmarshalAny(h, &hints); err != nil {
-						return errors.Wrapf(err, "failed to unmarshal series hints from %s", c.RemoteAddress())
+						level.Warn(spanLog).Log("err", errors.Wrapf(err, "failed to unmarshal series hints from %s", c.RemoteAddress()))
```
Comment (alanprot) [inline pkg/querier/blocks_store_queryable.go:662]: Does make sense to keep the change smaller for now and just ignore the network errors on [line](https://github.com/cortexproject/cortex/pull/4532/files#diff-5840d289b3ce21e878907eb354057ff9b0659d9dfd826112ea8ded6db06b1022R625) and [line](https://github.com/cortexproject/cortex/pull/4532/files#diff-5840d289b3ce21e878907eb354057ff9b0659d9dfd826112ea8ded6db06b1022R819)?

File: pkg/querier/blocks_store_queryable.go [hunk 2]
```diff
@@ -590,6 +590,9 @@ func (q *blocksStoreQuerier) fetchSeriesFromStores(
 			// TODO(goutham): we should ideally be passing the hints down to the storage layer
 			// and let the TSDB return us data with no chunks as in prometheus#8050.
 			// But this is an acceptable workaround for now.
+
+			// Only fail the function if we have validation error. We should return blocks that were successfully
```
Comment (harry671003) [inline pkg/querier/blocks_store_queryable.go:594]: We should also fail the function when store-gateways return a limit error. It'll be good to avoid unnecessary retries in that case.

**Comment by alanprot** [comment]
Nice! LGTM

**Review by alanprot — APPROVED** [review]

File: pkg/querier/blocks_store_queryable.go [hunk 3]
```diff
@@ -595,6 +602,10 @@ func (q *blocksStoreQuerier) fetchSeriesFromStores(
 
 			stream, err := c.Series(gCtx, req)
 			if err != nil {
+				if isRetryableError(err) {
+					level.Warn(spanLog).Log("err", errors.Wrapf(err, "failed to fetch series from %s", c.RemoteAddress()))
```
Comment (alvinlin123) [inline pkg/querier/blocks_store_queryable.go:606]: Can we make it clear that this is a retriable error in the log message? Something like "failed to fetch series from %s due to retriable error".

**Review by alvinlin123 — APPROVED** [review]

**Review by alvinlin123 — APPROVED** [review]
