### PR TITLE
Split incoming requests by day, run them in parallel, and cache query results.

### LINKED ISSUE #266: 500s while querying longish ranges
I was just trying to get a graph of our frontend's QPS over the last week using the data we have in Cortex. I could get as far as 2 days, but even then, Grafana would sometimes render an error page. On 7 days, it consistently errors.

Looking at the Cortex logs for the querier service, I see:

```
time="2017-02-06T14:09:14Z" level=warning msg="Error fetching from cache: read tcp 10.244.254.146:52292->10.244.229.94:11211: i/o timeout" source="chunk_store.go:469"
time="2017-02-06T14:09:23Z" level=error msg="Error in MergeQuerier.QueryRange: InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: 8CED988DD7ED850A" source="querier.go:130"
```

and 

```
time="2017-02-06T14:07:08Z" level=warning msg="Error fetching from cache: read tcp 10.244.228.139:42174->10.244.253.92:11211: i/o timeout" source="chunk_store.go:469"
time="2017-02-06T14:07:28Z" level=error msg="Error in MergeQuerier.QueryRange: RequestError: send request failed\ncaused by: Get https://weaveworks-prod-chunks.s3.amazonaws.com/2/15428021661599280118%3A1486162592195%3A1486170002195: http: server closed idle connection" source="querier.go:130"
time="2017-02-06T14:07:28Z" level=error msg="Error in MergeQuerier.QueryRange: RequestError: send request failed\ncaused by: Get https://weaveworks-prod-chunks.s3.amazonaws.com/2/12619149369118128877%3A1486247414537%3A1486262234537: EOF" source="querier.go:130"
```

The error grafana sees looks like:

```
{
  "status": "error",
  "errorType": "execution",
  "error": "InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: 0BA1F8D00B3A2DDC",
  "message": "InternalError: We encountered an internal error. Please try again.\n\tstatus code: 500, request id: 0BA1F8D00B3A2DDC"
}
```

I guess there are two possible implications of this behaviour:
* maybe we should do some sort of more sophisticated error handling on reads (e.g. retries)
* maybe we need to provide special logic for longer range queries with more data in order to make them perform reasonably

### LINKED ISSUE #963: Parallelise queries across "workers" by time range, for long queries
Now we have the query frontend, we should split queries than span multiple days into multiple queries and run them in parallel.

Special care will need to be take around handling vectors that span multiple days.

### LINKED ISSUE #977: Trickster style query results caching in query-frontend
Repeated large queries are can quickly "gum up" a Cortex cluster, as we limit the number of concurrent queries.  The idea here is to cache query results and when the same query comes in with an overlapping time range, only query for the delta and merge the results.

We probably want to keep the cache externally, as the results can be long lived.

Challenges are start/end and step alignment - Grafana 5.2(?) does this now, but I suspect a bunch of users aren't running an up to date version yet.  We could align start & end to the step in the frontend, but this runs into discussions about how we shouldn't mutate the query...

Finally, lets see if we can vendor / re use trickster code to achieve this - I've got no appetite for reimplementation.

### PR DESCRIPTION
**Pull request by tomwilkie**
~Includes #995~, fixes #977, fixes #963, fixes #266

Continuation of the work proposed in https://docs.google.com/document/d/1lsvSkv0tiAMPQv-V8vI2LZ8f4i9JuTRsuPI_i-XcAqY/edit?usp=drive_web&ouid=103586900408483314805.

- Generic code to parse incoming query_range requests, mutate them and round trip them.
- Align incoming queries with their step to make the results more cachable.
- Split queries along day boundaries, modulo step.
- Run queries in parallel and combine their results.
- Cache query results by (userid, promql query, step, day).
- Work out intersection of query and cached result and only query for difference.

### CODE REVIEW

File: pkg/querier/frontend/query_range_test.go [hunk 1]
```diff
@@ -0,0 +1,248 @@
...
+			expected: &apiResponse{
+				Status: statusSuccess,
+				Data: queryRangeResponse{
+					ResultType: model.ValMatrix,
+					Result:     model.Matrix{},
+				},
+			},
+		},
+
+		// Multiple empty responses shouldn't panic.
```
Comment (csmarchbanks) [inline pkg/querier/frontend/query_range_test.go]: These responses don't look empty

File: pkg/querier/frontend/results_cache_test.go [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+						Timestamp: 60,
+						Value:     60,
+					},
+				},
+			},
+		},
+	},
+}
+
+func TestParititon(t *testing.T) {
```
Comment (csmarchbanks) [inline pkg/querier/frontend/results_cache_test.go]: Parititon -> Partition

File: pkg/querier/frontend/frontend.go [hunk 3]
```diff
@@ -50,20 +50,28 @@ var (
...
+	resultsCacheConfig
 }
 
 // RegisterFlags adds the flags required to config this to the given FlagSet.
 func (cfg *Config) RegisterFlags(f *flag.FlagSet) {
 	f.IntVar(&cfg.MaxOutstandingPerTenant, "querier.max-outstanding-requests-per-tenant", 100, "Maximum number of outstanding requests per tenant per frontend; requests beyond this error with HTTP 429.")
-	f.IntVar(&cfg.MaxRetries, "querier.max-retries-per-request", 5, "Maximum number of retries for a single request; beyon this, the downstream error is returned.")
+	f.IntVar(&cfg.MaxRetries, "querier.max-retries-per-request", 5, "Maximum number of retries for a single request; beyond this, the downstream error is returned.")
+	f.BoolVar(&cfg.SplitQueriesByDay, "querier.split-queries-by-day", false, "Split queries by day and execute in parallel.")
+	f.BoolVar(&cfg.AlingQueriesWithStep, "querier.align-querier-with-step", false, "Mutate incoming queries to align their start and end with their step.")
```
[the remark this answers is not in the document]
Comment (tomwilkie) [reply pkg/querier/frontend/frontend.go]: The main criticism I've heard against trickster is that it mutates the request.  Also, we've put the step alignment into Grafana now.  So I wanted to make this optional as I think it shouldn't be necessary in some cases.  Its a niche case, for sure.

**Comment by tomwilkie** [comment]
> Would you mind creating some docs for the new flags/behavior?

Done!

File: Gopkg.toml [hunk 4]
```diff
@@ -6,6 +6,18 @@
   name = "github.com/aws/aws-sdk-go"
   version = "v1.10.8"
 
+[[constraint]]
```
Comment (csmarchbanks) [inline Gopkg.toml]: Are these new constraints necessary? Or were they just needed for when you were pointing to a branch?

File: pkg/chunk/cache/mock.go [hunk 5]
```diff
@@ -0,0 +1,45 @@
+package cache
+
+import (
+	"context"
+	"sync"
+)
+
+type mockCache struct {
```
Comment (csmarchbanks) [inline pkg/chunk/cache/mock.go]: Could just call this an in memory cache instead of specifically a mock since it has real functionality.

Though if we are making sure no one uses it in the future, maybe mock is best.

**Comment by tomwilkie** [comment]
> Is the Check endpoint on an ingester still going to work? Seems like client.RegisterIngesterServer will no longer register the Check method, so another register will need to be added to cmd/ingester/main.go?

Good catch!  I had fixed but forgot to push...

File: Gopkg.toml (hunk 4 above)
Comment (tomwilkie) [reply Gopkg.toml]: I needed them to get dep to successfully find a solution, but now it has, I don't seem to need them.  Removed.

File: pkg/chunk/cache/mock.go (hunk 5 above)
Comment (tomwilkie) [reply pkg/chunk/cache/mock.go]: It currently doesn't ever remove entries, so best only used in tests.  The FIFOCache is for inmemory usage.

Comment (csmarchbanks) [reply pkg/chunk/cache/mock.go]: 👍

**Comment by tomwilkie** [comment]
BTW we've deployed this in production and it makes a _huge_ difference to query performance.

File: Gopkg.toml (hunk 4 above)
Comment (csmarchbanks) [reply Gopkg.toml]: Looks like weaveworks/common is still new and unneeded

**Comment by csmarchbanks** [comment]
One last thing to remove in Gopkg.toml, then this LGTM

**Comment by tomwilkie** [comment]
Thanks!
