### PR TITLE
Fix ruler query failure reporting

### LINKED ISSUE #4333: Ruler doesn't track internal errors vs user errors correctly
Recent PR https://github.com/cortexproject/cortex/pull/4281 has introduced new metrics for tracking errors from ruler. Idea was that these failure metrics will only be incremented for queries that would normally result in 500 errors.

However this doesn't quite work. There is a class of errors that querier would return 422 for, but ruler still treats as internal errors. Examples include a rule that ends with `multiple matches for labels: many-to-one matching must be explicit (group_left/group_right)` errors, or a rule like `label_replace(metric, "foo", "$1", "service", "[")` with invalid regex `"["`.

Why do these return 422, but ruler doesn't recognize them as user-errors? Ruler uses `querier.TranslateToPromqlAPIError` to translate errors to PromQL errors. This function was designed to be used by querier, for returning errors from `storage.Queryable` implementation that match errors expected by Prometheus API library.

However in case of above mentioned class of errors, they don't "go" through the storage layer, but are generated by PromQL engine itself. As such, these errors are internal, but Prometheus API layer can translate them to proper status codes. Unfortunately Cortex ruler doesn't use Prometheus API library to run the queries, and cannot currently do type assertions on these internal Prometheus errors.

(By Prometheus API library/layer I mean `github.com/prometheus/prometheus/web/api/v1` package that implements HTTP API in Prometheus.)

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR fixes problem described in issue https://github.com/cortexproject/cortex/issues/4333. It does so by wrapping errors returned by supplied `Queryable` into special wrapper, that is then recognized and unwrapped by `MetricsQueryFunc`. This allows "failures" metric to be updated only if error was actually caused by internal Cortex error, and not by PromQL engine failure during evaluation (this fixes #4333), or by hitting limits.

This PR also adds integration test to check for these scenarios.

**Which issue(s) this PR fixes**:
Fixes https://github.com/cortexproject/cortex/issues/4333

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ruler/compat.go [hunk 1]
```diff
@@ -149,16 +149,29 @@ func MetricsQueryFunc(qf rules.QueryFunc, queries, failedQueries prometheus.Coun
...
-		// It returns promql.ErrStorage, if error should be reported back as 500.
-		// Other errors it returns are either for canceled or timed-out queriers (we're not reporting those as failures),
-		// or various user-errors (limits, duplicate samples, etc. ... also not failures).
-		//
-		// All errors will still be counted towards "evaluation failures" metrics and logged by Prometheus Ruler,
-		// but we only want internal errors here.
-		if _, ok := querier.TranslateToPromqlAPIError(err).(promql.ErrStorage); ok {
-			failedQueries.Inc()
+		// We only care about errors returned by underlying Queryable. Errors returned by PromQL engine are "user-errors",
+		// and not interesting here.
```
Comment (pracucci) [inline pkg/ruler/compat.go:154]: Is this true? For example, if it fails decoding a chunk while iterating seriesset, then it's an underlying error but the error didn't directly come from the `Queryable`.

What's the downside if we remove the check on `QueryableError` at all?

**Review by pracucci — APPROVED** [review]
Very good job! This stuff is tricky, but makes sense to me. I left a question.

File: pkg/ruler/compat.go (hunk 1 above)
Comment (pstibrany) [reply pkg/ruler/compat.go:154]: Discussed offline. Decoding a chunk is an edge case that is not covered by current implementation. To fix that, we will wrap returned Series and ChunkSeries (from SeriesSet and ChunkSeriesSet), and translate errors returned by their iterators as well.

Comment (pstibrany) [reply pkg/ruler/compat.go:154]: > Discussed offline. Decoding a chunk is an edge case that is not covered by current implementation. To fix that, we will wrap returned Series and ChunkSeries (from SeriesSet and ChunkSeriesSet), and translate errors returned by their iterators as well.

It would be possible to detect errors that occur during iteration of chunks or samples and treat them in the same way as other errors from Queryable, however benchmarks show that performance penalty for wrapping Series/ChunkSeries and their iterators is too big ([~15% more cpu time](https://gist.githubusercontent.com/pstibrany/4ad7e5debec6fe67d51c355aacc52a6e/raw/dcf0620aae0a2f64963d09dfc0848bfe7e86fa52/gistfile2.txt)). Therefore we have decided to not cover this case.

Comment (pracucci) [reply pkg/ruler/compat.go:154]: ☝️  Agree. Thanks for the investigation!
