### PR TITLE
AwaitHealthy now returns more descriptive error message

### LINKED ISSUE #3124: Ruler fails to start without helpful logs
This is very similar to https://github.com/cortexproject/cortex/issues/2991. In this case, it's the ruler that's failing to start:

```
level=info ts=2020-09-03T01:18:10.009762812Z caller=main.go:162 msg="Starting Cortex" version="(version=1.3.0, branch=HEAD, revision=90cf57435)"
level=info ts=2020-09-03T01:18:10.009938816Z caller=server.go:194 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-09-03T01:18:10.014732218Z caller=memcached.go:47 msg="created memcached cache"
level=warn ts=2020-09-03T01:18:10.014984347Z caller=experimental.go:19 msg="experimental feature in use" feature="Blocks storage engine"
level=info ts=2020-09-03T01:18:10.015787248Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2020-09-03T01:18:10.015857766Z caller=module_service.go:58 msg=initialising module=store-queryable
level=info ts=2020-09-03T01:18:10.015878462Z caller=module_service.go:58 msg=initialising module=runtime-config
level=info ts=2020-09-03T01:18:10.016453162Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2020-09-03T01:18:10.01692631Z caller=module_service.go:58 msg=initialising module=ring
level=info ts=2020-09-03T01:18:10.017106419Z caller=module_service.go:58 msg=initialising module=distributor
level=info ts=2020-09-03T01:18:10.11931313Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=101.319391ms cached=178 returned=82 partial=0
level=info ts=2020-09-03T01:18:11.836562804Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=65.240933ms cached=178 returned=82 partial=0
level=info ts=2020-09-03T01:18:15.53879203Z caller=fetcher.go:453 org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=63.360277ms cached=178 returned=82 partial=0
level=error ts=2020-09-03T01:18:15.548938974Z caller=cortex.go:319 msg="module failed" module=store-queryable err="invalid service state: Failed, expected: Running, failure: unable to start blocks storage queryable subservices: not healthy"
level=error ts=2020-09-03T01:18:15.548999735Z caller=cortex.go:319 msg="module failed" module=ruler err="failed to start ruler, because it depends on module store-queryable, which has failed: context canceled"
level=error ts=2020-09-03T01:18:15.549008571Z caller=client.go:198 msg="error while rate-limiting" key=store-gateway err="context canceled"
level=info ts=2020-09-03T01:18:15.549063192Z caller=module_service.go:90 msg="module stopped" module=distributor
level=error ts=2020-09-03T01:18:15.549095769Z caller=client.go:198 msg="error while rate-limiting" key=ring err="context canceled"
level=info ts=2020-09-03T01:18:15.549115661Z caller=module_service.go:90 msg="module stopped" module=ring
level=info ts=2020-09-03T01:18:15.54913489Z caller=module_service.go:90 msg="module stopped" module=runtime-config
level=info ts=2020-09-03T01:18:15.549158497Z caller=module_service.go:90 msg="module stopped" module=memberlist-kv
level=info ts=2020-09-03T01:18:15.549250071Z caller=server_service.go:50 msg="server stopped"
level=info ts=2020-09-03T01:18:15.549264317Z caller=module_service.go:90 msg="module stopped" module=server
level=info ts=2020-09-03T01:18:15.549274603Z caller=cortex.go:308 msg="Cortex stopped"
level=error ts=2020-09-03T01:18:15.549319793Z caller=log.go:143 msg="error running cortex" err="failed services\ngithub.com/cortexproject/cortex/pkg/cortex.(*Cortex).Run\n\t/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:354\nmain.main\n\t/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:164\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
```

We're running cortex v.1.3.0. Here's the ruler's config:
```
      -auth.enabled=false
      -consul.hostname=consul.cortex-tsdb.svc.cluster.local:8500
      -distributor.health-check-ingesters=true
      -distributor.replication-factor=3
      -distributor.shard-by-all-labels=true
      -dynamodb.api-limit=10
      -dynamodb.url=https://us-west-2
      -experimental.blocks-storage.bucket-store.ignore-deletion-marks-delay=1h
      -experimental.blocks-storage.bucket-store.metadata-cache.backend=memcached
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+memcached-metadata.cortex-tsdb.svc.cluster.local:11211
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.max-async-buffer-size=25000
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.max-async-concurrency=50
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.max-get-multi-batch-size=100
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.max-item-size=1048576
      -experimental.blocks-storage.bucket-store.metadata-cache.memcached.timeout=200ms
      -experimental.blocks-storage.bucket-store.sync-dir=/data/tsdb
      -experimental.blocks-storage.s3.bucket-name=robinhood-cortex-dev-tsdb
      -experimental.blocks-storage.s3.endpoint=s3.us-west-2.amazonaws.com
      -experimental.blocks-storage.tsdb.block-ranges-period=2h
      -experimental.blocks-storage.tsdb.dir=/data/tsdb
      -experimental.blocks-storage.tsdb.retention-period=96h
      -experimental.blocks-storage.tsdb.ship-interval=1m
      -experimental.ruler.enable-api=true
      -experimental.store-gateway.replication-factor=3
      -experimental.store-gateway.sharding-enabled=true
      -experimental.store-gateway.sharding-ring.consul.hostname=consul.cortex-tsdb.svc.cluster.local:8500
      -experimental.store-gateway.sharding-ring.prefix=
      -experimental.store-gateway.sharding-ring.store=consul
      -limits.per-user-override-config=/etc/cortex/overrides.yaml
      -log.level=debug
      -querier.query-ingesters-within=13h
      -querier.query-store-after=12h
      -ring.heartbeat-timeout=10m
      -ring.prefix=
      -ruler.alertmanager-url=http://alertmanager.cortex-tsdb.svc.cluster.local/alertmanager
      -ruler.enable-sharding=true
      -ruler.ring.consul.hostname=consul.cortex-tsdb.svc.cluster.local:8500
      -ruler.rule-path=/etc/cortex/ruler/rules
      -ruler.storage.local.directory=/etc/cortex/ruler
      -ruler.storage.type=local
      -s3.url=https://us-west-2/robinhood-cortex-dev-tsdb
      -schema-config-file=/etc/cortex/schema/config.yaml
      -store.cardinality-limit=1000000
      -store.engine=blocks
      -store.max-query-length=744h
      -target=ruler
```

One of the diagnoses from the previous issue was an unhealthy consul cluster, which is not a problem we appear to be having since all the other components are healthy.

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR modifies `(*services.Manager).AwaitHealthy` method to return more descriptive error message, including the failure cases of failed services.

**Which issue(s) this PR fixes**:
Fixes #3124 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/util/services/manager_test.go [hunk 1]
```diff
@@ -177,7 +177,9 @@ func TestManagerThatFailsToStart(t *testing.T) {
 	require.Equal(t, states, map[State][]Service{New: {s1, s2, s3}})
 
 	require.NoError(t, m.StartAsync(context.Background()))
-	require.Error(t, m.AwaitHealthy(context.Background())) // will never get healthy, since one service fails to start
+	err = m.AwaitHealthy(context.Background())
+	require.Error(t, err) // will never get healthy, since one service fails to start
+	require.EqualError(t, err, "not healthy, 0 terminated, 1 failed: [failed to start]")
```
Comment (codesome) [inline pkg/util/services/manager_test.go:182]: I am wondering if `failed to start` is descriptive enough to know whats the matter. But is the scope of this PR just to return the failure cases that it received?

Comment (codesome) [reply pkg/util/services/manager_test.go:182]: Oh I see, `failed to start` comes from the mock service

Comment (codesome) [reply pkg/util/services/manager_test.go:182]: All good here :)

**Review by codesome — APPROVED** [review]

**Review by pracucci — APPROVED** [review]
LGTM, thanks!
