### PR TITLE
Do not close idle TSDBs while blocks shipping is in progress

### LINKED ISSUE #3620: ingester_v2 reporting quite a bit of "failed to delete idle TSDB" error
**Describe the bug**
We are seeing error message like 

```
level=error ts=2020-12-15T21:33:44.395830698Z caller=ingester_v2.go:1623 msg="failed to delete idle TSDB" user=some-user-id err="unlinkat /data/tsdb/some-user-id: directory not empty"
```
We are using [this commit](https://github.com/cortexproject/cortex/tree/af9e20c54ee97f409008f3e86541c5dfa5038e22)

**To Reproduce**
I am not sure

**Expected behavior**

**Environment:**
 - Infrastructure: EKS 
 - Deployment tool: Helm

**Storage Engine**
- [ X ] Blocks
- [ ] Chunks

**Additional Context**
The error happens during a call to `os.RemoveAll()` call, research shows that `RemoveAll()` might return "directory not empty" error if file are created under the directory while the removal process is on going. So I am wondering if there is any background process in ingester that maybe interfering with the local TSDB deletion process?

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
In this PR I'm attempting one possible solution (there are multiples) to fix the race condition described in #3620.

**Which issue(s) this PR fixes**:
Fixes #3620

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ingester/ingester_v2.go [hunk 1]
```diff
@@ -1501,7 +1503,14 @@ func (i *Ingester) shipBlocks(ctx context.Context) {
 			}
 		}
 
-		// Run the shipper's Sync() to upload unshipped blocks.
+		// Run the shipper's Sync() to upload unshipped blocks. Make sure the TSDB state is active, in order to
+		// avoid any race condition with closing idle TSDBs.
+		if !userDB.casState(active, activeShipping) {
+			level.Warn(util.Logger).Log("msg", "shipper shipped because the TSDB is not active", "user", userID)
```
Comment (pstibrany) [inline pkg/ingester/ingester_v2.go:1509]: typo: "shipper skipped ..."

Should this be a warning? Looks more like a debug message to me.

**Review by pstibrany — APPROVED** [review]
LGTM, good job!

File: pkg/ingester/ingester_v2.go (hunk 1 above)
Comment (pracucci) [reply pkg/ingester/ingester_v2.go:1509]: > typo: "shipper skipped ..."

Ops, fixed!

> Should this be a warning? Looks more like a debug message to me.

Let's find a common ground. I lowered it to Info, but I believe it's worth to notice and most users don't run Cortex with debug log level.

Comment (pstibrany) [reply pkg/ingester/ingester_v2.go]: My reasoning for "debug" level is that there are only two reasons how this can happen:
- during force-compaction, In this case, after force-compaction, flushing will call shipper anyway
- when tsdb is closed (or being closed), in this case we already know that shipper has nothing to ship

I think that in both cases, fact that shipper has skipped its cycle is not interesting.
