### PR TITLE
Fix bug where cleaner does not delete deletable partition group

### LINKED ISSUE #7129: Double compaction after completing partitioning compaction job
**Describe the bug**
As a follow-up from https://github.com/cortexproject/cortex/issues/7075, double compaction can occur for a completed partitioning compaction group. 

Scenario:
T0 Compactor 1: Compaction job for partitioning group version 1 was completed. The cleaner updates the bucket index with the new result blocks and starts deleting parent blocks and partitioned group info file.
T1 Compactor 2: Once bucket index is updated, it groups parent blocks with result blocks of version 1 and created version 2. Starts compacting group 0 of version 2.
T2 Compactor 1: Finishes deleting parent blocks and partitioned group file.
T3 Compactor 2: Finishes compacting group 0 of version 2. Remaining groups of version 2 are invalid because the parent blocks have been deleted. Version 2 is deleted.

The result block from group 0 of version 2 is a double compaction of blocks in version 1.

**To Reproduce**
It is hard to accurately reproduce these steps as the timing of the compaction and cleaning operations must be very close to one another.

**Expected behavior**
A completed partition group does not get re-compacted.

**Environment:**
Infrastructure: A Kubernetes cluster running Cortex as a distributed service, with multiple compactors running concurrently

### PR DESCRIPTION
**Pull request by anna-tran**
**What this PR does**:
A bug was introduced in this PR https://github.com/cortexproject/cortex/pull/7130 where the partition group file is no longer deleted even if it was marked as deletable because the cleaner would only delete partition groups that are both marked as `CanDelete` and `IsCompleted`. This causes invalid partition groups (e.g. a block from the group was deleted) to never be cleaned up.

This PR adds back the deletion logic such that if no blocks were deleted for the deletable partition group, it can still be deleted. It also preserves the logic that partition groups are deleted on the second cleaner cycle if the parent blocks needed to be deleted first.

No tests were updated but this was tested in a distributed environment where that left partition groups dangling, and afterwards were cleaned up with the patched image including this change.

**Which issue(s) this PR fixes**:
Fixes #7129

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by alexqyle** [comment]
LGTM

File: pkg/compactor/blocks_cleaner.go [hunk 1]
```diff
@@ -788,28 +788,29 @@ func (c *BlocksCleaner) cleanPartitionedGroupInfo(ctx context.Context, userBucke
...
-					level.Info(userLogger).Log("msg", "parent blocks deleted, will delete partition group file in next cleaning cycle", "partitioned_group_id", partitionedGroupInfo.PartitionedGroupID)
+			}
+
+			if deletedBlocksCount > 0 {
+				level.Info(userLogger).Log("msg", "parent blocks deleted, will delete partition group file in next cleaning cycle", "partitioned_group_id", partitionedGroupInfo.PartitionedGroupID)
+			} else {
+				if err := userBucket.Delete(ctx, partitionedGroupInfoFile); err != nil {
+					level.Warn(userLogger).Log("msg", "failed to delete partitioned group info", "partitioned_group_info", partitionedGroupInfoFile, "err", err)
 				} else {
-					level.Info(userLogger).Log("msg", "deleting partition group now that all associated blocks have been deleted", "partitioned_group_id", partitionedGroupInfo.PartitionedGroupID)
```
Comment (danielblando) [inline pkg/compactor/blocks_cleaner.go:806]: Can we add this log back?

Comment (anna-tran) [reply pkg/compactor/blocks_cleaner.go:806]: I removed it because it didn't make sense if we delete an invalid partition group. This only applies to Completed partition groups where we delete in 2 phases.

Comment (anna-tran) [reply pkg/compactor/blocks_cleaner.go:806]: I can change it to a generic message like "deleting partition group because either all associated blocks have been deleted or partition group is invalid"

File: CHANGELOG.md [hunk 2]
```diff
@@ -19,6 +19,7 @@
 * [BUGFIX] Ruler: Add XFunctions validation support. #7111
 * [BUGFIX] Querier: propagate Prometheus info annotations in protobuf responses. #7132
 * [BUGFIX] Scheduler: Fix memory leak by properly cleaning up query fragment registry. #7148
+* [BUGFIX] Compactor: Add back deletion of partition group info file even if not complete #7129
```
Comment (SungJin1212) [inline CHANGELOG.md]: Can you fix a PR number?
```suggestion
* [BUGFIX] Compactor: Add back deletion of partition group info file even if not complete #7127
```

Comment (anna-tran) [reply CHANGELOG.md]: Thanks updated
