### PR TITLE
Fix remote read route registration

### LINKED ISSUE #2619: Remote Reads are Broken
Prometheus remote-read requests require a POST method with an encoded `prompb.ReadRequest`. See [here for more context](https://github.com/prometheus/prometheus/blob/1c99adb9fdc79446534e55edba35c676d5e89d57/storage/remote/client.go#L149)

Cortex currently only registers the read endpoint for `GET` requests

### PR DESCRIPTION
**Pull request by jtlisi**
**What this PR does**:

- Ensure the `POST` method is set for the`/read` route registration to match the endpoint in Prometheus. 

**Which issue(s) this PR fixes**:
Fixes #2619

**Checklist**
- [x] Tests updated
- [x] `CHANGELOG.md` updated

### CODE REVIEW

File: pkg/api/api.go [hunk 1]
```diff
@@ -290,7 +290,7 @@ func (a *API) RegisterQuerier(queryable storage.Queryable, engine *promql.Engine
 	cacheGenHeaderMiddleware := getHTTPCacheGenNumberHeaderSetterMiddleware(tombstonesLoader)
 	promHandler := fakeRemoteAddr(cacheGenHeaderMiddleware.Wrap(promRouter))
 
-	a.registerRouteWithRouter(router, a.cfg.PrometheusHTTPPrefix+"/api/v1/read", querier.RemoteReadHandler(queryable), true, "GET")
+	a.registerRouteWithRouter(router, a.cfg.PrometheusHTTPPrefix+"/api/v1/read", querier.RemoteReadHandler(queryable), true, "POST")
```
Comment (slim-bean) [inline pkg/api/api.go:293]: is there any harm in supporting both `GET` and `POST`?

Comment (jtlisi) [reply pkg/api/api.go:293]: `GET` will always return an error since the handler will always try to decode an empty response body. If we only specify `POST`, `GET` will return a method no valid which is what we would want in this case.

Comment (pracucci) [reply pkg/api/api.go:293]: How has this ever worked?

Comment (jtlisi) [reply pkg/api/api.go:293]: We used to not do any form of method validation.

**Comment by pracucci** [comment]
@jtlisi Could you rebase `master`, please?
