### PR TITLE
Bigtable fix family already exists error

### LINKED ISSUE #1249: Index Tables constantly being created if GCS storage is used.
Table manager keeps trying to recreate tables that already exist. Can be an issue with certain schemas that have the same table.

```
...
level=info ts=2019-03-01T18:48:12.674935659Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2564
level=info ts=2019-03-01T18:48:13.102494276Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2565
level=info ts=2019-03-01T18:53:12.677863813Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2564
level=info ts=2019-03-01T18:53:13.104331145Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2565
level=info ts=2019-03-01T18:58:12.676143101Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2564
level=info ts=2019-03-01T18:58:13.103416555Z caller=table_manager.go:354 msg="creating table" table=cortex-ops_index_2565
...
```

Causes an error in bigtable when the family already exists.

### PR DESCRIPTION
**Pull request by jtlisi**
Check to see if the Column family already exists in bigtable and not return an error if it does.
Fixes #1249 
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>

### CODE REVIEW

File: pkg/chunk/gcp/table_client.go [hunk 1]
```diff
@@ -81,6 +83,10 @@ func alreadyExistsError(err error) bool {
 	return ok && strings.Contains(serr.Message(), "already exists")
 }
 
+func familyAlreadyExistsError(err error) bool {
+	return strings.Contains(err.Error(), "AlreadyExists")
```
Comment (tomwilkie) [inline pkg/chunk/gcp/table_client.go]: Is there a better way to detect this?  Like `alreadyExistsError` above - can we reuse the same code?

File: pkg/chunk/gcp/table_client.go [hunk 2]
```diff
@@ -78,7 +81,7 @@ func alreadyExistsError(err error) bool {
 	// This is super fragile, but I can't find a better way of doing it.
 	// Have filed bug upstream: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/672
```
Comment (gouthamve) [inline pkg/chunk/gcp/table_client.go]: Can you fix the comment here?
