### PR TITLE
Filter out "Tagging is not currently supported" errors from DynamoDB Local

### LINKED ISSUE #1484: Table Manager - UnknownOperationException error syncing tables
Hello everyone. I'm having this problem with Table Manager. What can I do to resolve it?

```
level=info ts=2019-07-01T09:46:23.407230048Z caller=table_manager.go:349 msg="creating table" table=cortex_weekly_2489
level=info ts=2019-07-01T09:46:23.910604647Z caller=table_manager.go:349 msg="creating table" table=cortex_weekly_2566
level=info ts=2019-07-01T09:46:24.419691089Z caller=table_manager.go:349 msg="creating table" table=cortex
level=info ts=2019-07-01T09:46:24.918574976Z caller=table_manager.go:349 msg="creating table" table=cortex_chunks_2508
level=info ts=2019-07-01T09:46:25.410324388Z caller=table_manager.go:349 msg="creating table" table=cortex_weekly_2498
level=info ts=2019-07-01T09:46:25.912701971Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=247 expected_tables=247
level=error ts=2019-07-01T09:46:27.359170097Z caller=table_manager.go:174 msg="error syncing tables" err="UnknownOperationException: An unknown operation was requested.\n\tstatus code: 400, request id: f6d1f11e-0833-4842-8080-6edb1adb2798"
level=info ts=2019-07-01T09:48:21.915757892Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=247 expected_tables=247
level=error ts=2019-07-01T09:48:22.921463444Z caller=table_manager.go:174 msg="error syncing tables" err="UnknownOperationException: An unknown operation was requested.\n\tstatus code: 400, request id: 2b38dc64-2b8a-4ab2-b040-9f722f77f586"
level=info ts=2019-07-01T09:50:21.917929145Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=247 expected_tables=247
level=error ts=2019-07-01T09:50:22.929712054Z caller=table_manager.go:174 msg="error syncing tables" err="UnknownOperationException: An unknown operation was requested.\n\tstatus code: 400, request id: 6c650b7e-ce0a-43e5-a002-1c99f4a153d9"
```

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1484 

Also wrap the error so next time we get a weird one it's easier to see where it came from.

### CODE REVIEW

File: pkg/chunk/aws/dynamodb_table_client.go [hunk 1]
```diff
@@ -264,6 +269,18 @@ func (d dynamoTableClient) DescribeTable(ctx context.Context, name string) (desc
 	return
 }
 
+// Filter out errors that we don't want to see
+// (currently only relevant in integration tests)
+func relevantError(err error) bool {
+	if err == nil {
+		return false
+	}
+	if strings.Contains(err.Error(), "Tagging is not currently supported in DynamoDB Local.") {
```
Comment (tomwilkie) [inline pkg/chunk/aws/dynamodb_table_client.go]: Is it possible to do this without string matching?  Is there a `Code()` for it like here:https://github.com/cortexproject/cortex/blob/master/pkg/chunk/aws/dynamodb_storage_client.go#L251

**Comment by tomwilkie** [comment]
Minor nit; LGTM if you can't find a nicer way.

File: pkg/chunk/aws/dynamodb_table_client.go (hunk 1 above)
Comment (bboreham) [reply pkg/chunk/aws/dynamodb_table_client.go]: Sadly `Code()` is `"UnknownOperationException"` in this case.
I can't see a repo or similar to file issues against DynamoDB local.
