### PR TITLE
Fix default memberlist configuration value for RetransmitMult.

### LINKED ISSUE #4010: memberlist keeps resurrecting deleted store-gateways
**Describe the bug**
when performing a scale-up of store-gateway pods followed by a scale-down memberlist entries of deleted store-gateway pods sporadically re-appear after a few hours as unhealthy in the memberlist ring again. 
The system doesn't recover from the ghost entries and they appear and disappear at random.

Screen Shot 2021-03-25 at 9 10 29 AM

In our case we scaled 12 to 80 and back to 12, but this happens with lower scale-up numbers as well. 

**To Reproduce**
1. Start Cortex, using memberlist for store-gateway ring (efd1de49ee9a2ae62ca824845204f66864a31d1f)
2. Scale up store-gateway deployment 
3. Scale down store-gateway deployment
4. keep k8s cluster running for a few hours

**Expected behavior**
Inspecting the cortex store-gateway ring status history for the lifetime of the cluster it shouldn't contain unhealthy store-gateways of deleted pods.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm, custom chart

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
#3603 was a PR to fix it, but it seems it doesn't cover some edge cases.

### PR DESCRIPTION
**Pull request by stevesg**
**What this PR does**:
If configuration is not explicitly given for RetransmitMult (via
`-memberlist.retransmit_factor`), then it is intended to be picked up
from `DefaultLANConfig`. However, though the correct value was being
used to configure `memberlist` itself, zero would be passed into the
`TransmitLimitedQueue` used for broadcasting ring updates. This
essentially means that ring updates are only ever gossiped once.

**Which issue(s) this PR fixes**:
Fixes #4010 (unconfirmed)

**Checklist**
- [x] Tests updated
- [x] ~~Documentation added~~
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Good job! This PR definitely needs a CHANGELOG entry 😉

**Comment by stevesg** [comment]
Looking into unit test failure...

File: integration/integration_memberlist_single_binary_test.go [hunk 1]
```diff
@@ -145,3 +146,77 @@ func newSingleBinary(name string, servername string, join string) *e2ecortex.Cor
...
+
+	maxCortex := 20
+	minCortex := 3
+	instances := make([]*e2ecortex.CortexService, 0)
+
+	for i := 0; i < maxCortex; i++ {
+		name := fmt.Sprintf("cortex-%d", i+1)
+		join := ""
+		if i > 0 {
+			join = fmt.Sprintf("%s-cortex-1:8000", networkName)
```
Comment (pracucci) [inline integration/integration_memberlist_single_binary_test.go:170]: [nit] You can use `instances[0].NetworkContainerHostPort(networkName, "cortex-1", 8000)`

File: integration/integration_memberlist_single_binary_test.go [hunk 2]
```diff
@@ -145,3 +146,77 @@ func newSingleBinary(name string, servername string, join string) *e2ecortex.Cor
...
+	// Sanity check the ring membership and give each instance time to see every other instance.
+
+	for _, c := range instances {
+		require.NoError(t, c.WaitSumMetrics(e2e.Equals(float64(maxCortex)), "cortex_ring_members"))
+		require.NoError(t, c.WaitSumMetrics(e2e.Equals(0), "memberlist_client_kv_store_value_tombstones"))
+	}
+
+	// Scale down as fast as possible but cleanly, in order to send out tombstones.
+
+	for len(instances) > minCortex {
```
Comment (pracucci) [inline integration/integration_memberlist_single_binary_test.go:186]: What do you think if we call `s.Stop()` concurrently (each one in a goroutine) and then wait until all have done? This would be closer to a K8S statefulset scale down operation.

**Review by pstibrany — APPROVED** [review]
Nice find!

**Review by pracucci — APPROVED** [review]
Good job! I left a couple of nits in the integration test. Failing unit tests looks flaky tests unrelated from this PR changes.

**Comment by bboreham** [comment]
I was confused that we document the default `-memberlist.retransmit_factor` as zero, when you say your expectation was that it will be 4.  It seems that `KV.buildMemberlistConfig()` does the same thing with a range of arguments.

Could we have `KVConfig.RegisterFlags()` call `memberlist.DefaultLANConfig()` and obtain the defaults that way?

(this could be a separate issue/PR)

File: integration/integration_memberlist_single_binary_test.go (hunk 1 above)
Comment (stevesg) [reply integration/integration_memberlist_single_binary_test.go:170]: Neat!

File: integration/integration_memberlist_single_binary_test.go (hunk 2 above)
Comment (stevesg) [reply integration/integration_memberlist_single_binary_test.go:186]: Good idea, I'll give it a try.

**Comment by stevesg** [comment]
That's a good idea - makes the defaults more obvious and may have avoided this bug. I'll try it as a separate PR.

**Comment by pstibrany** [comment]
> I was confused that we document the default `-memberlist.retransmit_factor` as zero, when you say your expectation was that it will be 4. It seems that `KV.buildMemberlistConfig()` does the same thing with a range of arguments.
> 
> Could we have `KVConfig.RegisterFlags()` call `memberlist.DefaultLANConfig()` and obtain the defaults that way?
> 

This can introduce unintended change of default values over time. (Our current approach can as well, but it’s more explicit about what’s going on). That said, I think it would be helpful.

**Comment by stevesg** [comment]
Hold off merging this - the unit test failure appears to be a race condition in the unit test: the test will signal to shut down the memberlist service, then it will try and grab the state from the clients. Sometimes the memberlist service will shutdown before the test was able to grab the state.

**Comment by stevesg** [comment]
Fixed now, didn't seem worth pulling out into a separate PR.
