### PR TITLE
fix for query_rejection bug

### LINKED ISSUE #6143: Query Rejection for Metadata Queries Bug
**Describe the bug**
When [Query Rejection](https://github.com/cortexproject/cortex/pull/6005) configured with only properties that is not applicable for the API, then it rejects all the metadata queries. For example, dashboard_uid and panel_id headers are not provided for Metadata queries, and if query rejection configured to only those two fields, then it will reject all the Metadata queries for that tenant. 

**To Reproduce**
Configure Query rejection with below config
```
    query_rejection:
      enabled: true
      query_attributes:
        - dashboard_uid: "dash123"
          panel_id: "panel123"
```
1. Start Cortex (SHA or version)
2. Perform Operations(Query metadata API)

**Expected behavior**
It should only reject queries that is matching the query_attributes. It shouldn't be rejecting metadata queries because they don't match (no dashboard_uid or panel_id header for them)

**Environment:**
 - Any

**Additional Context**

### PR DESCRIPTION
**Pull request by erlan-z**
**What this PR does**:
Fix for bug in query rejection 

**Which issue(s) this PR fixes**:
Fixes #6143 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by danielblando — APPROVED** [review]
LGTM

File: pkg/querier/tripperware/query_attribute_matcher.go [hunk 1]
```diff
@@ -14,7 +14,7 @@ import (
 	"github.com/cortexproject/cortex/pkg/util/validation"
 )
 
-const QueryRejectErrorMessage = "This query has been rejected by the service operator."
+const QueryRejectErrorMessage = "This query does not perform well and has been rejected by the service operator."
```
Comment (yeya24) [inline pkg/querier/tripperware/query_attribute_matcher.go:17]: It is probably unnecessary for this one. But we do make the message a flag in Ingester in order to customize it. https://github.com/cortexproject/cortex/blob/master/pkg/ingester/ingester.go#L162

**Review by yeya24 — APPROVED** [review]
Thanks

File: pkg/querier/tripperware/query_attribute_matcher.go (hunk 1 above)
Comment (yeya24) [reply pkg/querier/tripperware/query_attribute_matcher.go:17]: I wonder if we want to include the first part `does not perform well`. If a regex accidentally matches a good query, does it confuse users?

Comment (erlan-z) [reply pkg/querier/tripperware/query_attribute_matcher.go:17]: In that case, it gives good reason to user to reach out service operator asking why that query does not perform well. We want user to reach out to service team if query is rejected by accident so I think it's good idea to have this part of the error message in case of accidental match.

Comment (yeya24) [reply pkg/querier/tripperware/query_attribute_matcher.go:17]: OK. I think we can leave it for now.
