### PR TITLE
Add "wait ring stability" to store-gateway and fix cold start issue

### LINKED ISSUE #2827: Wait stable store-gateway ring state before running the initial blocks sync
In the event of a cluster cold start or scale up of 2+ store-gateway instances at the same time we may end up in a situation where each new store-gateway instance starts at a slightly different time and thus each one syncs blocks based on a different state of the ring.

## Example of the issue

Consider this cold start scenario (SG = store-gateway):
- T1: SG1 starts
- T2: SG2 starts
- T3: SG1 begins synching blocks based on the current state of the ring (ring: SG1)
- T3: SG3 starts
- T4: SG2 begins synching blocks based on the current state of the ring (ring: SG1, SG2)
- T5: SG3 begins synching blocks based on the current state of the ring (ring: SG1, SG2, SG3)

In case of a replication factor of 1 (but the same applies to clusters with a replication factor > 1), SG1 will initially sync all blocks, SG2 will initially sync 50% of blocks, SG3 will initially sync 30% of blocks.

## Proposal

An idea would be introducing a buffer period before starting synching blocks. During this buffer period we do monitor the ring and wait until the ring state is stable (doesn't change) for at least X seconds, before running the initial sync.

The same approach could be applied to the sync done by the store-gateway each time the ring topology changes, in order to cover the case of existing store-gateway instances re-synching after a scale up (so that they will re-synch blocks once all scaled up instances have started).

Under normal conditions, it's not necessary to have a very large buffer period. For example, 1 minute could be a reasonable default to cover a cluster deployed to Kubernetes.

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does**:
The store-gateway suffers a cold start issue which this PR should fix.

Let's say we have a disruption across all store-gateways and we restart all of them. At startup, each store-gateway is in `JOINING` state in the ring and begin synching blocks. Due to how the `BlocksSync` ring operation works, if all store-gateways are in `JOINING` state (and they are during a cold start), each store-gateway replica syncs **all** the blocks, not just the blocks belonging to their own shard because we extend the replication set for instances in `JOINING` state.

This looks an apparently easy problem to solve, because we could just not extend the replication set for `JOINING` state but then this open to another issue. Let's say we have a pool of running store-gateways and we scale up. If the `JOINING` state doesn't extend the replication set, we can end up in a situation where the previous store-gateways holding a block all offload the block while new replicas are still loading it (`JOINING` state) so no store-gateway has that block and queries fail.

This PR tries to solve this problem changing the logic as follow:
- Load a block when it belongs to store-gateway shard
- Unload a block when it doesn't belong to store-gateway shard anymore **but** at least 1 owner is ACTIVE in the ring (**otherwise wait before offloading**)
- If checking the ring fails, the store-gateway keeps the previously loaded blocks instead of offloading them

This logic change, in conjunction with the "wait ring stability" at startup, should solve the cold start issue. I've added unit tests to show it (they fail in `master`) and I've also manually tested in a dev cluster (my tests show working as expected).

**Which issue(s) this PR fixes**:
Fixes #2827 #3570 

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/storegateway/sharding_strategy.go [hunk 1]
```diff
@@ -115,30 +117,49 @@ func (s *ShuffleShardingStrategy) FilterUsers(_ context.Context, userIDs []strin
...
-		// then we filter it out.
-		if err != nil || !set.Includes(instanceAddr) {
-			if err != nil {
-				level.Warn(logger).Log("msg", "excluded block because failed to get replication set", "block", blockID.String(), "err", err)
-			}
 
+		// A block needs to be always loaded if is owned by the store-gateway itself.
+		set, err := r.Get(key, BlocksOwnerSync, bufDescs, bufHosts, bufZones)
+		if err != nil {
+			level.Warn(logger).Log("msg", "excluded block because failed to get replication set", "block", blockID.String(), "err", err)
```
Comment (pracucci) [inline pkg/storegateway/sharding_strategy.go:135]: Now that I think about this, a better approach may be keep it loaded if it was previously loaded. That would be an improvement over `master` version.

File: pkg/storegateway/sharding_strategy.go [hunk 2]
```diff
@@ -159,18 +180,33 @@ func GetShuffleShardingSubring(ring *ring.Ring, userID string, limits ShardingLi
...
-		userID:   userID,
-		strategy: strategy,
+		userID:     userID,
+		strategy:   strategy,
+		lastBlocks: map[ulid.ULID]struct{}{},
 	}
 }
 
 // Filter implements block.MetadataFilter.
+// This function is NOT safe for use by multiple goroutines concurrently.
```
Comment (pracucci) [inline pkg/storegateway/sharding_strategy.go:197]: It's not used concurrently. Not even Thanos filters are thread-safe. I've added the comment just to make it clear.

**Review by jtlisi — APPROVED** [review]
LGTM, modulo a changelog entry

**Comment by bboreham** [comment]
Does this help #3570 ?

**Comment by pracucci** [comment]
> Does this help #3570 ?

Yes, I think so, because it doesn't expand the replication set anymore for instances in JOINING state. However the replication set would be expanded anyway for unhealthy store-gateways, but if they restart quick enough (before they're detected as unhealthy) then no extra pressure should be added to other (healthy) store-gateways.

File: pkg/storegateway/bucket_store_inmemory_server.go [hunk 3]
```diff
@@ -30,6 +33,13 @@ func (s *bucketStoreSeriesServer) Send(r *storepb.SeriesResponse) error {
 		s.Warnings = append(s.Warnings, errors.New(r.GetWarning()))
 	}
 
+	if rawHints := r.GetHints(); rawHints != nil {
```
[the remark this answers is not in the document]
Comment (pracucci) [reply pkg/storegateway/bucket_store_inmemory_server.go:36]: Yes. It's just used by tests. I've added the ability to read hints too.

**Review by pstibrany — APPROVED** [review]
Nice work. Change makes sense to me, and PR looks great!

**Review by stevesg — APPROVED** [review]
Not an expert on the logic in this area but the code all looks good to me.

**Comment by bboreham** [comment]
Is the "Improved filterBlocksByRingSharding() logic" commit covered by the PR description?  If not please add it.
Consider moving to a separate PR, because I can't see the relationship, and once all the commits are squashed it will be harder to look.

**Comment by pracucci** [comment]
> Is the "Improved filterBlocksByRingSharding() logic" commit covered by the PR description?

Good point. I've added this one to the PR description:
- If checking the ring fails, the store-gateway keeps the previously loaded blocks instead of offloading them

File: docs/blocks-storage/store-gateway.md [hunk 4]
```diff
@@ -81,6 +81,14 @@ The store-gateway replication optionally supports [zone-awareness](../guides/zon
 2. Enable blocks zone-aware replication via the `-store-gateway.sharding-ring.zone-awareness-enabled` CLI flag (or its respective YAML config option). Please be aware this configuration option should be set to store-gateways, queriers and rulers.
 3. Rollout store-gateways, queriers and rulers to apply the new configuration
 
+### Waiting for stable ring at startup
+
+In the event of a cluster cold start or scale up of 2+ store-gateway instances at the same time we may end up in a situation where each new store-gateway instance starts at a slightly different time and thus each one runs the initial blocks sync based on a different state of the ring. For example, in case of a cold start, the first store-gateway joining the ring may load all blocks since the sharding logic runs based on the current state of the ring, which is 1 single store-gateway.
```
Comment (amckinley) [inline docs/blocks-storage/store-gateway.md:86]: Technically, shouldn't this be "greater than or equal to `replication_factor` store-gateway instances at the same time"?

File: docs/blocks-storage/store-gateway.template [hunk 5]
```diff
@@ -81,6 +81,14 @@ The store-gateway replication optionally supports [zone-awareness](../guides/zon
 2. Enable blocks zone-aware replication via the `-store-gateway.sharding-ring.zone-awareness-enabled` CLI flag (or its respective YAML config option). Please be aware this configuration option should be set to store-gateways, queriers and rulers.
 3. Rollout store-gateways, queriers and rulers to apply the new configuration
 
+### Waiting for stable ring at startup
+
+In the event of a cluster cold start or scale up of 2+ store-gateway instances at the same time we may end up in a situation where each new store-gateway instance starts at a slightly different time and thus each one runs the initial blocks sync based on a different state of the ring. For example, in case of a cold start, the first store-gateway joining the ring may load all blocks since the sharding logic runs based on the current state of the ring, which is 1 single store-gateway.
```
Comment (amckinley) [inline docs/blocks-storage/store-gateway.template:86]: Same as above.

File: docs/blocks-storage/store-gateway.md (hunk 4 above)
Comment (pracucci) [reply docs/blocks-storage/store-gateway.md:86]: It depends. For a cold start, yes (because if you have a number of replicas <= RF then all replicas load all blocks). For the scale up case you may have a RF=3 and scale up by +2 and this PR still improve it cause the 2 new replicas will not load extra blocks they will not need anymore once they will be both ACTIVE in the ring (after the initial sync is completed).
