### PR TITLE
Fix flaky TestIngester_flushing

### LINKED ISSUE #3404: Flaky test TestIngester_flushing
**Describe the bug**
The recently introduced test `TestIngester_flushing/flushMultipleBlocksWithDataSpanning3Days` looks to be flaky:

```
--- FAIL: TestIngester_flushing (2.19s)
    --- FAIL: TestIngester_flushing/flushMultipleBlocksWithDataSpanning3Days (0.84s)
        ingester_v2_test.go:1902: 
            	Error Trace:	ingester_v2_test.go:1902
            	            				ingester_v2_test.go:1950
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	TestIngester_flushing/flushMultipleBlocksWithDataSpanning3Days
            	Messages:   	Expected number of calls (1) does not match the actual number of calls (0).
```

**To Reproduce**
[This CI execution](https://github.com/cortexproject/cortex/runs/1316128190) failed.

### PR DESCRIPTION
**Pull request by codesome**
**What this PR does**:

Fixes the flaky test `TestIngester_flushing`

**Which issue(s) this PR fixes**:
Fixes #3404

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ingester/ingester_v2_test.go [hunk 1]
```diff
@@ -1888,17 +1897,20 @@ func TestIngester_flushing(t *testing.T) {
...
 						return false
 					}
-
-					h := db.Head()
-					return h.NumSeries() == 0
+					return db.Head().NumSeries() == 0
 				})
 
+				// The above waiting only ensures compaction, waiting another second to register the Sync call.
+				time.Sleep(1 * time.Second)
```
Comment (codesome) [inline pkg/ingester/ingester_v2_test.go:1910]: This sleep it similar to what we are doing above for other test cases. Additionally added polling for other cases.

**Review by pracucci — APPROVED** [review]
Thanks!

**Review by gouthamve — APPROVED** [review]
