### PR TITLE
Fix querier try store gateways on different zones

### LINKED ISSUE #5468: Retries in blocksStoreQuerier.queryWithConsistencyCheck() doesn't query all zones
**Describe the bug**
With zone aware replication and with RF > number of zones, it's possible that the three retries for the same block can go to replicas in the same zone.

This can be problematic during:
- An AZ outage - even if we have replicas in healthy AZs, we might never query them.
- A Zone based deployment - Multiple store-gateways from the same zone can be brought down and the 3 retries might all hit the store-gateways that are down.

Assume we have 9 replicas for a block:
- sg1 (AZ1)
- sg2 (AZ1)
- sg3 (AZ1)
- sg4 (AZ2)
- sg5 (AZ2)
- sg6 (AZ2)
- sg7 (AZ3)
- sg8 (AZ3)
- sg9 (AZ3)

Assume AZ1 is down and sg1, sg2 and sg3 are not available.
The retry logic picks a random store-gateway from the list and it's possible that all three retries go to the store-gateways in AZ1.

Relavant Code:
- Retry Logic: https://github.com/cortexproject/cortex/blob/master/pkg/querier/blocks_store_queryable.go#L505
- Picking random store-gateways: https://github.com/cortexproject/cortex/blob/master/pkg/querier/blocks_store_replicated_set.go#L147

**To Reproduce**
1. Enable zone aware replication
2. Set RF to 9
3. Bring down multiple store-gateway in the same AZ.

**Expected behavior**
- An AZ outage shouldn't fail a query if there are replicas in other AZs.

### PR DESCRIPTION
**Pull request by yeya24**
**What this PR does**:

This pr changes `GetClientsFor ` method of `BlocksStoreSet ` interface to take an additional map of retried zones.
`blocksStoreReplicationSet` is mainly changed. If zone awareness is not enabled, the logic should be the same. If enabled, the algorithm is:
1. There is a map to track number of attempts for each zone per block.
2. For each block, we get the min attempts over all zones.
3. Iterate all instances in the replication set, if the instance is located in the zone where its attempts == minAttempts, pick the target instance.

**Which issue(s) this PR fixes**:
Fixes #5468

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/querier/blocks_store_replicated_set.go [hunk 1]
```diff
@@ -118,12 +123,19 @@ func (s *blocksStoreReplicationSet) GetClientsFor(userID string, blockIDs []ulid
 		}
 
 		// Pick a non excluded store-gateway instance.
-		addr := getNonExcludedInstanceAddr(set, exclude[blockID], s.balancingStrategy)
-		if addr == "" {
+		instance := getNonExcludedInstanceAddr(set, exclude[blockID], s.balancingStrategy, s.zoneAwarenessEnabled, attemptedBlocksZones[blockID])
```
Comment (harry671003) [inline pkg/querier/blocks_store_replicated_set.go:127]: nit: rename to `getNonExcludedInstance`. It no longer returns `Addr`

File: pkg/querier/store_gateway_client.go [hunk 2]
```diff
@@ -49,6 +49,15 @@ func dialStoreGatewayClient(clientCfg grpcclient.Config, addr string, requestDur
...
+type zoneAwareStoreGatewayClient struct {
+	*storeGatewayClient
+	zone string
+}
+
+func (c *zoneAwareStoreGatewayClient) Zone() string {
+	return c.zone
+}
+
 type storeGatewayClient struct {
```
Comment (harry671003) [inline pkg/querier/store_gateway_client.go:61]: Can the `Zone()` method be added to the existing client? By default it can take a value of `""`.

File: pkg/querier/blocks_store_replicated_set.go [hunk 3]
```diff
@@ -135,25 +145,50 @@ func (s *blocksStoreReplicationSet) GetClientsFor(userID string, blockIDs []ulid
 			return nil, errors.Wrapf(err, "failed to get store-gateway client for %s", addr)
 		}
 
-		clients[c.(BlocksStoreClient)] = blockIDs
+		sgc, ok := c.(*storeGatewayClient)
+		if !s.zoneAwarenessEnabled || !ok {
+			clients[c.(BlocksStoreClient)] = blockIDs
+		} else {
+			bsc := &zoneAwareStoreGatewayClient{storeGatewayClient: sgc, zone: zones[addr]}
```
Comment (harry671003) [inline pkg/querier/blocks_store_replicated_set.go:152]: Do we need a new type here? Can the zone be added to the existing client?

File: pkg/querier/store_gateway_client.go (hunk 2 above)
Comment (yeya24) [reply pkg/querier/store_gateway_client.go:61]: This needs more changes on the pool client struct

File: pkg/querier/blocks_store_replicated_set.go (hunk 1 above)
Comment (yeya24) [reply pkg/querier/blocks_store_replicated_set.go]: Fixed

File: pkg/querier/blocks_store_replicated_set.go (hunk 3 above)
Comment (yeya24) [reply pkg/querier/blocks_store_replicated_set.go]: Changes reverted so should be fixed.

File: pkg/querier/store_gateway_client.go (hunk 2 above)
Comment (yeya24) [reply pkg/querier/store_gateway_client.go]: Changes reverted so should be fixed.

**Review by harry671003 — APPROVED** [review]
LGTM! Thanks Ben.

**Comment by yeya24** [comment]
This seems concerning https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476.

```
query_fuzz_test.go:190: case 105 results mismatch.
        range query: sqrt(
          topk(
            --scalar(count_values by (job, series) ("value", -max({__name__="test_series_a"}))),
            count_values by (series, status_code, __name__) (
              "value",
              max_over_time({__name__="test_series_b"}[1h:1m] offset -3m38s)
            )
          )
        )
        res1: {series="3", status_code="200", value="65"} =>
        1 @[1690304[58](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:59)2.945]
        {series="3", status_code="200", value="67"} =>
        1 @[1690304[61](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:62)2.945]
        1 @[1690304642.945]
        {series="3", status_code="200", value="69"} =>
        1 @[1690304672.945]
        1 @[1690304702.945]
        {series="3", status_code="200", value="75"} =>
        1 @[1690304852.945]
        1 @[1690304882.945]
        {series="4", status_code="400", value="91"} =>
        1 @[1690304732.945]
        1 @[16903047[62](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:63).945]
        {series="4", status_code="400", value="97"} =>
        1 @[1690304912.945]
        1 @[1690304942.945]
        {series="4", status_code="400", value="99"} =>
        1 @[1690304972.945]
        1 @[1690305002.945]
        1 @[1690305032.945]
        1 @[1690305062.945]
        1 @[1690305092.945]
        1 @[1690305122.945]
        {series="5", status_code="500", value="113"} =>
        1 @[1690304792.945]
        1 @[1690304822.945]
        res2: {series="3", status_code="200", value="69"} =>
        1 @[1690304672.945]
        1 @[1690304702.945]
        {series="3", status_code="200", value="73"} =>
        1 @[1690304792.945]
        1 @[1690304822.945]
        {series="4", status_code="400", value="85"} =>
        1 @[1690304582.945]
        {series="4", status_code="400", value="87"} =>
        1 @[1690304612.945]
        1 @[1690304[64](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:65)2.945]
        {series="4", status_code="400", value="91"} =>
        1 @[1[69](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:70)0304732.945]
        1 @[1690304762.945]
        {series="4", status_code="400", value="97"} =>
        1 @[1690304912.945]
        1 @[1690304942.945]
        {series="5", status_code="500", value="115"} =>
        1 @[1690304852.945]
        1 @[1690304882.945]
        {series="5", status_code="500", value="119"} =>
        1 @[16903049[72](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:73).945]
        1 @[1690305002.945]
        1 @[1690305032.945]
        1 @[1690305062.945]
        1 @[1690305092.945]
        1 @[1690305122.945]
    query_fuzz_test.go:1[95](https://github.com/cortexproject/cortex/actions/runs/5659654449/job/15333902668?pr=5476#step:10:96): 
        	Error Trace:	/home/runner/work/cortex/cortex/integration/query_fuzz_test.go:195
        	Error:      	finished query fuzzing tests
        	Test:       	TestVerticalShardingFuzz
        	Messages:   	1 test cases failed
```

**Review by alanprot — APPROVED** [review]

**Comment by alanprot** [comment]
Thanks! LGTM
