### PR TITLE
Distributor: /all_user_stats now show API and Rule Ingest Rate correctly

### LINKED ISSUE #2171: [bug] /all_user_stats don't show correct Rule Ingest Rate
### WHAT

/all_user_stats show Rule Ingest Rate `0` even if rules are defined.

### Version

cortex master-c63a4f2e
image: quay.io/cortexproject/cortex:master-c63a4f2e

### How to reproduce

* setup ruler
* check /all_user_stats

### PR DESCRIPTION
**Pull request by Wing924**
Signed-off-by: Wing924 <weihe924stephen@gmail.com>

**What this PR does**:
* Distributor: `/all_user_stats` now show API and Rule Ingest Rate correctly.

**Which issue(s) this PR fixes**:
Fixes #2171

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ruler/compat.go [hunk 1]
```diff
@@ -39,9 +39,12 @@ func (a *appender) AddFast(l labels.Labels, ref uint64, t int64, v float64) erro
 }
 
 func (a *appender) Commit() error {
-	_, err := a.pusher.Push(user.InjectOrgID(context.Background(), a.userID), client.ToWriteRequest(a.labels, a.samples, nil, client.RULE))
+	wq := client.ToWriteRequest(a.labels, a.samples, nil, client.RULE)
+	_, err := a.pusher.Push(user.InjectOrgID(context.Background(), a.userID), wq)
+	client.ReuseSlice(wq.Timeseries)
```
Comment (bboreham) [inline pkg/ruler/compat.go:44]: This doesn't seem to be part of the PR description?

Comment (Wing924) [reply pkg/ruler/compat.go:44]: it's another bugfix.
I'll update changelog and PR title.

File: pkg/util/push/push.go [hunk 2]
```diff
@@ -17,14 +17,14 @@ func Handler(cfg distributor.Config, push func(context.Context, *client.WriteReq
...
 		var req client.PreallocWriteRequest
-		req.Source = client.API
 		_, err := util.ParseProtoReader(r.Context(), r.Body, int(r.ContentLength), cfg.MaxRecvMsgSize, &req, compressionType)
 		logger := util.WithContext(r.Context(), util.Logger)
 		if err != nil {
 			level.Error(logger).Log("err", err.Error())
 			http.Error(w, err.Error(), http.StatusBadRequest)
 			return
 		}
+		req.Source = client.API
```
Comment (bboreham) [inline pkg/util/push/push.go:27]: why did this move?

Comment (Wing924) [reply pkg/util/push/push.go:27]: `_, err := util.ParseProtoReader(r.Context(), r.Body, int(r.ContentLength), cfg.MaxRecvMsgSize, &req, compressionType)` overwrite that value.

File: pkg/ruler/compat.go (hunk 1 above)
Comment (pracucci) [reply pkg/ruler/compat.go:44]: I don't think this is correct. `a.pusher` is an instance of `Distributor` and the slice reusing is already done there. I think we should rollback this change.

File: pkg/util/push/push.go (hunk 2 above)
Comment (bboreham) [reply pkg/util/push/push.go:27]: I believe that was deliberate: if the caller supplies a value then we use that, otherwise we fall back to `API`.

File: pkg/distributor/distributor.go [hunk 3]
```diff
@@ -360,6 +360,7 @@ func (d *Distributor) Push(ctx context.Context, req *client.WriteRequest) (*clie
 		return nil, err
 	}
 
+	source := req.Source
```
Comment (bboreham) [inline pkg/distributor/distributor.go:363]: This doesn't seem to be adding much; just use `req.Source` when you need it.

File: pkg/util/push/push.go (hunk 2 above)
Comment (Wing924) [reply pkg/util/push/push.go:27]: I tested here and I'm sure `util.ParseProtoReader` will overwrite `req.Source` to `0`.
Because `client.API` equals to `0`, you may not notice it.

**reproduce**
```diff
diff --git a/pkg/ingester/client/cortex.proto b/pkg/ingester/client/cortex.proto
index 6a341b59..a9dfcfee 100644
--- a/pkg/ingester/client/cortex.proto
+++ b/pkg/ingester/client/cortex.proto
@@ -30,7 +30,8 @@ service Ingester {
 message WriteRequest {
   repeated TimeSeries timeseries = 1 [(gogoproto.nullable) = false, (gogoproto.customtype) = "PreallocTimeseries"];
   enum SourceEnum {
-    API = 0;
+    UNKNOWN_SOURCE = 0;
+    API = 2;
     RULE = 1;
   }
   SourceEnum Source = 2;
```
and print `req.Source` before and after`util.ParseProtoReader`.

result:
* before is `API`
* after is `UNKNOWN_SOURCE`

File: pkg/distributor/distributor.go (hunk 3 above)
Comment (Wing924) [reply pkg/distributor/distributor.go]: I've fixed it.

File: pkg/ruler/compat.go (hunk 1 above)
Comment (Wing924) [reply pkg/ruler/compat.go]: I've rolled back this change.

File: pkg/util/push/push.go (hunk 2 above)
Comment (bboreham) [reply pkg/util/push/push.go:27]: Did you test it with and without the caller supplying a value in the protobuf?

Comment (Wing924) [reply pkg/util/push/push.go:27]: I just test it with real remote write from distributor.
I don't think remote write protobuf have `Source` field.

Comment (Wing924) [reply pkg/util/push/push.go:27]: remote write protobuf:
https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto#L22-L24

Comment (pracucci) [reply pkg/util/push/push.go:27]: I agree on @Wing924 on this. The source is not part of the remote write protocol, so we need to inject it after the `WriteRequest` has been deseralized, otherwise the deserialization will overwrite it with the default value.

Comment (Wing924) [reply pkg/util/push/push.go]: I added test to cover both prometheus remote write and cortex writerequest.

File: pkg/util/push/push.go [hunk 4]
```diff
@@ -17,14 +17,16 @@ func Handler(cfg distributor.Config, push func(context.Context, *client.WriteReq
...
 		_, err := util.ParseProtoReader(r.Context(), r.Body, int(r.ContentLength), cfg.MaxRecvMsgSize, &req, compressionType)
 		logger := util.WithContext(r.Context(), util.Logger)
 		if err != nil {
 			level.Error(logger).Log("err", err.Error())
 			http.Error(w, err.Error(), http.StatusBadRequest)
 			return
 		}
+		if req.Source == 0 {
+			req.Source = client.API
+		}
```
Comment (bboreham) [inline pkg/util/push/push.go:29]: As per our [instructions](https://cortexmetrics.io/docs/contributing/#workflow), every commit must explain the changes made.  This is an extraordinary change, so needs a very good explanation.

Comment (pracucci) [inline pkg/util/push/push.go:29]: Getting back to this change, @bboreham as right and I was wrong. The `req.Source` is not overridden by the unmarshalling if not included in the request, so we should have fixed the issue to the root: ensuring `Source` is always set within Cortex.

https://github.com/cortexproject/cortex/blob/master/pkg/ingester/client/cortex.pb.go#L5502-L5520

@Wing924 May you re-iterate on this?

Comment (Wing924) [reply pkg/util/push/push.go:29]: > The req.Source is not overridden by the unmarshalling if not included in the request
It's not true.

Let's change the code like this:
```diff
+ req.Source = 2
		_, err := util.ParseProtoReader(r.Context(), r.Body, int(r.ContentLength), cfg.MaxRecvMsgSize, &req, compressionType)
		logger := util.WithContext(r.Context(), util.Logger)
		if err != nil {
			level.Error(logger).Log("err", err.Error())
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
- if req.Source == 0 {
- 	req.Source = client.API
- }
```
if `Source` is not included in the request, we expect `req.Source` is `2`, right?
But actually it's `0`.
You can check my test.

Comment (Wing924) [reply pkg/util/push/push.go:29]: I'll send another PR to add comment here.

Comment (Wing924) [reply pkg/util/push/push.go:29]: https://github.com/cortexproject/cortex/blob/master/pkg/util/http.go#L107
this line reset req.Source to `0`

Comment (bboreham) [reply pkg/util/push/push.go:29]: How about you explain your change, where I have substituted one const value with its definition for clarity:
```
if req.Source == 0 {
	req.Source = 0
}
```

Comment (Wing924) [reply pkg/util/push/push.go:29]: I know `client.API` is equals to `0` so that you think these code is useless.
This code is explicitly set default value if req.Source is not set.

Comment (Wing924) [reply pkg/util/push/push.go:29]: Physically, `client.API` equals to `0`, but logically, they are different things.

Comment (bboreham) [reply pkg/util/push/push.go:29]: OK, the `Reset()` is indeed the important line, thanks.
So the original code didn't do anything (it set to 0 which was then overridden to 0) and the new code doesn't do anything.
