### PR TITLE
Prevent failed ingestion from affecting rate limiting in distributor.

### LINKED ISSUE #3804: Distributor ingestion rate limit increased for retries due to ingestion failure
The distributor ingestion rate limit increases the number of "consumed tokens" in the rate limiter once the request is received and before writing to ingesters:
https://github.com/cortexproject/cortex/blob/527f9b58b93ce234e8d8624724efeeebcdf7de78/pkg/distributor/distributor.go#L581

In the event of an ingesters outage (eg. 2+ ingesters are unavailable), this means that each tenant remote write request will consume tokens from its rate limiter even if samples have not been successfully ingested. The client (eg. Prometheus) will retry writes and this will further consume tokens from the rate limiter, until it will eventually hit the rate limit, regardless any samples has been actually ingested.

The burst should protect from this, but in the event of a relatively long outage we would end up consuming the burst too (eg. we set burst to 10x the rate limit).

I'm wondering if a better approach would be checking if enough tokens are still available in the rate limiter once the request is received but actually consuming them from the rate limiter only after samples have been successfully written to ingesters. Due to concurrency, the actual accepted rate could be higher than the limit, but we would err in favour of the customer instead of rate limiting for writes we haven't actually ingested.

Related discussions:
- [Distributor rate-limiter should call Wait() not Allow()](https://github.com/cortexproject/cortex/issues/879)

### PR DESCRIPTION
**Pull request by stevesg**
**What this PR does**:
Change the handling of the rate limiting in the distributor such that when the ingestion fails, the reservation in the rate limiter is canceled, returning the tokens for future use in the proceeding requests.

In the process, a change was made to the `util/limiter` package to use `ReserveN`. To match the semantics of `ApplyN`, we have to check the `Delay()` on the returned `rate.Reservation` is zero. I also chose to only expose a limited subset of the rate.Reservation struct (to use `CancelAt`), following from how the existing code does not expose the `x/time/rate` package.

Unit tests added to `rate_limiter_test.go` and `distributor_test.go` to check the cancel behaviour.

**Which issue(s) this PR fixes**:
Fixes #3804

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by stevesg** [comment]
Fixed a couple of typos in comments, and added issue number to changelog.

**Comment by stevesg** [comment]
Rebase, change issue number to PR number.

**Comment by stevesg** [comment]
Fix lint

File: pkg/util/limiter/rate_limiter.go [hunk 1]
```diff
@@ -42,9 +50,29 @@ func NewRateLimiter(strategy RateLimiterStrategy, recheckPeriod time.Duration) *
 	}
 }
 
-// AllowN reports whether n tokens may be consumed happen at time now.
-func (l *RateLimiter) AllowN(now time.Time, tenantID string, n int) bool {
-	return l.getTenantLimiter(now, tenantID).AllowN(now, n)
+// AllowN reports whether n tokens may be consumed happen at time now. The
+// reservation of tokens can be canceled using CancelAt on the returned object.
+func (l *RateLimiter) AllowN(now time.Time, tenantID string, n int) *Reservation {
```
Comment (pracucci) [inline pkg/util/limiter/rate_limiter.go:55]: This is used in the write path, which is an hot path. I think we could avoid extra allocations for `type Reservation struct` doing the following:

1. Change `type Reservation struct` to `type Reservation interface { CancelAt(now time.Time) }` (`*rate.Reservation` will already implements this interface)
2. Change this `AllowN()` return from `*Reservation` to `(bool, Reservation)` (no pointer because now it's an interface) and directly return `(ok, *rate.Reservation)`

The `type Reservation interface` wouldn't be strictly required, but it's a nice to have to abstract away the underlying `*rate.Reservation` so we don't leak it.

File: pkg/distributor/distributor_test.go [hunk 2]
```diff
@@ -413,6 +414,17 @@ func TestDistributor_PushIngestionRateLimiter(t *testing.T) {
 				{metadata: 1, expectedError: httpgrpc.Errorf(http.StatusTooManyRequests, "ingestion rate limit (5) exceeded while adding 0 samples and 1 metadata")},
 			},
 		},
+		"unhappy ingestors: rate limit should be unaffected when ingestion fails": {
```
Comment (pracucci) [inline pkg/distributor/distributor_test.go:417]: They're called "ingesters" not "ingestors". It's a very typical typo.

```suggestion
		"unhappy ingesters: rate limit should be unaffected when ingestion fails": {
```

**Review by pracucci — COMMENTED** [review]
Good job! I left a comment, but overall LGTM!

File: pkg/util/limiter/rate_limiter.go (hunk 1 above)
Comment (stevesg) [reply pkg/util/limiter/rate_limiter.go:55]: Agreed - good point.

File: pkg/util/limiter/rate_limiter.go [hunk 3]
```diff
@@ -42,9 +53,29 @@ func NewRateLimiter(strategy RateLimiterStrategy, recheckPeriod time.Duration) *
...
-	return l.getTenantLimiter(now, tenantID).AllowN(now, n)
+// AllowN reports whether n tokens may be consumed happen at time now. The
+// reservation of tokens can be canceled using CancelAt on the returned object.
+func (l *RateLimiter) AllowN(now time.Time, tenantID string, n int) (bool, Reservation) {
+
+	// Using ReserveN allows cancellation of the reservation, but
+	// the semantics are subtly different to AllowN.
+	r := l.getTenantLimiter(now, tenantID).ReserveN(now, n)
+	if !r.OK() {
+		return false, r
```
Comment (pracucci) [inline pkg/util/limiter/rate_limiter.go:64]: I think the reservation should be nil when failed

```suggestion
		return false, nil
```

File: pkg/util/limiter/rate_limiter.go [hunk 4]
```diff
@@ -42,9 +53,29 @@ func NewRateLimiter(strategy RateLimiterStrategy, recheckPeriod time.Duration) *
...
+
+	// ReserveN will still return OK if the necessary tokens are
+	// available in the future, and tells us this time delay. In
+	// order to mimic the semantics of AllowN, we must check that
+	// there is no delay before we can use them.
+	if r.DelayFrom(now) > time.Duration(0) {
+		// Having decided not to use the reservation, return the
+		// tokens to the rate limiter.
+		r.CancelAt(now)
+		return false, r
```
Comment (pracucci) [inline pkg/util/limiter/rate_limiter.go:75]:
```suggestion
		return false, nil
```

File: pkg/util/limiter/rate_limiter_test.go [hunk 5]
```diff
@@ -127,3 +163,7 @@ func (s *staticLimitStrategy) Burst(tenantID string) int {
 
 	return tenant.burst
 }
+
+func OK(ok bool, r Reservation) bool {
```
Comment (pracucci) [inline pkg/util/limiter/rate_limiter_test.go:167]: No need to expose it. You can rename it to `isOK()` so that doesn't start with an uppercase letter and doesn't clash with `ok` variable too.

**Review by pracucci — APPROVED** [review]
Good job, thanks! LGTM  (modulo a couple of nits)

File: pkg/util/limiter/rate_limiter.go [hunk 6]
```diff
@@ -42,9 +53,29 @@ func NewRateLimiter(strategy RateLimiterStrategy, recheckPeriod time.Duration) *
...
+	r := l.getTenantLimiter(now, tenantID).ReserveN(now, n)
+	if !r.OK() {
+		return false, nil
+	}
+
+	// ReserveN will still return OK if the necessary tokens are
+	// available in the future, and tells us this time delay. In
+	// order to mimic the semantics of AllowN, we must check that
+	// there is no delay before we can use them.
+	if r.DelayFrom(now) > time.Duration(0) {
```
Comment (pstibrany) [inline pkg/util/limiter/rate_limiter.go:71]:
```suggestion
	if r.DelayFrom(now) > 0 {
```

File: pkg/util/limiter/rate_limiter.go [hunk 7]
```diff
@@ -26,6 +26,17 @@ type RateLimiter struct {
 	tenants     map[string]*tenantLimiter
 }
 
+// Reservation is similar to rate.Reservation but excludes interfaces which do
+// not make sense to expose, because we are following the semantics of AllowN,
+// being an immediate reservation, i.e. not delayed into the future.
+type Reservation interface {
```
Comment (pstibrany) [inline pkg/util/limiter/rate_limiter.go:32]: Interface here is not necessary and is actually what adds extra allocation – which is what it tried to prevent in the first place. I would suggest to go back to previous design:

```go
type Reservation struct {
    r *Reservation
}
```

and return it directly as a value and not pointer (!). I would also suggest to add a unit test proving that we don't allocate more than necessary (see `testing.AllocsPerRun()`).

File: pkg/util/limiter/rate_limiter_test.go [hunk 8]
```diff
@@ -127,3 +163,7 @@ func (s *staticLimitStrategy) Burst(tenantID string) int {
 
 	return tenant.burst
 }
+
+func isOK(ok bool, r Reservation) bool {
```
Comment (pstibrany) [inline pkg/util/limiter/rate_limiter_test.go:167]: This function is not necessary.

File: pkg/util/limiter/rate_limiter.go (hunk 7 above)
Comment (stevesg) [reply pkg/util/limiter/rate_limiter.go:32]: That's unfortunate! Makes sense to change it back then.

Comment (pstibrany) [reply pkg/util/limiter/rate_limiter.go:32]: Turns out interface with pointer value doesn't need to do extra allocation, so my objection is not valid.

I still don't think we need the interface here... interfaces in Go are best used to give clients a way to provide different implementations. Interfaces don't hide the underlying implementation, as client code can still do `val.(*rate.Reservation)` on returned value. Custom struct as implemented originally achieves that goal better.

**Review by pstibrany — APPROVED** [review]
Thanks!

File: pkg/util/limiter/rate_limiter.go (hunk 7 above)
Comment (stevesg) [reply pkg/util/limiter/rate_limiter.go:32]: Got confused about this so did a little experiment: https://play.golang.org/p/iHSGnvXzbEx

It seems assigning a pointer (to something which is already allocated) to an interface does not cause an additional allocation. This makes sense, as the interface is sized to hold pointers, but cannot be sized for structs of arbitrary size, hence in the struct case, a heap allocated copy of the struct must be made.

**Comment by bboreham** [comment]
What happens in the case that some samples succeed and some fail?
Looks like distributor acts as if they all failed.
