### PR TITLE
fix regex resolver match 0 or 1 tenant bug

### LINKED ISSUE #7413: Bug: Regex handling issues in tenant federation (Cortex v1.20 / Grafana datasource)
Environment
Cortex version: 1.20

Configuration:
```
tenant_federation:
  enabled: true
  regex_matcher_enabled: true
```
Client: Grafana (Prometheus datasource)

Description

We observed unexpected behavior when using regex-based tenant matching in the Grafana datasource configuration with tenant federation enabled.
Specifically, certain regex patterns either fail validation or produce incomplete query results.

### Issue 1: Unsupported `+` character at end of regex

 `cluster-dev-.+`

This produces a validation/parsing error (see screenshot).
Image

However, the same operator works correctly when used in the middle of the expression: `cluster-.+-dev`

### Issue 2: Missing time series when regex ends with `.*` and there is only one tenant that matches the regex pattern 
When using a regex pattern that ends with `.*`, e.g.: `cluster-stage-.*` and there is only one tenant ID matching the regex, like `cluster-stage-1`,
We observe that data is missing for approximately the last 6 hours

Image

### PR DESCRIPTION
**Pull request by SungJin1212**
Fix `unsupported character` error when `tenant-federation.regex-matcher-enabled` is enabled and the input regex matches 0 or 1 existing tenant.

Ingester Side (Use Single Resolver): The raw regex was propagated to ingesters via context instead of the resolved tenant ID, causing validation errors for patterns containing characters unsupported in tenant IDs (e.g. `+`).

Store Gateway Side: The tenantID is passed by the querier (Use Resolve Resolver),  so the query results are partially returned only by the Store Gateway side in #7413(Issue 2).

**Which issue(s) this PR fixes**:
Fixes #7413 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by CharlieTLe — APPROVED** [review]

File: integration/querier_tenant_federation_test.go [hunk 1]
```diff
@@ -126,6 +126,146 @@ func TestRegexResolver_NewlyCreatedTenant(t *testing.T) {
...
+
+	res, err = clientForMatchOneTenant.Push(series2)
+	require.NoError(t, err)
+	require.Equal(t, 200, res.StatusCode)
+
+	// wait to upload blocks
+	require.NoError(t, ingester.WaitSumMetricsWithOptions(e2e.Greater(0), []string{"cortex_ingester_shipper_uploads_total"}, e2e.WaitMissingMetrics))
+
+	// wait to update knownUsers
+	require.NoError(t, querier.WaitSumMetricsWithOptions(e2e.Greater(0), []string{"cortex_regex_resolver_last_update_run_timestamp_seconds"}), e2e.WaitMissingMetrics)
```
Comment (friedrichg) [inline integration/querier_tenant_federation_test.go]:
```suggestion
	require.NoError(t, querier.WaitSumMetricsWithOptions(e2e.Greater(0), []string{"cortex_regex_resolver_last_update_run_timestamp_seconds"}, e2e.WaitMissingMetrics))
```

**Review by friedrichg — CHANGES_REQUESTED** [review]
see the suggestion

**Review by friedrichg — APPROVED** [review]
