### PR TITLE
fix a flaky test in purger

### LINKED ISSUE #2840: Flake in TestPurger_Metrics
While running the CI on master I've seen this flaky test ([details here](https://app.circleci.com/pipelines/github/cortexproject/cortex/6838/workflows/f024cd69-9fb8-4ac0-99b5-93a8250d9d66/jobs/34385/steps)):

```
--- FAIL: TestPurger_Metrics (2.16s)
    purger_test.go:421: 1 != 0
FAIL
```

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does**:
In `TestPurger_Metrics` test I was starting the purger service [here](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/purger/purger_test.go#L418) after pulling the delete requests for processing [here](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/purger/purger_test.go#L411) which usually should never happen because we always start the service first. This was done to capture an expected metric value.
This was causing Purger to work in an unexpected way causing it to fail the test sometimes. I have changed the test to stop existing purger and create a new one to start the service for delete request processing.

**Which issue(s) this PR fixes**:
Fixes #2840 

**Checklist**
- [x] Tests updated

### CODE REVIEW

File: pkg/chunk/purger/purger_test.go [hunk 1]
```diff
@@ -414,9 +417,17 @@ func TestPurger_Metrics(t *testing.T) {
 	require.InDelta(t, float64(2*86400), testutil.ToFloat64(purger.metrics.oldestPendingDeleteRequestAgeSeconds), 1)
 	require.Equal(t, float64(2), testutil.ToFloat64(purger.metrics.pendingDeleteRequestsCount))
 
-	// start loop to process requests
+	// stop the existing purger
+	require.NoError(t, services.StopAndAwaitTerminated(context.Background(), purger))
```
Comment (pracucci) [inline pkg/chunk/purger/purger_test.go:421]: At the beginning of the test there's a deferred call to `purger.StopAsync()`. Given we're now terminating it here, I believe that call should be removed.
