### PR TITLE
Fix multiple registrations with multi schema

### LINKED ISSUE #2302: Crash on startup with duplicate metrics collector registration
As of commit 59bbc46c, in ingester, querier and ruler.
Beginning of log:

```
level=info ts=2020-03-19T17:56:09.556287259Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000ce550, 0xc000838670, 0x1, 0x1)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.5.0/prometheus/registry.go:400 +0xad
github.com/thanos-io/thanos/pkg/discovery/dns.NewProvider(0x3a17800, 0xc00013b650, 0x3a70400, 0xc0000ce550, 0x3388a7a, 0x6, 0xc0008385f0)
	/go/pkg/mod/github.com/thanos-io/thanos@v0.11.0/pkg/discovery/dns/provider.go:74 +0x36a
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcachedClient(0x7ffd811bb6a1, 0x26, 0x338f0c5, 0x9, 0x0, 0x0, 0x5f5e100, 0x40, 0xdf8475800, 0x0, ...)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/cache/memcached_client.go:101 +0x19c
```

I guess we need integration tests that include memcached.

### PR DESCRIPTION
**Pull request by gouthamve**
Fixes #2302 

@bboreham Can you test if this actually fixes the issue?

### CODE REVIEW

File: pkg/chunk/cache/memcached_client.go [hunk 1]
```diff
@@ -92,17 +94,28 @@ func NewMemcachedClient(cfg MemcachedClientConfig, name string, r prometheus.Reg
...
+	provider, ok := providersForName[name]
+	if !ok {
+		dnsProviderRegisterer := prometheus.WrapRegistererWithPrefix("cortex_", prometheus.WrapRegistererWith(prometheus.Labels{
+			"name": name,
+		}, r))
+
+		provider = dns.NewProvider(util.Logger, dnsProviderRegisterer, dns.GolangResolverType)
+
+		providersForName[name] = provider
+	}
```
Comment (pstibrany) [inline pkg/chunk/cache/memcached_client.go]: I think this belongs outside of this function. Perhaps caller can maintain the map of dns providers, and pass the correct one to the new memcached client?

**Comment by bboreham** [comment]
It stops the crashing, but caches no longer work - just get `caller=memcached.go:164 msg="Failed to get keys from memcached" err="dial tcp :0: connect: connection refused"`

File: integration/configs.go [hunk 2]
```diff
@@ -21,7 +21,17 @@ const (
 	bucketName             = "cortex"
 	cortexConfigFile       = "config.yaml"
 	cortexSchemaConfigFile = "schema.yaml"
-	storeConfigTemplate    = `
+	// Adding an old schema so we test multi schema issues.
```
Comment (pracucci) [inline integration/configs.go]: I think this may break the usage in `integration/chunks_storage_backends_test.go`. Given the `chunks_storage_backends_test.go` already builds a multi schema config, I'm not really sure you need to add this. I think we're already covered there. Am I missing anything?

File: pkg/chunk/storage/factory.go [hunk 3]
```diff
@@ -95,14 +95,28 @@ func (cfg *Config) Validate() error {
...
 	if err != nil {
 		return nil, err
 	}
 
 	// Cache is shared by multiple stores, which means they will try and Stop
 	// it more than once.  Wrap in a StopOnce to prevent this.
-	tieredCache = cache.StopOnce(tieredCache)
+	indexReadCache = cache.StopOnce(indexReadCache)
+	chunksCache = cache.StopOnce(chunksCache)
+	writeDedupeCache = cache.StopOnce(writeDedupeCache)
```
Comment (pstibrany) [inline pkg/chunk/storage/factory.go]: This is a strange design... if store isn't initializing the cache, it should not stop it. Cache should only be stopped after the *last* store stops using it, not by first store. Something to look at in the future I guess.
