### PR TITLE
Make the per labelset series limit error message consistent with per user series error message

### LINKED ISSUE #7009: Error message for max series per label set is incomplete
**Describe the bug**
The [error message](https://github.com/cortexproject/cortex/blob/2ef5de076dec4c8e496eb40fbe590de01ca484b3/pkg/ingester/limiter.go#L211) returned when max series per label set limit is hit is in complete. 

The format for the error message is `"per-labelset series limit of %d exceeded (labelSet: %s, local limit: %d global limit: %d actual)"`, note that we actually don't have a `%d` placeholder for `actual` at the end of the message.

### PR DESCRIPTION
**Pull request by alvinlin123**
**What this PR does**:
See title

**Which issue(s) this PR fixes**:
Fixes #7009

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/ingester/limiter.go [hunk 1]
```diff
@@ -208,8 +208,9 @@ func (l *Limiter) formatMaxMetadataPerMetricError(userID string, metric string)
 }
 
 func (l *Limiter) formatMaxSeriesPerLabelSetError(err errMaxSeriesPerLabelSetLimitExceeded) error {
-	return fmt.Errorf("per-labelset series limit of %d exceeded (labelSet: %s, local limit: %d global limit: %d actual)",
-		minNonZero(err.globalLimit, err.localLimit), err.id, err.localLimit, err.globalLimit)
+	// per labelset limit does not have a configurable local limit like per user max series, so local limit is always zero.
+	return fmt.Errorf("per-labelset series limit of %d exceeded (labelSet: %s, local limit: 0 global limit: %d actual local limit: %d)",
```
Comment (justinjung04) [inline pkg/ingester/limiter.go]: nit: should we drop `local limit: 0` string? I don't see much value in it if it's always 0.

Comment (SungJin1212) [reply pkg/ingester/limiter.go]: Hi @alvinlin123!,
I think it would be better to expose only one of the two: `actualLocalLimit` or `localLimit`.

Comment (alvinlin123) [reply pkg/ingester/limiter.go]: Yup I think that's a good idea to drop the "localLimit" as we don't have local limit config now for per label set series limit. We can always add it back if we decided to add the local limit. Will update this PR.

Comment (SungJin1212) [reply pkg/ingester/limiter.go]: thanks!
