### PR TITLE
Fix visit marker race condition

### LINKED ISSUE #7075: Compactor: Race condition between cleaner and compactor of partitioning compaction could cause incorrect compaction results
**Describe the bug**
A race condition could happen when cleaner deleting previous version of partitioned group info file and its visit marers while another compactor picked up compaction job from previous version of partitioned group info file. This race condition would result in extra result block being compacted based on previous version of partitioned group info file. If there would be a new version of partitioned group info file being generated later on, that extra result block would be treated as result block from new version. Since the result block from previous version always contains few samples than new version, incorrect compaction results would occur under such situation.

**To Reproduce**
It is hard to setup a controllable reproduce steps. Will provide the timeline the race condition happens:

1. compactor x: Generate partitioned group version 1 with total 8 partitions.
1. compactor n..m: Finished compacting all 8 partitions for partitioned group version 1.
1. compactor 1: Load partitioned group version 1 from storage along with all existing and new partitioned groups. And iterating through to pick a compaction job out of them.
1. cleaner: Found partitioned group version 1 got all partitions completed. Delete partitioned group version 1 from bucket store along with all visit markers associated with this partitioned group.
1. compactor 1: Picked partition 0 from partitioned group version 1 for compaction and checked if there was visit marker for this partition. It started compaction since the visit marker was deleted by cleaner.
1. compactor 2: Found there was new lower level block from the same time range got uploaded and generated partitioned group version 2 with total 4 partitions. The partitioned group would contain newly uploaded blocks and all 8 result blocks from partitioned group version 1.
1. compactor n..m: Started compacting partition 1, 2, 3 from partitioned group version 2 since partition 0 got visit marker that was held by compactor 1.
1. compactor 1: Finished compacting partition 0 from partitioned group version 1. Visit marker got updated to complete state for partition 0.
1. compactor n..m: Finished compacting partition 1, 2, 3 from partitioned group version 2. Visit markers got updated to complete state for partition 1, 2, 3.
1. cleaner: Found all 4 partitions were completed based on visit markers. It considered partitioned group version 2 was complete. It marked all parent blocks in partitioned group version 2 for deletion. Those blocks contains newly uploaded blocks and 8 result blocks from partitioned group version 1. 

At the end, blocks got deleted:
- block1: partition 0 from partitioned group version 1
- block2: partition 1 from partitioned group version 1
- block3: partition 2 from partitioned group version 1
- block4: partition 3 from partitioned group version 1
- block5: partition 4 from partitioned group version 1
- block6: partition 5 from partitioned group version 1
- block7: partition 6 from partitioned group version 1
- block8: partition 7 from partitioned group version 1

Blocks were active:
- block9:  partition 0 from partitioned group version 1
- block10: partition 1 from partitioned group version 2
- block11: partition 2 from partitioned group version 2
- block12: partition 3 from partitioned group version 2

There was no incorrect compaction in block10, block11, and block12.

There was incorrect compaction in block9 because:
- Partition 0 from partitioned group version 2 should contain:
  -  1/4 of the data from newly uploaded block
  - all data from block1 and block5
- block9 only contained all data from block1

**Expected behavior**
No incorrect compaction results

**Environment:**
 - Infrastructure: Any distributed environment that has multiple compactors running at same time

**Possible Fix**
- Short term: 
  - Use `CreationTime` from `PartitionedGroupInfo` as a version tracker to make sure the picked compaction job matches the latest version of partitioned group in bucket store.
  - Planner could do such check. After planner passed check for visit marker, it could also make sure partitioned group info still exists in bucket store. If it exists, planner could check `CreationTime` matches.
- Long term:
  - Use leader/worker architecture for compactor.
  - Leader should deal with all the coordinations and cleanup to avoid race condition.
  - Worker should purely do actual compaction only.

### PR DESCRIPTION
**Pull request by danielblando**
**What this PR does**:
Introduce new check if grouper still exist before planner allow compactor to start to prevent race condition on compactor focusing on the short term proposed on #7075

**Which issue(s) this PR fixes**:
Fixes #7075

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/compactor/partition_compaction_planner.go [hunk 1]
```diff
@@ -109,6 +109,34 @@ func (p *PartitionCompactionPlanner) PlanWithPartition(_ context.Context, metasB
...
+			level.Warn(p.logger).Log("msg", "unable to read partition group info during planning", "err", err, "partitioned_group_id", partitionedGroupID, "partition_id", partitionID)
+			return nil, fmt.Errorf("unable to read partition group info for partition ID %d, partitioned group ID %d: %s", partitionID, partitionedGroupID, err.Error())
+		}
+	}
+
+	// Verify that this is the same partition group that the grouper created the visit marker for
+	// by comparing creation times. If they don't match, it means the cleaner deleted the old
+	// partition group and a new one was created with the same ID.
+	expectedCreationTime := partitionInfo.PartitionedGroupCreationTime
+	if currentPartitionedGroupInfo.CreationTime != expectedCreationTime {
```
Comment (yeya24) [inline pkg/compactor/partition_compaction_planner.go:131]: So we only verify it once. Would it be sufficient? Is it possible for the partition group file to be deleted after

**Review by anna-tran — APPROVED** [review]
Nice, thanks for fixing this!

File: pkg/compactor/partition_compaction_planner.go (hunk 1 above)
Comment (danielblando) [reply pkg/compactor/partition_compaction_planner.go:131]: We delete the partition group before deleting the visit markers. 

https://github.com/cortexproject/cortex/blob/a6444ec0c19f37f1dae2a6835360039981ce0adf/pkg/compactor/blocks_cleaner.go#L804-L818

The bug assume that the compactor got the partition group before deletion, choose a partition to compact and when checking the visit marker it was already deleted along with all other that by the cleaner.

**Review by yeya24 — APPROVED** [review]
Thanks!
