### PR TITLE
Fixed Cache fetch error on Redis Cluster

### LINKED ISSUE #4053: redis cluster not supported
**Describe the bug**
When configuring the cache on Redis Cluster, I get the following error. An error occurred in Loki using this client.

```
level=error ts=2021-04-07T09:06:09.604691484Z caller=redis_cache.go:37 msg="failed to get from redis" name=chunksredis err="CROSSSLOT Keys in request don't hash to the same slot"
```
Redis Cluster does not support mget to multiple nodes. It seems that multiple GET calls or pipelines are recommended.

https://github.com/go-redis/redis/issues/291

**To Reproduce**
1. build redis cluster https://redis.io/topics/cluster-tutorial
2. configure redis cache in cortex or loki

I will share the details if necessary.

**Expected behavior**

Support Redis Clsuter as PR expects. reference: https://github.com/cortexproject/cortex/pull/2961

**Environment:**
any

**Storage Engine**
- [ ] Blocks
- [x] Chunks

**Additional Context**

### PR DESCRIPTION
**Pull request by kamijin-fanta**
**What this PR does**:
Redis Cluster may not support MGet. In that case, fall back to multiple Get.

**Which issue(s) this PR fixes**:
Fixes #4053 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/chunk/cache/redis_client.go [hunk 1]
```diff
@@ -110,17 +110,29 @@ func (c *RedisClient) MGet(ctx context.Context, keys []string) ([][]byte, error)
...
-	cmd := c.rdb.MGet(ctx, keys...)
-	if err := cmd.Err(); err != nil {
-		return nil, err
-	}
-
 	ret := make([][]byte, len(keys))
-	for i, val := range cmd.Val() {
-		if val != nil {
-			ret[i] = StringToBytes(val.(string))
+	_, isCluster := c.rdb.(*redis.ClusterClient)
```
Comment (stevesg) [inline pkg/chunk/cache/redis_client.go:114]: Just a question to better understand the fix (I'm not an expect on Redis or the Go bindings).

This is working around an issue/limitation in the bindings, correct? Or a limitation in a particular server version? I only ask because my first reaction to this is that checking the type of an interface feels wrong. If it's the only option, then we'll have to live with it of course.

Either way, it might be nice to put a comment here to explain why we have to check the type.

**Review by stevesg — COMMENTED** [review]
Looks good, just one question. Looks like a useful fix for people using Redis.

File: pkg/chunk/cache/redis_client.go (hunk 1 above)
Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client.go:114]: Thank you for the review!

I thought the same thing, but I think this method is the simplest. The Redis client is initialized with the `NewUniversalClient` .

https://github.com/cortexproject/cortex/blob/v1.8.0/pkg/chunk/cache/redis_client.go#L70

This is the implementation.

https://github.com/go-redis/redis/blob/v8.8.0/universal.go#L199-L206

`UniversalClient` can take `Client` and `ClusterClient`. Single node or sentinel if `Client` is set. mget is always supported. Redis Cluster configuration if `ClusterClient` is set. mget may not be supported.

The only way to check if the Universal Client is Redis Cluster is by type assertion.

Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client.go:118]: Added a comment.

**Review by stevesg — APPROVED** [review]
LGTM

**Review by pstibrany — APPROVED** [review]
Thank you. I don't know much about redis client, but given the comment, it looks reasonable.

File: pkg/chunk/cache/redis_client.go [hunk 2]
```diff
@@ -110,17 +110,34 @@ func (c *RedisClient) MGet(ctx context.Context, keys []string) ([][]byte, error)
...
+	// if redis.ClusterClient is set, then Redis Cluster configuration. mget may not be supported.
+	_, isCluster := c.rdb.(*redis.ClusterClient)
+
+	if isCluster {
+		for i, key := range keys {
+			cmd := c.rdb.Get(ctx, key)
+			if err := cmd.Err(); err != nil {
+				return nil, err
+			}
+			ret[i] = StringToBytes(cmd.Val())
```
Comment (pracucci) [inline pkg/chunk/cache/redis_client.go:126]: If a key doesn't exist, then `ret[i]` is expected to be `nil`. I don't think it's the case here.

Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client.go:126]: @pracucci thanks for reviewing! `c.rdb.MGet(...).Val()` returns `[]interface{}`, but `c.rdb.Get(...).Val()` returns string. If the value is not found, it will return an empty string.

Comment (pracucci) [reply pkg/chunk/cache/redis_client.go:126]: > If the value is not found, it will return an empty string.

I think this break the behaviour (see my previous comment above). Having a unit test to prove / disprove it would be great.

**Comment by pracucci** [comment]
@kamijin-fanta 👋  Would you have some time to take a look at my last comment, please? Thanks!

File: pkg/chunk/cache/redis_client.go (hunk 2 above)
Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client.go:126]: understood. Thank you!

Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client.go]: Processed the empty values and added the tests. The tests confirm that the behavior is the same for Single and Cluster configurations of Redis.

**Comment by gouthamve** [comment]
Can you please rebase against master to pull in https://github.com/cortexproject/cortex/pull/4137 and move the changelog entry to the top?

File: CHANGELOG.md [hunk 3]
```diff
@@ -73,6 +73,7 @@
 * [BUGFIX] Frontend, Query-scheduler: allow querier to notify about shutdown without providing any authentication. #4066
 * [BUGFIX] Querier: fixed race condition causing queries to fail right after querier startup with the "empty ring" error. #4068
 * [BUGFIX] Compactor: Increment `cortex_compactor_runs_failed_total` if compactor failed compact a single tenant. #4094
+* [BUGFIX] Fixed cache fetch error on Redis Cluster. #4056
```
Comment (pracucci) [inline CHANGELOG.md:76]: Please rebase `master` and move this CHANGELOG entry to the top. We've cut 1.9 release in the meanwhile. Thanks!

File: pkg/chunk/cache/redis_client_test.go [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+
+	cluster, err := mockRedisClientCluster()
+	require.Nil(t, err)
+	defer cluster.Close()
+
+	ctx := context.Background()
+
+	clients := []*RedisClient{single, cluster}
+	for i, c := range clients {
+		meg := []string{"run on single redis client", "run on cluster redis client"}[i]
```
Comment (pracucci) [inline pkg/chunk/cache/redis_client_test.go:26]: It's a little convoluted. Instead of passing ` meg` (I guess you meant `msg`) to each assertion function, you can run the test within a `t.Run(description, func(t *testing.T) { /* your test logic here */})` and having the description only passed to `t.Run()`.

Following this example, a common pattern is using table testing to define the test cases. As example, I'm picking a random test where we use table testing:
https://github.com/cortexproject/cortex/blob/5009276fdd385587a13f1492520cc38647512bc6/pkg/chunk/schema_config_test.go#L306-L312

Comment (kamijin-fanta) [reply pkg/chunk/cache/redis_client_test.go]: thanks. fixed to assigned name and client to slice.

File: CHANGELOG.md (hunk 3 above)
Comment (pracucci) [reply CHANGELOG.md:93]: @kamijin-fanta This commit is still valid. Could you address it, please?

**Review by pracucci — APPROVED** [review]
Thanks @kamijin-fanta! LGTM. Please address the comment in the CHANGELOG and then we can merge. Thanks again!
