### PR TITLE
Query Frontend: Fix slow query logging if 'LogQueriesLongerThan' is set to < 0

### LINKED ISSUE #4610: Frontend: Parameter 'LogQueriesLongerThan' does not behave as described in the docs
Hello :wave: 

At Thanos, we have noticed that the `LogQueriesLongerThan` does not behave as is described in the docs:
`Log queries that are slower than the specified duration. Set to 0 to disable. Set to < 0 to enable on all queries.` 

In particular, setting the parameter to < 0 does not make it to log all queries, it actually disables logging (quick glance at the code seem to confirm this). 

What is the correct way to handle this? Should the functionality be adjusted to adhere to the docs or should the docs be amended to describe current behavior?

### PR DESCRIPTION
**Pull request by matej-g**
Signed-off-by: Matej Gera <matejgera@gmail.com>

**What this PR does**:
Fixes the behavior of Query Frontend when it comes to logging slow queries - if the parameter is set to < 0, all queries should be logged, as is described in the documentation. However, presently, the opposite is true - if set to < 0, logging is disabled altogether.

Leaving the parameter at `0` should still retaing the same behavior, i.e. disabling slow query logging.

**Which issue(s) this PR fixes**:
Fixes #4610

**Checklist**
- [X] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/frontend/frontend_test.go [hunk 1]
```diff
@@ -111,7 +111,8 @@ func TestFrontend_LogsSlowQueriesFormValues(t *testing.T) {
 
 	// Configure the query-frontend with the mocked downstream server.
 	config := defaultFrontendConfig()
-	config.Handler.LogQueriesLongerThan = 1 * time.Microsecond
+	// Setting to < 0 to ensure all queries are logged.
+	config.Handler.LogQueriesLongerThan = -1 * time.Microsecond
```
Comment (bboreham) [inline pkg/frontend/frontend_test.go:115]: I was a bit surprised that this is changing what the test does, rather than testing the old and new behaviour.
However I think the test should have had both a slow and a fast query to test the old one properly.

**Review by bboreham — APPROVED** [review]
OK to merge, but I had one comment on the test.

File: pkg/frontend/frontend_test.go (hunk 1 above)
Comment (matej-g) [reply pkg/frontend/frontend_test.go:115]: I thought the reason this was set so low was to in fact log every query for the purpose of this test. But I agree to have both cases tested separately would be nicer, I'll add it.

Comment (matej-g) [reply pkg/frontend/frontend_test.go]: I added the test case, let me know what you think!

**Review by alanprot — APPROVED** [review]
