### PR TITLE
Run local KES for S3 integration tests

### LINKED ISSUE #4543: Integration tests depend on minio kes experimental environment
**Describe the bug**
We depend on the experimental env from [minio](https://docs.min.io/docs/minio-kms-quickstart-guide.html) to run our s3 kes integration tests.
[TestS3Client](https://github.com/cortexproject/cortex/blob/master/integration/s3_storage_client_test.go#L68-L92) use endpoint [https://play.min.io:7373](https://github.com/cortexproject/cortex/blob/master/integration/e2e/db/db.go#L42) to generate keys.

We are recently failing on this test without any code change. It can be simply because the endpoint is down
```
=== RUN   TestS3Client/config-with-sse-s3
10:46:19 minio-9000: API: PutObject(bucket=cortex, object=key-config-with-sse-s3)
10:46:19 minio-9000: Time: 17:46:19 UTC 10/29/2021
10:46:19 minio-9000: DeploymentID: a997074b-4bc1-40c6-a61b-79ab6fefe5b3
10:46:19 minio-9000: RequestID: 16B29175BEA3F08C
10:46:19 minio-9000: RemoteHost: 172.31.0.1
10:46:19 minio-9000: Host: 127.0.0.1:55356
10:46:19 minio-9000: UserAgent: aws-sdk-go/1.40.37 (go1.17.2; darwin; amd64)
10:46:19 minio-9000: Error: Post https://play.min.io:7373/v1/key/generate/my-minio-key: dial tcp 147.75.201.93:7373: i/o timeout
10:46:19 minio-9000: 4: cmd/api-errors.go:1743:cmd.toAPIErrorCode()
10:46:19 minio-9000: 3: cmd/api-errors.go:1768:cmd.toAPIError()
10:46:19 minio-9000: 2: cmd/object-handlers.go:1273:cmd.objectAPIHandlers.PutObjectHandler()
10:46:19 minio-9000: 1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
10:46:19 minio-9000: API: PutObject(bucket=cortex, object=key-config-with-sse-s3)
10:46:19 minio-9000: Time: 17:46:19 UTC 10/29/2021
10:46:19 minio-9000: DeploymentID: a997074b-4bc1-40c6-a61b-79ab6fefe5b3
10:46:19 minio-9000: RequestID: 16B29175BEA3F08C
10:46:19 minio-9000: RemoteHost: 172.31.0.1
10:46:19 minio-9000: Host: 127.0.0.1:55356
10:46:19 minio-9000: UserAgent: aws-sdk-go/1.40.37 (go1.17.2; darwin; amd64)
10:46:19 minio-9000: Error: Post https://play.min.io:7373/v1/key/generate/my-minio-key: dial tcp 147.75.201.93:7373: i/o timeout
10:46:19 minio-9000: 4: cmd/api-errors.go:1743:cmd.toAPIErrorCode()
10:46:19 minio-9000: 3: cmd/api-errors.go:1768:cmd.toAPIError()
10:46:19 minio-9000: 2: cmd/object-handlers.go:1273:cmd.objectAPIHandlers.PutObjectHandler()
10:46:19 minio-9000: 1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
    s3_storage_client_test.go:106: 
        	Error Trace:	s3_storage_client_test.go:106
        	Error:      	Received unexpected error:
        	            	InternalError: We encountered an internal error, please try again.
        	            		status code: 500, request id: 16B29175BEA3F08C, host id: 
        	Test:       	TestS3Client/config-with-sse-s3
10:46:19 Killing minio-9000
    --- FAIL: TestS3Client/config-with-sse-s3 (29.98s)
``` 

**To Reproduce**
1. Make cortex image
2. Run integration test: ```go test -v -tags=requires_docker ./integration -run "^TestS3Client$"```

**Expected behavior**
We always succeed integration tests without depending on external source.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Storage Engine**
- [ ] Blocks
- [ ] Chunks

**Additional Context**
The project already have some quick instruction on how to implement a server for integration tests
https://github.com/minio/kes/issues/137

They also have a docker image to run the server
https://hub.docker.com/r/minio/kes/dockerfile

### PR DESCRIPTION
**Pull request by bboreham**
**What this PR does**:

Instead of calling out to play.min.io, run the KES service locally in a container.
Generate its key and cert instead of downloading them from GitHub.

By depending on fewer third-party services we reduce test failures.

Extract function to generate PKI certificates.
Update to more recent Minio image; not using the very latest KES because it removed `--root` which is useful.
Re-enable the SSE tests (see #4545)

**Which issue(s) this PR fixes**:
Fixes #4543 

**Checklist**
- [x] Tests updated
- NA Documentation added
- NA CHANGELOG.md - not a user-visible change.

### CODE REVIEW

**Review by danielblando — APPROVED** [review]

File: integration/e2e/db/db.go [hunk 1]
```diff
@@ -33,17 +46,27 @@ func NewMinio(port int, bktNames ...string) *e2e.HTTPService {
...
+func NewKES(port int, serverKeyFile, serverCertFile, rootCertFile string) *e2e.HTTPService {
+	// Run this as a shell command, so sub-shell can evaluate 'identity' of root user.
+	command := fmt.Sprintf("/kes server --addr 0.0.0.0:%d --key=%s --cert=%s --root=$(/kes tool identity of %s) --auth=off --quiet",
+		port, filepath.Join(e2e.ContainerSharedDir, serverKeyFile), filepath.Join(e2e.ContainerSharedDir, serverCertFile), filepath.Join(e2e.ContainerSharedDir, rootCertFile))
+
+	m := e2e.NewHTTPService(
+		"kes",
+		images.KES,
+		e2e.NewCommandWithoutEntrypoint("sh", "-c", command),
+		nil, // KES only supports https calls - TODO make Scenario able to call https or poll plain TCP socket.
```
Comment (pracucci) [inline integration/e2e/db/db.go:67]: We have `TCPReadinessProbe`. Does it work to you?

**Review by pracucci — APPROVED** [review]

**Review by alvinlin123 — APPROVED** [review]
