### PR TITLE
Fix failing integration tests

### LINKED ISSUE #2884: Data race in TestRejoin test
```
==================
WARNING: DATA RACE
Write at 0x0000019f0d40 by goroutine 81:
  github.com/cortexproject/cortex/pkg/ring/kv/memberlist.TestRejoin()
      /go/src/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/memberlist_client_test.go:989 +0xc2
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:991 +0x1eb

Previous read at 0x0000019f0d40 by goroutine 130:
  github.com/cortexproject/cortex/pkg/ring/kv/memberlist.(*TCPTransport).WriteTo()
      /go/src/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/tcp_transport.go:390 +0x33e
  github.com/hashicorp/memberlist.(*shimNodeAwareTransport).WriteToAddress()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/transport.go:122 +0xac
  github.com/hashicorp/memberlist.(*Memberlist).rawSendMsgPacket()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:770 +0x347
  github.com/hashicorp/memberlist.(*Memberlist).sendMsg()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:707 +0x3b2
  github.com/hashicorp/memberlist.(*Memberlist).encodeAndSendMsg()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:677 +0x134
  github.com/hashicorp/memberlist.(*Memberlist).handlePing()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:511 +0x4d5
  github.com/hashicorp/memberlist.(*Memberlist).handleCommand()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:370 +0xff
  github.com/hashicorp/memberlist.(*Memberlist).handleCompound()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:479 +0x13d
  github.com/hashicorp/memberlist.(*Memberlist).handleCommand()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:365 +0x606
  github.com/hashicorp/memberlist.(*Memberlist).handleCompressed()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:668 +0x221
  github.com/hashicorp/memberlist.(*Memberlist).handleCommand()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:367 +0x6c2
  github.com/hashicorp/memberlist.(*Memberlist).ingestPacket()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:353 +0x3d1
  github.com/hashicorp/memberlist.(*Memberlist).packetListen()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/net.go:316 +0x11b

Goroutine 81 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:134 +0x347

Goroutine 130 (finished) created at:
  github.com/hashicorp/memberlist.newMemberlist()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/memberlist.go:217 +0x9ca
  github.com/hashicorp/memberlist.Create()
      /go/src/github.com/cortexproject/cortex/vendor/github.com/hashicorp/memberlist/memberlist.go:228 +0x3c
  github.com/cortexproject/cortex/pkg/ring/kv/memberlist.(*KV).starting()
      /go/src/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/memberlist_client.go:374 +0xef
  github.com/cortexproject/cortex/pkg/ring/kv/memberlist.(*KV).starting-fm()
      /go/src/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/memberlist_client.go:358 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /go/src/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
```

From: https://app.circleci.com/pipelines/github/cortexproject/cortex/7024/workflows/941c3734-da3f-453c-b1eb-3471419b8d49/jobs/35218/steps

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does**: This PR fixes two problems: race condition from issue #2884, caused by modifying logger between memberlist tests, and [integration test failure](https://app.circleci.com/pipelines/github/cortexproject/cortex/8081/workflows/90ea6173-242b-46f0-9364-fc187802c431/jobs/39962) caused by missing dependancy between store-queryable and memberlist-kv.

**Which issue(s) this PR fixes**:
Fixes #2884 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/cortex/modules.go [hunk 1]
```diff
@@ -611,7 +611,7 @@ func (t *Cortex) initMemberlistKV() (services.Service, error) {
 	t.Cfg.MemberlistKV.Codecs = []codec.Codec{
 		ring.GetCodec(),
 	}
-	t.MemberlistKV = memberlist.NewKVInitService(&t.Cfg.MemberlistKV)
+	t.MemberlistKV = memberlist.NewKVInitService(&t.Cfg.MemberlistKV, util.Logger)
```
Comment (jtlisi) [inline pkg/cortex/modules.go:614]: **suggestion [non-blocking]**: It may make sense to wrap the logger passed here with a `component` field?

**Review by jtlisi — APPROVED** [review]
LGTM

File: pkg/cortex/modules.go (hunk 1 above)
Comment (pstibrany) [reply pkg/cortex/modules.go:614]: It sounds like a good idea, but log messages already look like this:

```
level=warn ts=2020-09-11T14:30:13.182589778Z caller=memberlist_client.go:541 msg="broadcast messages left in queue" count=1 nodes=1
```

So they include `memberlist_client.go`. Adding component to it would be probably too much.

Comment (jtlisi) [reply pkg/cortex/modules.go:614]: 👍 Makes sense
